- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
> Bugfix: continuous channel bug when sliced within a time step.

- lumicks/pylake/calibration.py
- lumicks/pylake/channel.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_channels.py
- lumicks/pylake/tests/test_file.py
* Adds calibration slicing for continuous and time series force channels.
* Adds slicing for calibration data.
* Adds tests for the new functionality.
* Add error message when start or stop of empty timeseries is requested.
> Ng 954 - Read calibrations from HDF5

- lumicks/pylake/channel.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/file.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
- Adds slicing behaviour to kymograph objects.
- Adds tests and fixture for kymo loading from file.
- Slightly modifies kymograph constructor interface to bring it more in line with other files (constructing from data using from_dataset rather than directly in the constructor).
- Adds tests for kymograph slicing.
- Adds convenience option to directly specify a plotting range using xlim and ylim for the kymograph plotting function (even without slicing).
> Ng 1888 - Implement slicing behaviour for kymographs

- changelog.md
- docs/api.rst
- docs/tutorial/correlatedstack.png
- docs/tutorial/correlatedstacks.rst
- docs/tutorial/file.rst
- docs/tutorial/index.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_correlated_stack.py
- Adds documentation for the new functionality.
- Add some input checking for downsampled_over. Checks whether stack overlaps with channel being downsampled, since this can give very confusing errors otherwise.
> Add documentation CorrelatedStack and check whether stack overlaps with channel

- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
Revision of #11 
Last PR related to this issue replaced a bug with a different bug, which wasn't immediately apparent since the test was performed with a time step of two. 😭 
This time fixes the continuous slicing properly and adds more testing to prevent this in the future. Since the previous version was not released independently, I have not added anything new to the changelog, since it is an amendment to a development build.
> Bugfix continuous slicing

- changelog.md
- lumicks/pylake/__about__.py
Update changelog date and version number for release.
> Update changelog date and version number for release.

- lumicks/pylake/detail/mixin.py
- lumicks/pylake/kymo.py
- lumicks/pylake/point_scan.py
NG-2241
Added properties to confocal items to retrieve power percentage for excitation and sted laser.
Companion to https://github.com/lumicks/bluelake/pull/777
> confocal: added lasers power interface

- lumicks/pylake/__about__.py
> Bump version number

- .gitignore
- release.md
> docs: add release procedure

- lumicks/pylake/kymotracker/detail/trace_line_2d.py
- lumicks/pylake/kymotracker/tests/test_tracing.py
- lumicks/pylake/tests/test_kymotracker.py
This PR adds some functionality to KymoLine:
- Sampling of image data using the coordinates of the line and a width. 
- Adding an offset.
- Checking whether the line is inside a rect.
> Kymo: Add some functionality to KymoLine

- changelog.md
- lumicks/pylake/__about__.py
Readying for release v0.6.2.
Also piggybacked a minor change into the changelog to include where to find information about the FdWidget.
> release: readying for releasing v0.6.2

- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
Added time property to Slice class. Converts absolute timestamps (in nanoseconds) to relative time (in seconds) to help with data visualization
> Lk51 timeprop

- changelog.md
- docs/refs.bib
- docs/tutorial/fdfitting.rst
- docs/tutorial/profile_bad.png
- docs/tutorial/profile_good.png
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/fitting/tests/test_profiles.py
- lumicks/pylake/fitting/tests/test_stepping.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/tests/test_fdfit.py
This PR aims to expose some of the asymptotic methods for computing parameter confidence intervals and introduces the non-asymptotic method (which was also used to confirm results of the former). The reason for this addition is that some customers requested the ability to calculate uncertainties on their parameters.
In this PR:
- Improvement in the standard deviation estimate of the noise on the data.
- Profile Likelihood method.
- Docs and tests for all.
Docs here: https://lumicks-pylake.readthedocs.io/en/profile_likelihood/tutorial/fdfitting.html#confidence-intervals-and-standard-errors
The profile likelihood method is a method for detecting non-identifiabilities and seeing which parameters are related. This method traces an optimal path through parameter space in order to estimate …
> Profile likelihood

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
this PR adds downsampling to a specific frequency for both Continuous and (possibly variable frequency) TimeSeries channels
> downsample Slice to frequency

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_correlated_stack.py
- setup.py
This PR adds feature to `CorrelatedStack` object to reconstruct an RGB image from the alignment matrices calculated in Bluelake. Functionality also added for plotting 16-bit RBG images in addition to the grayscale 8-bit images already implemented.
> CorrelatedStack: align image

- changelog.md
- lumicks/pylake/__about__.py
Want to do the release procedure for v0.7.1. Partially because we want a DOI, but also because it'd be nice to have the STED bugfix out there.
> release: readying for release v0.7.1

- readme.md
So people have a DOI they can cite when using Pylake.
> Add doi badge to readme

- lumicks/pylake/__init__.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/conftest.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/tests/test_kymotracker.py
Using the algorithms by hand is really cumbersome. This widget helps users actually use it.
**Movies**
**Where is algorithm 2?**
Algorithm 2 is pending.
**Why no widget coverage and where are the docs?**
I tried my best to test all the endpoints that actually do something for the different cases that can occur.
I have however not found a good way to test the actual widgets. In the last PR for this thing I will include both the documentation and an acceptance test-type document for how to test whether this thing isn't broken before a Pylake release.
Note: This PR depends on https://github.com/lumicks/pylake/pull/89 and https://github.com/lumicks/pylake/pull/90
> nbwidgets: add kymotracker widget

- .gitattributes
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/reference_spectrum.npz
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
We want to move force calibration into Pylake. We may want to refactor some of the code, but for this, we first need to make sure the code is tested. This first PR just imports the code as-is and adds testing.
The current version of the force calibration script.
- Tests for the power spectrum computation
- Tests for the power spectrum blocking
- Integration tests for power spectrum fitting based on a theoretical Lorentzian
- Integration test with real BL data.
- A reference spectrum in an npz file which is stored on git-lfs.
- An extra step in ci that also checks out the lfs materials.
**What's not in this PR?**
- A nice API for Pylake.
- Refactoring of `lumicks/pylake/force_calibration/powerspectrum_calibration.py`. Please defer comments on this …
> Moving force calibration into Pylake

- changelog.md
- lumicks/pylake/__about__.py
**Why?**
We wish to release v0.8 since it brings many new features, bugfixes and a performance improvement to the table.
> release: preparing for v0.8.0

- docs/install.rst
It's probably better to try to make a new environment rather than try and force conda to update all in case of trouble.
> docs: remove troubleshooting section

- .github/CODEOWNERS
Because docs also need review :)
> git: make code owners apply to all files

- changelog.md
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cas9_kymotracking/kymowidget.png
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/nb_widgets/detail/mouse.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/nb_widgets/tests/test_mouse.py
- lumicks/pylake/tests/test_kymotracker.py
**What is this PR?**
This PR allows manually connecting two kymograph lines in the kymotracker widget.
This was a highly requested feature.
> Kymotracker: Allow stitching lines manually

- changelog.md
- docs/refs.bib
- docs/tutorial/kymotracking.rst
- docs/tutorial/msdplot_100_lags.png
- docs/tutorial/msdplot_default_lags.png
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
- lumicks/pylake/tests/test_kymotracker.py
With the backend existing, it would be nice to have a user facing API so that users can actually use it.
_Figure 1: And this is why you only use a few points! Horrible!_
You can find the docs here:
https://lumicks-pylake.readthedocs.io/en/msd_api/tutorial/kymotracking.html#studying-diffusion-processes
> API for MSD-based methods [MSD 3 of N]

- lumicks/pylake/fitting/tests/test_stepping.py
When running `pytest --pyargs lumicks.pylake` there is a test failure in `fitting\tests\test_stepping.py`
It seems that when invoking pytest in that way the warning fails the test despite the filterwarning decorator which is supposed to let the test pass despite the warning.
Regardless of this, it is better to explicitly use the context manager to check whether the warning fired, rather than silence it and only look at the result of the stepper.
> fitting: make test check warning explicitly

- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
For active calibration, we need to be able to average spectra of subdivisions of the data. The use case for this is that you want to average multiples of the period of the driving frequency such that the driving peak ends up in a single data point. That way, you can get a power estimate using just that bin. The test specifically tests for this.
See below how much of an error you can make when you don't ensure that.
> force_calibration: add windowing to PowerSpectrum

- lumicks/pylake/kymotracker/detail/gaussian_mle.py
- lumicks/pylake/kymotracker/tests/data/gaussian_data_1d.npz
- lumicks/pylake/kymotracker/tests/data/generate_gaussian_data.py
- lumicks/pylake/kymotracker/tests/test_gaussian_mle.py
Why this PR?
Adding another type of kymotrack refinement for better estimation of localization (and localization uncertainty). This procedure specifically takes into account the Poisson nature of the signal/noise in confocal images.
This PR sets up all of the algorithms for the actual optimization (backend). The user-facing API dealing with KymoLine and other kymotracker-specific classes will be in the next PR.
This second attempt incorporates lessons learned from working on 2D gaussian localization for separate project. All parameters are now handled in physical units (photon counts, nm). Additionally, this PR does not include support for fitting with shared parameters between different image frames.
What's included
- Gaussian peak parameterized by total photon count, center, width , and …
> Peak localization by Gaussian MLE - version 2

- changelog.md
- docs/api.rst
- docs/refs.bib
- docs/tutorial/kymo_gau_window.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/data/gaussian_data_1d.npz
- lumicks/pylake/kymotracker/tests/data/generate_gaussian_data.py
- lumicks/pylake/kymotracker/tests/data/kymo_data_2lines.npz
- lumicks/pylake/kymotracker/tests/test_gaussian_mle.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
Why this PR?
Sets up the user-facing API to use the algorithms implemented in #170 . 
Docs are [here](https://lumicks-pylake.readthedocs.io/en/refine_gau_v2/tutorial/kymotracking.html)
> Peak localization by Gaussian MLE - v2 - Part 2: Public API

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/__about__.py
We want to get a release out that has a hotfix for the critical bug that existed in the kymograph slicing.
> release: prepare for releasing v0.10.0

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Fixes https://github.com/lumicks/pylake/issues/178 .
> kymowidget: show error when refining before tracking

- changelog.md
- docs/install.rst
- lumicks/pylake/__about__.py
It's been a while since we did a Pylake release.
I included a small fixup in the docs which slipped my attention when I reviewed that PR.
**What to look for**
Please have a look whether all the changelog entries are clear and understandable.
Docs build here: https://lumicks-pylake.readthedocs.io/en/release_v0_11/install.html
Changelog here: https://lumicks-pylake.readthedocs.io/en/release_v0_11/changelog.html
> Release pylake v0.11

- lumicks/pylake/force_calibration/tests/test_hydro.py
This case was not specifically covered but provides a good integration test / sanity check for the surface handling.
For small beads, the results (Rf, Rd, and kappa) with or without the hydrodynamically correct model should be the same near a surface.
Since internally, the effect of the surface is handled very differently through all the calibration options (hydro on/off, active on/off), this provides an integration test that actually tests whether all the parts are functioning correctly.
> force_calibration: add extra integration test hydro

- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
I added an example on how to select the background and how to subtract it from the line intensities after tracking.
> Add background subtraction to kymotracking example

- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
We need a way to find the surface position and focal shift. This PR implements that.
The API expects data to be in numpy array, and to be somewhat downsampled before entry (approx 150 Hz is fine). I was doubting whether to make this API call do that for the user or not. I opted for not, but it'd be easy to change. I also doubted whether to take `Slice` or numpy arrays.
There are no docs since it is private API for now.
I recommend reviewing commit by commit. Some commits have descriptions as to the what and why.
> Touchdown Method pt 1

- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
One of the requested output figures for kymotracked lines is a waterfall plot of binding histograms along the spatial axis for `n` time bins along the kymo. This PR adds an internal method on `KymoLineGroup` to calculate the data needed to make the plot (right side of the figure below).
Kernel density estimate is used to calculate a smoothed histogram, similar to what has been published in literature
> Add backend for making kymolines binding profile histogram

- changelog.md
- lumicks/pylake/__about__.py
Why this PR?
We have a lot of new features and a bunch of bugfixes that we'd like to get out before bumping to `0.12`.
What to look for
Please have a look whether all the changelog entries are clear and understandable.
Docs build here: https://lumicks-pylake.readthedocs.io/en/release_v0_11_1/install.html
Changelog here: https://lumicks-pylake.readthedocs.io/en/release_v0_11_1/changelog.html
> Prepare for release v0.11.1

- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
**Why?**
As you move away from the surface, the interference pattern decays over time. Including this decay provides a far better fit for longer touchdowns.
> touchdown: include exponential decay in touchdown

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_point_scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
Spring cleaning -- removed all properties deprecated <`v0.9.0`
> Remove old deprecated properties

- changelog.md
- lumicks/pylake/__about__.py
Time for a release
Docs build here: https://lumicks-pylake.readthedocs.io/en/release_0_12_0/install.html
Changelog here: https://lumicks-pylake.readthedocs.io/en/release_0_12_0/changelog.html
> Prepare for release v0.12.0

- lumicks/pylake/kymotracker/kymoline.py
Just something small I noticed.
> kymolinegroup: remove unused variable

- .github/workflows/pylake_test.yml
- changelog.md
- lumicks/pylake/__init__.py
- lumicks/pylake/benchmark.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_imaging_camera/conftest.py
By providing a benchmark of a vertical slice of Pylake functionalities, we can hopefully gauge how well a particular system performs at Pylake tasks.
> benchmarks

- changelog.md
- lumicks/pylake/piezo_tracking/baseline.py
- lumicks/pylake/piezo_tracking/piezo_tracking.py
- lumicks/pylake/piezo_tracking/tests/conftest.py
- lumicks/pylake/piezo_tracking/tests/test_baseline.py
- lumicks/pylake/piezo_tracking/tests/test_piezo_tracking.py
We wish to pull piezo tracking into Pylake. This PR attempts to pull in the basic functionality from the notebook to get up to feature parity.
The API is as follows (but deliberately not documented or public yet until we have the baseline model we wish to use in the end).
```python
from lumicks.pylake.piezo_tracking.piezo_tracking import *
from lumicks.pylake.piezo_tracking.baseline import *
baseline_data = lk.File(r'background_curve.h5')
distance_calibration = DistanceCalibration(baseline_data ["Trap position"]["1X"], baseline_data.distance1, degree=1)
```
Some functions are there to conveniently plot the results.
```python
plt.figure()
distance_calibration.plot()
plt.figure()
distance_calibration.plot_residual()
```
(Note that `degree = 1` which was used in the notebook …
> Piezo tracking

- lumicks/pylake/adjustments.py
- lumicks/pylake/tests/test_image.py
Please, approve my very first and (almost) single character pull request.
> adjustment: Typo

- changelog.md
- lumicks/pylake/__about__.py
> release: release pylake 0.12.1

- changelog.md
- lumicks/pylake/force_calibration/convenience.py
Does this count as a single character PR?
> force_calibration: change default driving frequency to 38 Hz

- docs/tutorial/force_calibration.rst
To make the force docs a bit more friendly towards a wider audience of users, some small amendments were suggested.
> docs: improve user friendliness force calib docs

- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
Currently, the calibration is based relative to microns; it makes more sense to set the calibration per pixel
> Change PositionCalibration to take per pixel calibration value

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
- lumicks/pylake/tests/test_utilities.py
For convenience, it's nice to not have to write this list comprehension every time.
> kymolinegroup: allow estimating diffusion at the group level

- changelog.md
- docs/api.rst
- docs/tutorial/figures/piezotracking/baseline.png
- docs/tutorial/figures/piezotracking/baseline_residual.png
- docs/tutorial/figures/piezotracking/comparison.png
- docs/tutorial/figures/piezotracking/mirror_calibration.png
- docs/tutorial/figures/piezotracking/mirror_calibration_residual.png
- docs/tutorial/figures/piezotracking/nonzero_force.png
- docs/tutorial/figures/piezotracking/piezotracking_result.png
- docs/tutorial/index.rst
- docs/tutorial/piezotracking.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/piezo_tracking/baseline.py
- lumicks/pylake/piezo_tracking/piezo_tracking.py
This PR makes the piezo tracking public and adds a small tutorial for the piezo tracking (a larger example based on the notebook we have on Harbor will likely still be added as well).
Docs build here: https://lumicks-pylake.readthedocs.io/en/piezo_docs/
> Piezo tracking documentation

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
As a user I want to be able to define steps when indexing frames of `CorrelatedStacks` (i.e. decimate the frames).
> Slicing steps

- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_corrstack.py
This PR enables the user to create a Kymo from a correlated stack.
> Create kymo from corrstack

- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
It's very minor, but we have some warnings in our own tests and they pollute the pytest results. This PR fixes them.
> msd: fix warnings in test

- changelog.md
- docs/api.rst
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cas9_kymotracking/kymowidget.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
This is the final PR to align the "line" vs "track" terminology, focused on the kymotracker widget
Docs build [here](https://lumicks-pylake.readthedocs.io/en/line_to_track_the_finale/examples/cas9_kymotracking/cas9_kymotracking.html)
> Line to track the finale

- changelog.md
- lumicks/pylake/__about__.py
> release: release Pylake 0.13.0

- changelog.md
- lumicks/pylake/__about__.py
hotfix for `TimeSeries` lazy loading bug
> Release pylake 0.13.1

- release.md
Update the release notes to improve experience when releasing a new Pylake release.
> release: Update release instructions

- docs/tutorial/file.rst
As a first step in updating the tutorials, I updated file.rst file in the docs:
A summary of the changes:
- Make sure that all the code runs at once
- Updated the text on some places, to make it more clear and concise. 
- I used the file 'WTCas9_tether=0011_replicate=0000_date=2021_12_03__13_28_26.h5', which is in the folder 'Pylake Docs Datasets' on Google drive.
> Docs] curate / update files and channels

- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
> kymotrack: ensure proper order on merge

- docs/tutorial/images.rst
I updated image.rst. Some of the changes are:
- Used the single-frame scan and multiframe scan from the Pylake data wishlist. I tuned all the parameters to fit these two data files.
- Make sure everything runs
- Restructured the text and change headings for a better structure
- When exporting video, I changed` end_frame` -> `stop_frame`
- `scan.red_photons` -> `scan.red_photon_count`
> Update docs confocal

- docs/install.rst
To really highlight the frequently asked questions from the installation instructions we've moved these hints from standard text to dedicated text boxes. You can see a preview of this here: https://lumicks-pylake.readthedocs.io/en/jupyter_env_docs/install.html#installation-using-anaconda
> docs: highlight troubleshooting section

- docs/api.rst
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
Often, when dealing with very short tracks the MSDs can be all over the place because of the lack of averaging. In such a case, ensemble MSDs can be useful. The difficult part of the ticket was that we wanted some quantification of uncertainty here as well. For this I implemented the SEM (standard error of the mean estimate that we plot). This seems pretty typically used.
This allows you to make plots like this:
To validate that the results we get from this are not nonsense, I have compared the standard errors obtained with this method against the covariance we're expecting from the GLS estimator (see below).
Shown are the theoretical SEM (from the GLS theoretical variance), the empirical SEM (from just naively repeating the simlation experiment and looking at the …
> msd: allow computing an ensemble MSD

- docs/tutorial/kymographs.rst
> docs: fix single character typo

- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
We want to provide some more insightful tooltips and for this we need some description fields.
> kymotracker widget: extended descriptions

- .github/workflows/pylake_docs_test.yml
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- .github/workflows/pylake_test_no_notebook.yml
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
There are newer version of our GH workflows available.
I also enabled pip caching.
Note that I also piggybacked a small fix for a warning we were getting in our tests.
> ci: update workflows

- docs/tutorial/fdcurves.rst
- docs/tutorial/figures/fdcurves/fdcurves_aligned.png
- docs/tutorial/figures/fdcurves/fdcurves_f_vs_time.png
- docs/tutorial/figures/fdcurves/fdcurves_scatter.png
- docs/tutorial/figures/fdcurves/fdcurves_scatter_f1x.png
- docs/tutorial/figures/fdcurves/fdcurves_scatter_manual.png
I added figures and updated the text for fdcurves.rst
The docs can be found here: https://lumicks-pylake.readthedocs.io/en/update_fdcurves2/tutorial/fdcurves.html
> docs: update fdcurves.rst

- docs/conf.py
- docs/tutorial/figures/population_dynamics/downsampling_problems.png
- docs/tutorial/figures/population_dynamics/dwell1_bootstrap.png
- docs/tutorial/figures/population_dynamics/dwell1_hist.png
- docs/tutorial/figures/population_dynamics/dwell2_bootstrap.png
- docs/tutorial/figures/population_dynamics/dwell2_hist.png
- docs/tutorial/figures/population_dynamics/gmm_hist.png
- docs/tutorial/figures/population_dynamics/gmm_labeled_trace.png
- docs/tutorial/figures/population_dynamics/hairpin_trace.png
- docs/tutorial/hairpin_kinetics.png
- docs/tutorial/kymo_bic_compare.png
- docs/tutorial/kymo_bind_bootstrap_2.png
- docs/tutorial/kymo_bind_dwell_1.png
- docs/tutorial/kymo_bind_dwell_2.png
- docs/tutorial/pop_downsampling_notes.png
- docs/tutorial/pop_gmm_hist.png
- docs/tutorial/pop_gmm_labeled_trace.png
- docs/tutorial/pop_hairpin_trace.png
- docs/tutorial/population_dynamics.rst
- lumicks/pylake/population/dwelltime.py
Now we have real data we can use 😄 See builds for [tutorial](https://lumicks-pylake.readthedocs.io/en/dynamics_docs/tutorial/population_dynamics.html) and [API](https://lumicks-pylake.readthedocs.io/en/dynamics_docs/api.html#population-dynamics)
> Update population dynamics docs

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/point_scan.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_point_scan.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_scan.py
> Remove deprecated methods/properties from image classes

- lumicks/pylake/kymotracker/detail/localization_models.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_loc_models.py
We want some private API to be able to flip a kymograph.
> kymotrackgroup: add `_flip` operation

- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
See discussion in #514.  Only a couple methods require single source. Added test for the happy path with OLS ensemble diffusion with multiple sources
> Remove `KymoTrackGroup._kymo`

- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Also make sure that we get proper display units for spatially aware parameter by quering the kymo instance.
> widgets: Add display_unit to KymotrackerParameter

- docs/tutorial/force_calibration.rst
Some fell through in the original PR (#551)
> docs: apply review suggestions to robust fitting tutorial

- changelog.md
- docs/tutorial/force_calibration.rst
- docs/tutorial/population_dynamics.rst
- docs/whatsnew/1.2.0/1_2_0.rst
- docs/whatsnew/1.2.0/group_plot_fit.png
- docs/whatsnew/1.2.0/robust_fitting.png
- lumicks/pylake/__about__.py
- Updated What's New section
- cleaned up changelog
- incremented version & release date
_will squash on merge_
[What's new build here](https://lumicks-pylake.readthedocs.io/en/release_v1_2_0/whatsnew/1.2.0/1_2_0.html)
> Release v1.2.0

- docs/refs.bib
- docs/theory/diffusion/diffusion.rst
- docs/theory/diffusion/figures/1D_diffusion.png
- docs/theory/diffusion/figures/MSD_analysis.png
- docs/theory/diffusion/figures/MSD_full.png
- docs/theory/diffusion/figures/diffusive_tracks.PNG
- docs/theory/diffusion/figures/refinement.png
- docs/theory/diffusion/figures/target_search.png
- docs/theory/diffusion/index.rst
- docs/theory/diffusion/intro.rst
This introductions to diffusion analysis summarizes the recommended methods for diffusion analysis in Pylake and informs the user on important steps in diffusion analysis. It is a kind of guide to the Pylake tutorial for a C-Trap user that is not so experienced with diffusion analysis and equations.
Please, check whether the content is accurate, and whether you think a biology user can follow everything.
Also, let me know if an important step in diffusion analysis is missing.
Doc can be viewed here: https://lumicks-pylake.readthedocs.io/en/docs_diffusion_intro/theory/diffusion/intro.html
> Docs diffusion intro

- docs/install.rst
I got the feedback that the installation instructions are super easy, but the update instructions are not so clear, so I made the steps more explicit
> Update update instructions install.rst

- changelog.md
- docs/whatsnew/1.2.0/1_2_0.rst
- lumicks/pylake/__about__.py
> Prerelease v1.2.1

- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_point_scan.py
> Migrate test point scan

- lumicks/pylake/file_download.py
- lumicks/pylake/tests/test_file_download.py
Zenodo reverted their API changes.
Once this one is merged I'll open a PR to merge all the bug-fixes back into `main` to ready us for a release.
> zenodo: fix `download_from_doi`

- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/file_download.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_file_download.py
We want to release `1.3` soon, so it's time to merge the bug fixes we have done up to now back into main.
> release prep: merge `1.2` back into `main`

- changelog.md
- docs/tutorial/kymotracking.rst
- docs/whatsnew/1.3.0/1_3_0.rst
- lumicks/pylake/__about__.py
> release: release pylake v1.3.0

- changelog.md
- docs/tutorial/kymotracking.rst
- docs/whatsnew/1.3.0/1_3_0.rst
- lumicks/pylake/__about__.py
- lumicks/pylake/detail/imaging_mixins.py
Merge the bug fix for the movie exporter back into `main`.
> release_proc: merge bugfix back into main

- changelog.md
- docs/_ext/nbexport.py
- docs/requirements.txt
- lumicks/pylake/nb_widgets/correlated_plot.py
> merge `1.3` back to `main`

- .gitattributes
- changelog.md
- docs/theory/force_calibration/force_calibration.rst
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_imaging_camera/data/tiff_from_scan_v1_3_1.tiff
- lumicks/pylake/tests/test_imaging_camera/reference_data/legacy_exposure_handling/dead_time[False].npz
- lumicks/pylake/tests/test_imaging_camera/reference_data/legacy_exposure_handling/dead_time[True].npz
- lumicks/pylake/tests/test_imaging_camera/test_image_reconstruction.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_imagestack.py
- lumicks/pylake/tests/test_imaging_mixins.py
- lumicks/pylake/tests/test_scalebar.py
- readme.md
- setup.manifest
> merge `release` branch into `main`

- changelog.md
- lumicks/pylake/__about__.py
**Why?**
Release pylake 1.4.0 🎉 
Note: once https://github.com/lumicks/pylake/pull/625 is merged, I will retarget this one to the new release branch.
> release: release pylake v1.4.0

- lumicks/pylake/file.py
just something I noticed and was a quick fix
> Replace hardcoded names in `File.__str__`

- changelog.md
- docs/tutorial/force_calibration.rst
- lumicks/pylake/__about__.py
- lumicks/pylake/file.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
**Why?**
Merge some of the fixes back into `main`. In particular, the one that closes image stacks explicitly fixes some occassional CI failures.
> merge `1.4` back into `main`

- docs/install.rst
I rephrased the installation instructions for China, keeping in mind that most users going to this section will not have Python experience.
> Update installation instructions China

- changelog.md
- docs/theory/force_calibration/fitting.rst
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
I want to add some diagnostic criteria to force calibration for which I need this bugfix on main.
> merge bugfix back into `main`

- changelog.md
- lumicks/pylake/__about__.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Merge back to `main` after release.
> merge release/1.5 to main

- changelog.md
- lumicks/pylake/__about__.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
We need this bugfix backported to an older release.
> release: release Pylake v1.4.1

- changelog.md
- docs/install.rst
- lumicks/pylake/__about__.py
Would be nice to do a bugfix release so that people on the latest `mpl` release can use our widgets again.
> release: Release Pylake v1.5.2

- changelog.md
- docs/install.rst
- lumicks/pylake/__about__.py
- lumicks/pylake/channel.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
Should merge the bug fixes we released back into `main`.
> merge `release/1.5` back into `main`

- changelog.md
- lumicks/pylake/adjustments.py
- lumicks/pylake/tests/test_image.py
Unnecessary warnings just worry people.
> adjustment: prevent division by zero

- docs/examples/hairpin_fitting/baseline_vs_time.png
- docs/examples/hairpin_fitting/baselinefit.png
- docs/examples/hairpin_fitting/baselines.png
- docs/examples/hairpin_fitting/calibration.png
- docs/examples/hairpin_fitting/distance.png
- docs/examples/hairpin_fitting/fdcurve.png
- docs/examples/hairpin_fitting/fit_all.png
- docs/examples/hairpin_fitting/fit_handles.png
- docs/examples/hairpin_fitting/hairpin_unfolding.rst
- docs/examples/hairpin_fitting/piezodistance.png
- docs/examples/hairpin_fitting/residuals.png
- docs/examples/hairpin_fitting/selected_data.png
- docs/examples/index.rst
- docs/tutorial/fdfitting.rst
- docs/tutorial/piezotracking.rst
Notebook that combines the piezo distance and fd fitting. A very common workflow for the protein unfolding community. 
Docs are compiled here:
https://lumicks-pylake.readthedocs.io/en/example_hairpin_unfolding/examples/hairpin_fitting/hairpin_unfolding.html
> examples: add hairpin unfolding fitting

- lumicks/pylake/tests/test_scalebar.py
This fixes this particular test failing after the first time it is run. I changed the input to a tuple, since it also discourages a similar thing from happening again in the future.
> ci: don't modify test parametrization during test

- .gitignore
- changelog.md
- lumicks/pylake/__about__.py
- lumicks/pylake/channel.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_file/test_file_items.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
These two fixes allow certain kymographs and scan objects to be opened.
> release: backport fixes and release pylake `1.4.2`

- docs/examples/binding_lifetime/binding_lifetime.rst
- docs/examples/binding_lifetime/kymo1.png
- docs/examples/binding_lifetime/kymo2.png
- docs/examples/binding_lifetime/tracks1.png
I added a plot of the tracks, to make more clear what we are actually analyzing in the rest of the example.
> examples: plot tracks in binding lifetime example

- .github/workflows/pylake_docs_test.yml
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- .github/workflows/pylake_test_no_notebook.yml
We forgot to update the CI actions [when we switched](https://github.com/lumicks/pylake/pull/675) over to using a `pyproject.toml`.
> ci: fix deploy action

- changelog.md
- lumicks/pylake/__about__.py
> release: release pylake v1.6.1

- changelog.md
- lumicks/pylake/__about__.py
This patch release contains a pretty critical bugfix that would be nice to release.
> release: release Pylake v1.6.2

- lumicks/pylake/population/tests/test_dwelltimes.py
This test depended on implementational details in the optimizer, which is undesirable, since that isn't what we wish to test, we simply want to know whether our parameters made it there.
No changelog entry since it doesn't affect users.
> ci: fix brittle test
