lumicks/pylake

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_channels.py
This only includes downsampling by a factor for continuous channels:
```python
lf_force = hf_force.downsampled_by(20)
```
Downsampling to a specific frequency is not implemented because the interface would be very misleading:
```python
assert hf.sample_rate == 78125
lf = hf.downsampled_to(77000)
assert lf.sample_rate == 77000  # FAILS!
assert lf.sample_rate == 39062  # what actually happens -> the factor must be an integer
```
> Support for downsampling continuous channel slices

- lumicks/pylake/fdcurve.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_dfcurve.py
- readme.md
- setup.py
Usage is very simple:
```python
fd_baseline = h5file.fdcurves["Baseline"]
fd_measured = h5file.fdcurves["Measurement"]
fd = fd_measured - fd_baseline
fd.plot_scatter()
```
The implementation is also reasonably simple, based on `scipy.interpolate.interp1d()`.
> Baseline subtraction for FD curves

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/file.py
- lumicks/pylake/group.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_channels.py
- lumicks/pylake/tests/test_dfcurve.py
- lumicks/pylake/tests/test_file.py
This is the _pylake_ companion to the Bluelake implementation of photon time tagging (NG-1392 and friends).
* Channel source classes in `pylake.channel` have been refactored to make room for a new `TimeTags` source.
* Explicit checking of different file format versions is now in place in `pylake.File`. Right now, an exception is thrown upon encountering an unknown file format. 
**Open question**: Is that the right behavior? Would it be better to issue a warning instead, and risk messing up the data if the file format has undergone major changes? Or play it safe, and force people to upgrade their _pylake_ if needed?
* Adds unit tests for the new channel types and file format versions, including some infrastructure for testing different file format versions.
> Add support for time tag channels

- lumicks/pylake/channel.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_image.py
Should mostly resolve NG-1472.
Benchmarked with a 2 GiB HDF5 file containing a continuous scan with 212 frames:
```
|            | before (ms) | after (ms) | speedup |
|------------|-------------|------------|---------|
| load       |   1353.3    |     1.1    |    ∞    |
| rgb image  |   3906.6    |   863.9    |   4.5x  |
| num_frames |   0.003     |    19.7    |    ∞    |
|------------|-------------|------------|---------|
|  total     |   5259.9    |   884.7    |  5.95x  |
```
* `load` is just listing the scan using `file.scans`. This was previously very slow for continuous scans because the the number of frames needed to be calculated and this was being done in the constructor. This is now done lazily, but the calculation is also faster. See below.
* `rgb image` indicates the time …
> Improve performance of confocal image reconstruction

- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_image.py
- Adds dwell time / pixel time as metadata to exported TIFF file.
- Adds resolution to exported TIFF file (resolution is verified to be correctly recognized in ImageJ).
- Add tests for resolution and pixel time export.
> Ng 987 - Export pixel size and dwell time to TIFF

- lumicks/pylake/file.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
- Fixes a regression in Scan which prevented the constructor from being called correctly upon file loading. Reason for the bug was inheritance on Kymo and no testing for Scan itself.
- Reverts the field name metadata back to json for backward compatibility.
- It also adds tests to prevent this from happening in the future.
- Removes convenience plot limit flags.
- Fixes test failures due to file open mode not being indicated in tests (deprecated in the h5py used on travis).
> NG-1936: Bugfix for scan constructor failing due to changes in base class Kymo.

- lumicks/pylake/group.py
- lumicks/pylake/tests/test_file.py
- Adds more informative __repr__ for groups (shows the members and makes navigation of the h5 tree easier).
- Adds keys() for Group.
- Adds iterator for Group.
- Adds tests for above functionality (full coverage).
Note that the tests are failing because of an actual error in the tests that was fixed in #17 . Rebasing after that PR is accepted should fix this.
> Ng 1929 - As a user, I would like to be able to see the keys in a group when printing either the group, or requesting its keys via keys()

- lumicks/pylake/detail/utilities.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_utilities.py
This fixes a bug where image reconstruction fails when the image axes in the json are switched.
> Ng 1812 - Images reconstructed in pylake can have the axes inverted

- lumicks/pylake/channel.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/file.py
- lumicks/pylake/group.py
- lumicks/pylake/marker.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
In ```group.__getitem__```, we check what type of data we are actually trying to index. Modern bluelake files have a "kind" field for channel data, but there's a fallback for older versions which don't have this field, which returns Continuous.
Not all datasets are channel data however, and when it gets called on one of these, the construction of Continuous fails providing an error that to the user has little or nothing to do with what they were trying to do. Instead, we now throw an exception when the user accesses something pylake isn't built to understand.
In this PR:
- Provides API for markers.
- Allows printing property fields available in the h5 in human readable format.
- When data access is attempted through the fields directly (such as h5file["Calibration"]) the user is …
> Deal with unrecognized fields

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/__about__.py
- lumicks/pylake/correlated_stack.py
- setup.py
This PR aims to get pylake ready for release v0.4.1
- Removes matplotlib < 3 requirement. Despite conda-forge's recommendation to go with matplotlib-base, it seems more sensible to stick with matplotlib > 2.2, since matplotlib-base only starts at 3.0 and > 3.0 may be a harder constraint than base (leading to more difficult environment solving).
- Modifies the documentation to be in accordance with the current output of print.
- Updates the changelog.
- Implements a plotting bugfix on CorrelatedStack.
> Preparation for release v.0.4.1 

- changelog.md
- lumicks/pylake/detail/image.py
Three try catches :(.
I could try to put this in a function, but then we wouldn't be able to use try/catch, since passing the reference into the function would bump the reference count by one. There isn't an equivalent of move semantics, is there? :)
We could consider switching to concatenate altogether (since it doesn't seem to have a huge performance impact), but I'm not sure how much memory it takes compared to an in-place resize.
Time measurement (performed in randomized sequential order):
In place: 1.5232401490211487 +- 0.050069897091749985 (N=20)
Concatenate: 1.6158243656158446 +- 0.0414880556443715 (N=20)
np.resize: 2.3809279084205626 +- 0.06063061274418485 (N=20)
> reconstruct_image: make a copy when in-place resize fails

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_correlated_stack.py
Timestamps returned from downsampled_over weren't defined as int64. This PR fixes that.
> Return int64 for time from channel.downsampled_over

- changelog.md
- docs/conf.py
- docs/index.rst
- docs/refs.bib
- docs/requirements.txt
- docs/zrefs.rst
- lumicks/pylake/fitting/fit.py
This PR adds a literature/references page to rtd.
It adds bibtex as a dependency for building the docs (tested on rtd).
Note that the page is called `zref` since it has to be the last page parsed (requirement from sphinxcontrib-bibtex).
I piggybacked a fixup in the docs for `Fit.plot()` since its a small fix and also affects docs.
> Add literature page

- .travis.yml
- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/fitting/detail/utilities.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_fdfit.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
Related to issues [LAKE-94](https://lumicks.atlassian.net/browse/LAKE-94) and [NG-2706](https://lumicks.atlassian.net/browse/NG-2706). We got a file through support that had a kymograph for which the corresponding photon channel data was not available all the way up to the start (i.e.. `photon_count._src.start > kymo.start`). In this case reconstruction would quietly fail and produce wrong images and timestamps.
This PR fixes that. 
For kymographs it reconstructs by omitting the first line (and giving a warning about the issue). For scans it raises an exception, as there's not enough information to reliably reconstruct a multi-image scan.
It also implements a more efficient way of doing the reconstruction for photon counts that doesn't rely on fixed pixel size. Originally, I was also …
> Hotfix damaged kymographs.

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
Fixes issue in [LAKE-95](https://lumicks.atlassian.net/browse/LAKE-95) pertaining to the reconstruction of scans.
The reconstruction of images with a fast axis in y-direction failed due to changes made in https://github.com/lumicks/pylake/pull/19 . The axis flip should have been implemented post-reconstruction as data is acquired in the order specified in the json (fast axis being the first axis in the list).
This PR fixes the issue as well as hardens some of the scan tests (by including multi-frame scans as this almost caused a regression while doing the fix).
> scan: fix reconstruction bug when fast axis in y direction

- changelog.md
- docs/api.rst
- lumicks/pylake/fitting/detail/model_implementation.py
- lumicks/pylake/fitting/models.py
- lumicks/pylake/tests/test_fdfit.py
For protein studies (and the notebook we want to release), the simple (non-extensible) version of the Marko Siggia model is often used to model the protein state. It's basically the Marko Siggia model without the stretch modulus (which is equivalent to a stretch modulus of infinity).
We already have both forms of the full Marko Siggia model in the FdFitter. By both forms, I mean one version of the model with force as independent parameter, and one version of the model with distance as independent parameter. While it's technically possible to just set the stretch modulus to a very large value, this can lead to numerical problems during optimization and is just a generally icky thing to do.
We also already have the simplified Marko Siggia model in the FdFitter.
However, when working with …
> fdfit: Added simplified Marko Siggia model for protein studies

- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/detail/scoring_functions.py
- lumicks/pylake/kymotracker/detail/trace_line_2d.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
- lumicks/pylake/kymotracker/tests/test_tracing.py
This is algorithm 2 for the kymotracker. This one seems to fare a bit better when the kymos are relatively high SNR, but doesn't rely on the assumption that the kymos are inherently lines. As such it seems to require less prefiltering.
The peakfinding is based on section 2.2 from: https://publications.mpi-cbg.de/Sbalzarini_2005_4820.pdf
While the actual particle tracing is a greedy algorithm, that is a bit more akin to: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4907728/pdf/1948.pdf
Except for the fact that for now, velocity in our model is not time-dependent, but a user specified value. Our model for accepting or rejecting the steps, is also slightly different, in the sense that we also try to incorporate diffusion (when relevant).
Next up will be the refinement PR which will build on …
> Kymotracker Algorithm 2

- changelog.md
- lumicks/pylake/group.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
To avoid breaking people's code, this PR changes an `IndexError` exception that we raised upon accessing a field covered by the API by a `FutureWarning`.
> change deprecated field access result from exception to warning

- docs/examples/cst/kinesin_open_loop.rst
Tiny PR which removes deprecated use of the raw calibration groups from the docs and replaces it with the recommended method.
> docs: remove old calibration syntax from cst example

- changelog.md
- lumicks/pylake/nb_widgets/fd_selector.py
This solves an annoying bug that can occur when a different figure got focus in a Jupyter notebook in the meantime.
Before:
After:
> widgets: make unfocused fdwidget plot to correct axes

- changelog.md
- lumicks/pylake/kymo.py
This PR flips the displayed coordinates to correctly reflect position in `Kymo.plot_red()`, `Kymo.plot_green()`, `Kymo.plot_blue()` and `Kymo.plot_rgb()`.
While the origin of the image data has always been at the top left, previously the coordinate y=0 was displayed at the bottom left, incorrectly indicating that the origin was on the bottom left.
> kymo: fix coordinates displayed on axis

- .github/CODEOWNERS
When any `.py` file is modified in a PR, 2 people from the @lumicks/python_review team will be assigned to review it. Only one person actually needs to review. Two are selected so as not to put too much pressure on one person if they are busy. @lumicks/python_review Please coordinate with the other person that you're assigned with so that we don't end up with no reviews.
> github: Add codeowners file to auto-assign reviewers

- changelog.md
- docs/tutorial/file.rst
- docs/tutorial/nbwidgets.rst
- lumicks/pylake/detail/h5_helper.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file.py
One issue with uploading data to Harbor is that data files are often quite big. Very often, one doesn't need the high frequency channels for a particular dataset, or one might want to compress using a higher compression ratio. For this, `export_h5` was added to the `File` interface.
See also: https://lumicks-pylake.readthedocs.io/en/export_h5/tutorial/file.html
> Allow exporting h5

- changelog.md
- docs/install.rst
- docs/tutorial/images.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_scan.py
This PR adds a feature to `scan` that's been requested a few times, namely the ability to export multi-frame scans to movie formats such as `.avi`, .`mp4` and `.gif`.
I decided to use the `matplotlib` animation module for this, since it allows us to easily export the axes with and doesn't require any fiddling with ffmpeg or other converters ourselves.
One thing to note is that I update the `imshow` data rather than replot it entirely every time. This is a lot faster than the alternative.
By default it uses `Pillow` (which already ships with `mpl`), and will allow you to generate GIFs. If `ffmpeg` is installed it will use that instead since it supports far more formats. I added some conda instructions to the installation instructions for installing `ffmpeg`. While that binary is GPL-3.0, …
> scan: allow exporting plots to video formats

- changelog.md
- docs/api.rst
- docs/tutorial/nbwidgets.rst
- docs/tutorial/slice_widget.png
- docs/tutorial/slice_widget2.png
- lumicks/pylake/channel.py
- lumicks/pylake/nb_widgets/fd_selector.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
This PR generalizes the interactive range slicer to be used on channel data in addition to on F,d curves.
Why this PR:
- Makes it easier to extract chunks of channel data that one is interested in for further analysis.
- Extending this feature from just F,d to channels in general was requested.
- Makes sure that the widget gets a copy of the timestamp ranges involved rather than a reference (so that if the user messes with the ranges, the widget doesn't actually break)
Docs here: https://lumicks-pylake.readthedocs.io/en/slice_selector/tutorial/nbwidgets.html
> channel: add range slicer

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_correlated_stack.py
- There is a critical bug in `CorrelatedStack.plot_correlated` that happens when a `TiffStack` is sliced and then plotted correlated to `Channel` data. In this case, the start index is added twice since `get_frame` already takes into account the start index.
**What this PR adds**
- A fix for the bug and a regression test so that this does not happen again.
> CorrelatedStack: bugfix in plot_correlated to prevent misalignment

- readme.md
Because we'd like the badge to not point to Travis when we're actually using GitHub actions.
> ci: add test badge

- lumicks/pylake/tests/conftest.py
Builds are occassionally failing on GitHub actions because of Tk dependencies (see error below).
`_tkinter.TclError: Can't find a usable tk.tcl in the following directories`
This is not something we want to explicitly test. In this PR we switch to a headless `Agg` backend.
> ci: switch to headless backend for mpl tests

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_channels.py
- lumicks/pylake/tests/test_correlated_stack.py
This PR fixes two issues:
- `downsampled_over` used to be inconsistent with `downsampled_by`. The two did not produce the same timestamps when downsampling over integer frequency ratios. When downsampling the new timestamp should not have been `(subset.start + subset.stop)/2` but `(subset.timestamps[0] + subset.timestamps[-1])/2`
- The second one came  up during WIT testing, which is that when the h5 is smaller than the tiff exported, you can't use `correlatedstack` at all anymore. This PR fixes that by omitting those points in the downsampled series and raises a warning when this is the case.
- Tests were added to prevent the same inconsistency from popping up again.
> Downsampled over fix

- changelog.md
- lumicks/pylake/file.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
This PR fixes a bug where if a file contains a scan that is missing metadata, none of the scans could be loaded. Now a warning is generated and the scan that is missing metadata is ignored while all other scans are accessible.
_**Update Nov 2**_
This PR is now based on #68
> Missing meta

- .github/workflows/pylake_test.yml
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_import_time.py
This PR adds a test which measures how much time it takes to import Pylake.
As we are pulling in more and more dependencies, we might want to keep an eye on import times.
**Why this implementation?**
- Option A. Downside: Measures time taken to spin up python itself.
```python
def import_pylake():
subprocess.run(['python', '-c', 'import lumicks.pylake'])
times = timeit.repeat(import_pylake, number=1, repeat=3)
print(f"Pylake import time: {np.mean(times)} +- {np.std(times)}")
```
- Option B. Downside: Little control over output string. Reparsing the output of timeit would have been messy since it specifies time with prefixes to the units.
```
subprocess.run(['python', '-m', 'timeit', '--number=1', '--repeat=1', 'import lumicks.pylake'])
```
- Option C. This is more or less …
> ci import time tests

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
**What is this PR?**
Due to an issue with the implementation of the sted delay, the starting timestamp of a scan is not necessarily quantized to a multiple of the samplerate. This leads to an exception in the function which checks whether the start of the scan was truncated. In this PR, we allow for a small discrepancy here (within a time step) to accomodate for the quantization mishap (since the channel data can start a fraction of a sample after the scan start time).
Since systems shipped that have this delay mechanism, we need to handle it gracefully in Pylake for both scans and kymos.
> scan/kymo: workaround for non-quantized start timestamp

- changelog.md
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
This PR fixes a bug in `kymo._plot()` to ensure plotted time limits exclude fly-in/out times. Previously time limits were calculated from `kymo.start` and `kymo.stop` which can lead to subtle time discrepancies when comparing with force channels. Here the time limits are adjusted to the center timestamp of the first and last scan lines.
> Kymo plot time limits

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
It was requested to have a function which downsamples exactly like Bluelake does.
**How does it work?**
Bluelake averages backward in time from the end (i.e. `[t-dt : t]`) using the frame time. We can reconstruct this frame time from the consecutive time stamps.
When the framerate changes, it takes some time for new images to arrive. The code shouldn't average that entire time and instead just use the new framerate based on the timesteps that follow.
**Why not via downsampled_over?**
The difference in how the change in framerate is handled warranted a separate function.
Test with actual bluelake data with varying framerate (first samples cannot be reconstructed since there is no HF data there):
The residual when they overlap:
> channel: add function to downsample like bluelake

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
Quite often, you want to plot two slices of something together. It can be inconvenient to use a different starting point for the time axes. For example, when comparing downsampled data to the normal data, it can be pretty annoying that there is an apparent time shift when the initial sample is different. Or when you want to plot two slices together, you might want to be able to align them quickly and conveniently.
**How does this PR make things better?**
This PR exposes `start` and `stop` on `Slice` and allows you to `.plot()` with a custom starting timestamp.
```python
first_slice = file.force1x['5s':'10s']
second_slice = file.force1x['15s':'20s']
first_slice.plot()
second_slice.plot(start=first_slice.start)  # we want to use the start of first_slice as time point "zero" …
```
> Allow plotting with respect to a different timestamp

- lumicks/pylake/channel.py
`Downsampled_like` did not appropriately forward labels and calibrations. This PR fixes this.
> channel: forward properties in downsampled_like

- .github/workflows/pylake_test.yml
- changelog.md
- setup.py
To support Python 3.9 we need wheels for `h5py`. We need to start using the new `h5py` to still get wheels.
> ci: support python 3.9

- changelog.md
- docs/install.rst
- lumicks/pylake/nb_widgets/fd_selector.py
- setup.py
This PR hopes to make it simpler for our users to get the interactive widgets to work.
**How?**
`Pylake` checked explicitly whether the backend is `ipympl` and threw an exception if it wasn't. In Jupyter notebook, the backend `nbagg` is installed by default and would also be suitable for displaying our interactive plots.
The second change introduced in this PR is that `ipywidgets` is added as an explicit dependency. Some of our users may not know how to install it, and it'd be nice to just have it dealt with.
I also added a few FAQ issues to the docs that come up frequently.
**Docs:**
https://lumicks-pylake.readthedocs.io/en/simplify_widgets/install.html#faq
> Don't force users to install ipympl + faq

- changelog.md
- docs/api.rst
- docs/tutorial/kymo_refine.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
When performing Kymotracking using the greedy algorithm, one strings together a sequence of points that fall above a certain threshold into a trace. This means gaps can occur in the trace. This PR adds a method which interpolates the traces, and then tweaks those points based on the local brightness (using the brightness weighted centroid).
Before:
After:
**Why part 1?**
Ideally this method is followed up by a more extensive fitting procedure that will take into account the Poissonian nature of the measurement.
Docs: https://lumicks-pylake.readthedocs.io/en/kymo_refinement_pt1/tutorial/kymotracking.html
I added a paragraph on the refinement (look for refine_lines_centroid).
> kymotracker: add refinement pt. 1

- changelog.md
- lumicks/pylake/channel.py
When downsampling variable TimeSeries the command suggests to use `Force=True` rather than `method=”force”` which was a previous API in the PR that was never released. This exception should correctly reflect what a user actually has to do.
> channel: fix exception message downsampled_to

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
- lumicks/pylake/tests/test_kymo.py
This PR adds functionality for automatically downsampling a force channel over the time ranges of the kymograph scan lines and plotting the image and downsampled force.
* added `Kymo.plot_with_force()`
* added `Kymo._downsample_channel()` to automatically calculate scanline time ranges and return appropriately downsampled channel
> Kymo plot with downsampled force

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
Currently, the plotting functions for `Kymo` incorrectly set the time extent of the image, leading to a subtle bug (see image below)
**How does this PR make things better?**
By adjusting the time extent (essentially adding an extra line time) the line time points now correspond with the center of the pixel. 
Shown below is a simple dataset of 12 pixels with a timestep of 1
> kymo: fix plot time extent

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/tests/test_kymotracker.py
Being able to write kymograph traces to csv was requested by multiple customers. We already have this functionality on Harbor, but it would be nice to add a nicer API for it. This PR is also preparation for the kymotracker notebook widget PR which relies on this functionality being present.
Note that only the `save` functionality is exposed. The `load` functionality is also implemented (and tested), and needed for the widget.
Originally, this was going to be a PR with the widget as well, but I decided to split it up seeing how this refactor of how KymoLines are handled made it a bit bigger than intended already.
**Why KymoLines?**
I debated between just having save to csv a free function, but ended up choosing to write a small API to collect multiple `KymoLine` instances. …
> kymotracker: save tracked kymos to file

- lumicks/pylake/fitting/fit.py
- lumicks/pylake/tests/test_fdfit.py
Currently, when you specify a model without a Jacobian in the `FdFit` package, you get an error after fitting when it attempts to compute standard errors. This PR checks whether they are specified and if not, we don't compute them.
It also adds an explicit `NotImplementedError` when the user _does_ try to get the covariance matrix when there's no Jacobian for the model. Eventually we may want to add finite differencing, but that needs a bit more investigation.
> fdfit: skip std errors in absence of jacobian

- lumicks/pylake/nb_widgets/detail/mouse.py
- lumicks/pylake/nb_widgets/tests/conftest.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
- lumicks/pylake/nb_widgets/tests/test_mouse.py
It is required for the kymotracker widget to work.
**What is it?**
It's a small handler to deal with mouse drag events on a plot where the axis limits respond to dragging.
I have also factored out the mocked mouse event to be able to reuse it in different tests.
> nbwidgets: mouse drag

- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_image.py
Currently, there is a lot of duplicated code in `reconstruct_image()` and `reconstruct_image_sum()`. Additionally these functions have an optional `lines_per_frame` kwarg to handle reconstructing 2D images, which leads to different call signatures from `Scan` and `Kymo`
**How does this PR make things better?**
- duplicated code in `reconstruct_image()` and `reconstruct_image_sum()` is pulled out into separate helper functions
- a private `_shape` property is added to `Scan` and `Kymo` which can be used directly in the image reconstruction functions rather than the current `pixels_per_line` and optional `lines_per_frame` arguments
- this allows for a homogenous call to the reconstruction functions; therefore `_image()` and `_timestamps()` are moved to `ConfocalImage` mixin …
> Refactor image reconstruction

- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- setup.py
Currently, caching for expensive calculations is handled manually (and not implemented for timestamps). Would be better to let a dedicated caching package handle this.
**How does this PR make things better?**
- caching is handled through `cachetools` method decorator 
- caching is implemented for `timestamps` along with `{color}_image`
- all calculations are handled through a single method `_from_infowave` (and `_timestamps` and `_image` have been removed)
> Better caching

- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
User request for histograms plotted alongside a kymo (for example, to visualize binding events)
- can histogram along either time or position axes
- user inputs the number of pixels to bin together
Example:
> Kymo plot with histogram

- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file.py
to make clear that the `downsampled_force##` attributes exist in the file
> Include downsampled_force## when printing File

- changelog.md
- setup.py
We don't want to ship Qt with Pylake as this can lead to issues with Bluelake.
Note that there is no headless opencv available for anaconda; but this shouldn't be an issue since we use pip for BL.
> deps: switch to headless opencv

- changelog.md
- lumicks/pylake/__about__.py
- lumicks/pylake/__init__.py
- Want to release v0.7.2.
- Put a date in the changelog.
- Hide the kymotracker widget from the public API as there is no documentation for it yet and there is still an outstanding issue with Jupyter notebook (see other PR).
> release: readying for release v0.7.2

- lumicks/pylake/nb_widgets/kymotracker_widgets.py
In Jupyter notebook, there's an issue with the notebook backend which prevents the widget from correctly opening.
**Why this fix?**
The reason for this is that an output cell has to be displayed, before it can be used as a context manager. Therefore, the construction of the figure has to be deferred until the widget is displayed.
This workaround has been tested on the latest `Jupyter notebook` and `Jupyter Lab` w/`ipympl`.
> nbwidgets: fix kymotracker widget not opening in notebook

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
*Why this PR?*
Sometimes, `TimeSeries` data can contain a large gap. When you `downsample_over` a gap you get an exception (since some of the slices are empty). This can happen for example when you have data where the distance lock is turned off and then on.
This PR fixes that by ignoring samples where there is no data. Note that since we don't guarantee that a `Slice` of `TimeSeries` is contiguous, it should be evident that the returned `Slice` doesn't have to be either.
> channel: fix exception downsampled_over over gap

- changelog.md
- docs/examples/cas9_kymotracking/binding_vs_force.png
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cas9_kymotracking/kymo_force.png
- docs/examples/cas9_kymotracking/kymo_position_over_time.png
- docs/examples/cas9_kymotracking/kymowidget.png
- docs/examples/cas9_kymotracking/line_duration_vs_force.png
- docs/examples/cas9_kymotracking/photon_counts_longest.png
- docs/examples/index.rst
- docs/tutorial/kymotracking.rst
- lumicks/pylake/__init__.py
*Why this PR?*
Users would probably like to have documentation for the kymotracker widget.
*What does this PR add to mitigate this?*
It adds documentation for the kymotracker widget and a worked example to show a typical analysis done with the widget.
Docs here: https://lumicks-pylake.readthedocs.io/en/kymowidget_docs/examples/cas9_kymotracking/cas9_kymotracking.html
And here: https://lumicks-pylake.readthedocs.io/en/kymowidget_docs/tutorial/kymotracking.html#using-the-kymotracker-widget
> kymotracker: add docs and make widget public

- changelog.md
- docs/tutorial/fd_dist_widget.png
- docs/tutorial/fd_dist_widget2.png
- docs/tutorial/fd_dist_widget3.png
- docs/tutorial/fd_dist_widget3a.png
- docs/tutorial/nbwidgets.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/channel.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/nb_widgets/range_selector.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
- lumicks/pylake/tests/test_dfcurve.py
- lumicks/pylake/tests/test_utilities.py
User request for a notebook widget to select a range based on distance rather than time
**Key Points & Notes**
- `fd_selector.py` was renamed to `range_selector.py` (internal module)
- selector widgets code was refactored to make more general, easier to add new widgets
- some internal widget classes renamed to be more consistent
- noise in distance measurement can lead to premature truncation of the time channel if the longest contiguous block of data is selected from a pure logical mask (see figure, left and middle columns). An optional argument allows for small gaps caused by noise in the data (figure, right column)
the desired distance threshold is displayed as the dashed black line in relevant plots
See the docs …
> FDCurve - distance range selector widget

- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_correlated_stack.py
- lumicks/pylake/tests/test_fdfit.py
- lumicks/pylake/tests/test_file.py
- setup.cfg
Some functionalities were deprecated in numpy. We'd like to stay up to date.
**Why the addition to setup.cfg?**
h5py is still using some deprecated behaviour. They already have a fix for this (see: https://github.com/h5py/h5py/pull/1780/files ) but until that's out there, it would be nice to silence this one error.
> Fixes for deprecated functionalities in numpy

- changelog.md
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
Let users know what type of metadata is available for scans and kymos
* added `center_point_um` and `scan_width_um` properties
* added documentation for all public properties in `Scan` and `Kymo` classes. This should hopefully avoid many users from directly accessing the `.json` metadata
* cleaned up documenation for Confocal Images and Kymographs
Updated docs for [Scan](https://lumicks-pylake.readthedocs.io/en/scan_props/tutorial/images.html) and [Kymo](https://lumicks-pylake.readthedocs.io/en/scan_props/tutorial/kymographs.html)
> Document access to scan metadata

- lumicks/pylake/tests/test_file.py
numpy < v1.20 raises FutureWarning with `np.issubdtype(np.int, int)`
change offending line according to warning suggestion
> Handle Numpy FutureWarning

- changelog.md
- docs/tutorial/fdcurves.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/detail/alignment.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/fdensemble.py
- lumicks/pylake/tests/test_dfcurve.py
- lumicks/pylake/tests/test_fdensemble.py
While we do provide a workflow for dealing with offsets by means of fitting in the F,d curves, some labs prefer doing analyses on ensembles of F,d curves. One thing they often do is align the curves prior to analysis, after which they classify different parts of the curves (many curves at the same time). This PR is the first towards enabling that type of workflow.
It introduces the `FdEnsemble` which is essentially a collection of processed F,d curves. It also includes the most basic alignment method, which is based on two regressions (one constant, one linear) at the start and end of each curve.
It works quite well for data generated by some of our collaborators. For some of our own data, the conditions that the measurements were taken in are often …
> Fd ensemble

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_correlated_stack.py
- setup.py
Users would like to export the aligned images for use in other software or presentation
* added `CorrelatedStack.export_tiff()` method. `roi` kwarg allows for exporting a specific region
* some refactoring of the tests, adding fixtures to deal with test image and file generation
* works with either RGB or grayscale stacks, single- or multi-frame stacks
> Export (aligned) tiff files

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
**Why?**
It seems that the `Continuous` channel was no longer evaluated lazily and immediately pulled in all the data. This degraded performance and memory usage.
Note that `TimeTags` suffers from the same issue, but there it doesn't have a performance implication because it gets converted into a `numpy` array immediately in the constructor anyhow.
> channel: fix lazy evaluation of Continuous.from_data

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_point_scan.py
- lumicks/pylake/tests/test_scan.py
- setup.py
Currently the public `json` attribute in `confocal.BaseScan` is a regular Python dict read from the json metadata exported by Bluelake. This attribute should be deprecated so users are warned not to use it.
**What changed?**
* `BaseScan.json` is now a property decorated with `@deprecated`
* internal access to the metadata is still available as before through `BaseScan._json` 
* deprecated `BaseScan.has_force` and `BaseScan.has_fluorescence`. These fields were never really useful, now return hard-coded boolean values
> Deprecate confocal json public attribute

- changelog.md
- docs/api.rst
- docs/examples/reca_fitting/reca_fitting.rst
- lumicks/pylake/detail/alignment.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/fdensemble.py
- lumicks/pylake/file.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
- lumicks/pylake/tests/test_fdcurve.py
- lumicks/pylake/tests/test_fdensemble.py
**Why?**
Considering the relatively large number of breaking changes in the next release, let's make names a bit more consistent across the board first.
This PR renames `FDCurve` and `FDSlice` to `FdCurve` and `FdSlice` respectively.
> Rename FDCurve to FdCurve

- .github/workflows/pylake_test.py
- .github/workflows/pylake_test.yml
- lumicks/pylake/tests/conftest.py
- setup.cfg
Because I don't want to release a broken pylake again. During the v0.8.0 we had the problem that one of the files needed in the test wasn't being shipped. This wasn't picked up by CI, because CI doesn't actually test the installed package, but just whether pytest passes in the current working directory.
**Why this solution?**
This solution installs pylake using pip and runs the tests there.
Originally, I opted for the cleaner
`pytest --runslow --color=yes --pyargs lumicks.pylake`
But it wouldn't recognise our custom option `runslow`. Therefore this solution has the preference.
Note that I have moved the warning configuration from `setup.cfg` to `conftest.py`. The reason for this is that we want our testing configured when calling pytest in the imported module as well. …
> ci: test installation

- docs/install.rst
We're still having a lot of support originating from anaconda breakage. The default installation instructions have to be amended to reflect that we do rely on always creating a new environment for Pylake now. On Windows, we also need to set the correct path for Jupyter notebook to find the IPython kernel. This was also added to the list of installation instructions.
These installation instructions were tested on Windows and Linux.
Proposed docs can be found here: https://lumicks-pylake.readthedocs.io/en/conda_instructions/install.html
> docs: update conda instructions

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/detail/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/conftest.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
**Why?**
Would be nice to allow different `ForceCalibration` models to be used.
**What is all in this PR?**
`PowerSpectrum` is in its own file, with its own tests. I have moved keeping track of how much averaging has taken place into `PowerSpectrum`, since this guy owns that information.
Instead of a stateful class, the calibration is now a function that raises an exception when things go awry. You do however want access to the `PowerSpectrum` used for fitting if it fails. Instead, you now compute the `PowerSpectrum` with its own API, and pass it and an appropriate model to the calibration function. I've added some plotting functionality to it as well, which is probably not so relevant for automation/Bluelake, but nice to have in Pylake when adding new `ForceCalibration` models.
In the …
> Ldat refactor (pt. 1)

- lumicks/pylake/channel.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/force_calibration/detail/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/tests/test_utilities.py
While writing the docs I noticed two things that needed fixups. One, we  use `sample_rate` instead of `sampling_rate`.
The second is that how you specify how much the spectra need to be downsampled is a bit strange. The API takes a number of points to use for averaging. That is then converted to a number of blocks, which is then converted back to a number of points. By changing the API, we get more predictable behaviour.
It also deduplicates some code between channel and force calibration (and allows both to be covered by the same test of the basic functionality).
One thing that's worth noting is that this is part of the reason the original LDAT was using the wrong `n_points_per_block` in the actual fit (since it usually wasn't what you actually got and it was used …
> force_calibration: remove extra downsample factor conversions

- changelog.md
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
It fixes a bug in the Kymotracker that could occur when a bright structure suddenly ends.
The reason for this bug was that a filter that was being applied to reduce pixelation noise was being applied in two directions rather than just along the scan axis. This meant that the pixel could bleed through to the next column of pixels.
Note that while this bug affects peak _detection_, it should not affect peak localization, since this step is followed by a centroid estimation step.
> kymotracker: fix bug in peakfinding routine

- docs/install.rst
**Why?**
`Conda-forge` is apparently very slow from China. A local mirror for `PyPI` exists, so we might as well point users to it.
> docs: add docs for different PyPI mirror

- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
The old Force Calibration had a bug in the data weighting that lead to subtle differences. This mode reproduces the old (incorrect) behaviour in case someone wants to compare their results.
The reason for the difference is that the original Force Calibration used `num_points_per_block` from the `CalibrationSettings` class even though the actual downsampling provided him with a different actual downsampling. The refactored version fixes this bug leading to differences in the calibration. For the important parameters the differences are very small (fourth digit), but for the chi_squared_per_deg the difference can be more than 10%.
```
Bead diameter (um)  | BL:                            4.4 New:                            4.4	Compatibility (wrong): …
```
> force_calibration: Add compatibility mode

- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_image.py
While fixing something else, I noticed that this behaviour is unexpected.
When slicing a kymo, the intended behaviour was to use the starting timestamps of each line as a determinant of whether that line should be included. Instead, it was using the one beyond the end.
**Why not use `self.timestamps`**?
`self.timestamps` provides means of the timestamps of samples corresponding to each pixel. This can lead to strange issues with a partial pixel being cut off when slicing that way. You really want the first sample of each line.
**How could this one slip through the tests?**
The overarching test of the slicing is not precise enough. This is part of bigger problem which we hope to address soon, but which requires a bit of refactoring.
The test on the actual function grabbing …
> kymo: fix slicing bug

- changelog.md
- docs/_ext/nbexport.py
- docs/api.rst
- docs/refs.bib
- docs/tutorial/force_calibration.rst
- docs/tutorial/force_calibration_blocked_spectrum.png
- docs/tutorial/force_calibration_fit.png
- docs/tutorial/force_calibration_table.png
- docs/tutorial/index.rst
- docs/zrefs.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
To illustrate how to use the Force Calibration functions.
**Open issues**
- How should we deal with the fact that the calibration is slightly different now? Should we document it? Should I redo the reference calibration in the docs such that the two agree (assuming BL will be updated)?
The reason for the difference is that the original Force Calibration used `num_points_per_block` from the `CalibrationSettings` class even though the actual downsampling provided him with a different actual downsampling. The refactored version fixes this bug leading to differences in the calibration. For the important parameters the differences are very small (fourth digit), but for the `chi_squared_per_deg` the difference can be more than 10%.
See also: …
> force_calibration: docs

- changelog.md
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_scan.py
In pylake, the scan width the user entered was available through `scan_width_um`. While a user may be lured into believing that this is the actual scan width of the scan they're dealing with, it is actually not because Bluelake will round the scan to a fixed number of pixels multiplied by the pixel width. It would be better to reserve this property for the actually obtained scan width and have a separate property for the scan width as entered in the UI.
> confocal: differentiate ui scan_width from actual scan_width

- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Since the differences between the old and new force calibration were so small, it was decided to drop the compatibility mode with the old version (since it only adds more code to maintain).
If someone _really really_ needs it, it'll still be in the git history.
> force_calibration: drop compatibility mode

- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/tests/test_msd.py
Users would like to estimate diffusion constants from their single particle traces. This PR adds some back-end for doing MSD estimation. It implements methods from.
**What is in this PR?**
Essentially, it computes the MSD statistic and regresses a line through it. The optimal number of points to include depends on the localization uncertainty and to determine this the heuristic from [1] was implemented.
[1]. Michalet, X., & Berglund, A. J. (2012). Optimal diffusion coefficient estimation in single-particle tracking. Physical Review E, 85(6), 061916.
[2]. Michalet, X. (2010). Mean square displacement analysis of single-particle trajectories with localization error: Brownian motion in an isotropic medium. Physical Review E, 82(4), 041914.
**Why 1 of N?**
This PR merely has …
> kymotracker: estimate diffusion constant from MSD (1 of N)

- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- pyproject.toml
We currently catch and lump all errors that can happen during the analytical part of the force calibration. This is not helpful when debugging issues.
This PR handles two known preconditions explicitly (and provides more useful information) and lets the others bubble up.
> force_calibration: don't catch and rethrow exception

- changelog.md
- docs/tutorial/force_calibration.rst
- lumicks/pylake/__about__.py
We want to do a release to get some of the bugfixes and new features out there.
Note that this PR puts a notice at the top of the force calibration page that this API may still be subject to change (as this depends on how well the current API integrates with BL).
> release: preparing for v0.8.2

- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/data/mock_confocal.py
Mocking confocal images is needed for MSD 2a. Essentially this introduces some functions that make it possible to easily mock a confocal image. It also deduplicates some of the JSON generation.
> Mocking confocal (MSD 2`)

- changelog.md
- docs/tutorial/kymographs.rst
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
- setup.py
One of the issues with MSD 2 of N was that we spun out a separate class because we needed to handle downsampling. This is undesirable because it makes things more complex for the user (yet another object to think about).
Instead, this PR attempts to add downsampling to `Kymo` itself. To not make the same mess as before, I have also developed a small mocking setup, which allows us to mock Kymos.
One advantage of this setup is that the downsampling can be done lazily.
One alternative to this is to do something similar to https://github.com/lumicks/pylake/pull/132 and abstract the image in the `Kymo`. Then this `DownsampledKymo` could be a regular `Kymo` but with a different image as source. You'd lose the connection to the original though.
To enable this feature, and still be able to plot, …
> Kymo.downsampled_by(#) [MSD 2a of N]

- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- .readthedocs.yml
- changelog.md
- docs/install.rst
- lumicks/pylake/kymotracker/detail/trace_line_2d.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/tests/test_kymotracker.py
- pyproject.toml
- setup.py
This PR changes `KymoLineData` to a dataclass. It also adds some small syntactic sugar for generating a `KymoLine` (user facing) from a `KymoLineData` (backend only).
Dataclasses are nice.
Note that this PR requires dropping 3.6 support.
> Use a dataclass for KymolineData [MSD 2c]

- .github/workflows/pylake_test.yml
Black's dependencies should be installed after running pytest, so that its dependencies don't affect the tests. Otherwise this could mask missing dependencies.
Note that I did test this on a commit which had this problem, and indeed now the test that should have failed fails.
> black: don't let black affect the testing environment

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels.py
When using `Slice.downsampled_like()` to downsample a high frequency channel to the same timestamps as a low frequency channel output from Bluelake, the first 1-2 time points cannot be constructed due to missing HF data.
This PR introduces a breaking change where `downsampled_like()` now returns both the downsampled channel and a copy of the reference LF channel that is cropped such that the timestamps of both instances are exactly the same.
> Return cropped reference channel from downsampled_like

- changelog.md
- docs/tutorial/fdcurves.rst
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/fdcurve.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/data/mock_fdcurve.py
- lumicks/pylake/tests/test_fdcurve.py
Allow users to access FD curves exported with baseline correction from Bluelake.
Currently in Bluelake, the baseline is only calculated for the x-component `Fx`. However, as currently implemented in pylake, `FdCurves` by default are constructed using the channel magnitude `sqrt(Fx**2 + Fy**2)`. There are also future considerations (like piezotracking as the distance channel) which are not yet clearly defined. So it seemed most reasonable to add the `FdCurve.with_baseline_correction()` method to return a new instance using the corrected data rather than messing around with object construction from `File`.
~~I chose to add a `FdCurve._baseline_corrected` attribute to keep track of which data is used for each instance. However, I also considered making a separate `BaselineCorrectedFdCurve` …
> Handle baseline corrected FD curves

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_arithmetic.py
- lumicks/pylake/tests/test_channels.py
**What is this PR?**
It adds arithmetic operations on `Continuous` and `TimeSeries` slices.
Because it makes performing basic mathematical operations on slices a lot less cumbersome and will likely lead to people not immediately pulling their data out of our slice class all the time.
Note that we explicitly verify that the timestamps of the two channels in question are the same. There is still a performance improvement that could be done by specializing this for `Continuous` channel data, but I left that for another day.
> channel: add arithmetic operators

- changelog.md
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/tests/test_kymotracker.py
It fixes a pretty serious bug. I think the changelog describes it best:
Fixed bug in kymotracker which could result in `sample_from_image` returning erroneous values in some cases. When sampling the image, we sample pixels in a region around the traced line. This sampling procedure is constrained to stay within the image bounds. Previously, we used the incorrect axis to clamp the pixel index along the positional axis.
As a consequence, kymographs that are wider (in terms of number of pixels on the positional axis) than they are long (in terms of number of pixels along the time axis) would only have an accurate sampling in the top half of the kymograph. The lower portion of the kymograph would result in zero counts.
The fix is simple. You could clamp by the other axis. Now …
> kymotracker: fix position clamping bug in sample_from_image

- changelog.md
- lumicks/pylake/kymotracker/detail/calibrated_images.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/tests/test_kymotracker.py
This PR fixes a bug which could lead to bias when tracking lines using `track_greedy` with the rectangle tool.
Basically, in the widget, a user can select a rectangle in which to track lines. Selecting which region to track used to pass that region specifically to the tracking algorithm. This means that the algorithm is unable to sample the image outside of the passed region. Therefore, this can lead to a bias when the line to be tracked is near the edge of the selected region. In the updated version, all image processing steps that depend on the image use the full image.
One could argue that we could be more restrictive and apply the image processing on only a small portion of the image, but given that this is only a very small part of the run-time of the algorithm, the added complexity …
> Bugfix rectangle-based tracking `track_greedy`.

- changelog.md
- lumicks/pylake/kymotracker/detail/trace_line_2d.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/tests/test_kymotracker.py
This PR fixes a bug which could lead to bias when tracking lines using track_greedy with the rectangle tool.
Selecting which region to track used to pass that region specifically to the tracking algorithm. This algorithm does a lot of filtering, which means that all these results become biased if the distance between the edge of the ROI and the line becomes too small.
See also https://github.com/lumicks/pylake/pull/146 which fixes a similar issue for the other Kymotracking algorithm.
While the problem is similar, the fixes are different for the two algorithms (hence two PRs).
> kymotracker: fix bug in `track_lines`

- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
Currently slicing after downsampling undoes the downsampling. This is undesirable.
In the future, we will implement slicing in a different way, but a good implementation of this will depend on a number of other features being present first (copy constructor, a separate function for getting start times of the lines that is preserved under downsampling). For now, it's best to leave it explicitly `NotImplemented` to prevent users from getting dependent on weird behaviour.
This PR adds a check whether the factories are the defaults prior to slicing as any specialized factories would be ignored currently.
> kymo: raise NotImplemented error for slicing post downsampling

- changelog.md
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
This PR fixes a bug in the plotting order of `CalibrationResults.plot()`. Previously, when plotting after performing a force calibration, the model fit was erroneously plotted first (while the legend indicated that the model fit was plotted last). The results of the calibration itself are unchanged.
*Figure 1: Cool. The model looks more non-ideal than the data ?!?*
> force_calibration: fix plotting order model and data

- lumicks/pylake/fitting/tests/test_stepping.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/kymotracker/tests/test_calibrated_images.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
- lumicks/pylake/kymotracker/tests/test_msd.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/kymotracker/tests/test_tracing.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/nb_widgets/tests/test_mouse.py
- lumicks/pylake/population/tests/test_mixture.py
- lumicks/pylake/tests/test_channels.py
- lumicks/pylake/tests/test_correlated_stack.py
- lumicks/pylake/tests/test_fdcurve.py
- lumicks/pylake/tests/test_fdensemble.py
- lumicks/pylake/tests/test_fdfit.py
- lumicks/pylake/tests/test_file.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_kymotracker.py
- lumicks/pylake/tests/test_point_scan.py
- lumicks/pylake/tests/test_scan.py
- lumicks/pylake/tests/test_utilities.py
Diffusion constant and power spectrum tests were ineffective at catching problems, since the default absolute tolerance set by `numpy` was high enough for pretty big relative deviations to slip by (diffusion constants in volts are tiny, in the order of 1e-12). This PR tightens these tolerances to make sure the tests fire when something changes inadvertently.
Note that nothing was broken.
> force_calibration: tighten test tolerances

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/image.py
`tifffile` no longer automatically infers what `photometric` type it is dealing with, so now we have to do it.
> tiff: fix deprecation warning (photometric no longer inferred)

- changelog.md
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Currently, the returned model fit contains a `num_points_per_block` of `1`. Instead, it would make a lot more sense to store the number of points per block that were used in the fitting procedure.
This PR mitigates that by storing the number of points per block used for fitting in the `num_points_per_block` attribute of the fitted power spectrum.
> force_calibration: store points per block with fit

- changelog.md
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cas9_kymotracking/kymowidget.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_algorithm_scaling.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/conftest.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/tests/test_kymotracker.py
We recently switched over Kymographs in a way that they can hold calibrations.
In addition, the algorithms now return traces in real units. However, the algorithm parameters were not using these physical units (and still had to be specified in pixels). This PR mitigates this.
I would argue that this should be part of the `v0.9` release to minimize the number of breaking changes in versions after this.
**Notes**
- Note that a separate ticket exists to actually put these units on the sliders. It is out of scope for this PR.
- Plan is to squash this into a single commit when merging.
Docs for your reading pleasure: https://lumicks-pylake.readthedocs.io/en/kymo_units/
Changes are in the Cas9 example and the kymotracking tutorial.
> kymotracker: algorithm parameter units

- changelog.md
- docs/tutorial/fdfitting.rst
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/fitting/tests/test_model_sim.py
- lumicks/pylake/tests/test_fdfit.py
It's a popular feature request to simulate a force-distance model without fitting it first.
With relatively minor modifications, the call operator can be made to take both dictionaries with parameter values and `Parameters`.
**Things to look out for**
Note that this PR changes the `keys` attribute of `Parameters` to a method. I believe having it as a property initially was a mistake, since this is not how the default dictionary behaves.
Before:
```python
import lumicks.pylake as lk
from lumicks.pylake.fitting.parameters import Params, Parameter  # These were not public by default, so users would have to know already what to do
dna = lk.inverted_odijk("DNA")
distances = [.1, .2, .3]
dna(distances, Params(**{"DNA/Lp": Parameter(50.0), "DNA/Lc": Parameter(16.0), "DNA/St": …
```
> fdfit: Allow simulating the wlc model without fitting

- lumicks/pylake/force_calibration/detail/driving_input.py
- lumicks/pylake/force_calibration/tests/test_driving_input.py
To be able to do active force calibration, we need to know exactly the frequency and amplitude of the oscillation with which we were driving the stage. This PR adds a backend function that can estimate this from data.
> calibration: freq and amp estimation for driving input

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
`plot_with_force` always fails for kymographs with an incomplete last line.
The reason for this is that the last few timestamps on the last line have zero as their timestamp. This meant it was trying to downsample a range from X to 0, which made the downsampler think that there was no overlap between the kymograph and the force channel (as it checks the last timestamp of the ranges to downsample to against the first one of the channel to downsample).
I've also added a regression test for it.
There's one other issue I have with this function, which is that there's no way to have it use the LF force and that the string input for the channel is ambiguous (passing `downsampled_force1x` for channel is accepted, but it's not what would be used as a source). From the docstring …
> kymo: fix `plot_with_force` for kymos with an incomplete last line

- changelog.md
- docs/tutorial/force_calibration.rst
- docs/tutorial/force_calibration_table.png
- lumicks/pylake/__init__.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
**Why?**
To make integration with Bluelake easier and have a clearer separation between inputs and outputs of the calibration routine.
> Simplify force calibration API

- changelog.md
- lumicks/pylake/__about__.py
We would like to release v0.9. This PR makes a few small additional amendments to the changelog for clarity.
This release introduces a fair number of breaking changes. All of them are motivated in the changelog.
Note that this PR depends on #165 since that PR introduces some breaking changes that would be good to include in this release.
The dependency changes since last release are:
- `numpy` minimum version was bumped from `1.14` to `1.20`.
- `scikit-image>=0.17.2` was added
- Support for `Python` `3.6` was dropped (in favor of `DataClasses`).
> Release v0.9

- changelog.md
- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
For active force calibration it has to be possible to exclude specific regions from the fit. This PR adds that functionality to `PowerSpectrum`.
Typically what happens in an active force calibration procedure is that you'd have a driving input frequency (a spike in the frequency spectrum) that needs to be excluded prior to fitting the thermal part of the spectrum.
In addition, this functionality can be used to reject noise peaks that may happen at various frequencies.
> force calibration: implement exclusion of specific frequency ranges

- changelog.md
- docs/tutorial/force_calibration.rst
**Why?**
Unfortunately, one equation in the documentation didn't get updated appropriately when we made the switch from `0.5 V^2/Hz` to `V^2/Hz`. This PR fixes that.
> docs: correct error in equation used for force calibration

- lumicks/pylake/force_calibration/tests/data/simulate_calibration_data.py
- lumicks/pylake/force_calibration/tests/data/simulate_ideal.py
- lumicks/pylake/force_calibration/tests/test_simulations.py
We need to be able to simulate test spectra to test the force calibration procedures.
**What's in here?**
There's two methods here. One is to simulate active calibration spectra via actual simulation of the Langevin equation. This is quite slow and requires oversampling to reduce aliasing. This only does idealized spectrum (since I do not have a model for the hydrodynamics at this point).
The other method is a method that can simulate any desired power spectral density (which will be useful for when we start simulating hydrodynamically correct spectra) and add a driving oscillation to it. Since the Langevin equation is linear, these can be treated separately. One caveat of this method is that it does not produce the correct phase on the driving input, but for a purely …
> Force calibration: Simulate calibration spectra

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/driving_input.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/data/simulate_calibration_data.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_simulations.py
Because we want to have active calibration functionality in Pylake.
This PR contains the basic scaffold for active calibration for an ideal spectrum.
The suggested API looks something like this:
```python
model = ActiveCalibrationModel(
driving_data,
force_voltage_data,
sample_rate,
bead_diameter,
driving_frequency_guess,
viscosity,
temperature,
)
power_spectrum = calculate_power_spectrum(force_voltage_data, sample_rate)
fit = fit_power_spectrum(power_spectrum, model)
fit.plot()
fit
```
**Out of scope, but good to keep in mind when considering architecture**
Documentation is out of scope, since this functionality is not yet public (we deliberately do not import it yet).
This PR does not cover:
- Hydrodynamic correction.
- Bias correction.
- Fixing …
> Force calibration: Active calibration scaffold model

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_kymo.py
`plot_with_force` was not summing over the full line range, but from the center of the first pixel to the center of the last pixel. It also had problems with an incomplete last pixel (always resulting in an exception). This PR changes it so that it is exact and fixes the last pixel issue.
**What to look out for**
To achieve this, I generalized `_timestamps` that allows us to provide a custom reduce function (which will also properly get cached). The only downside of this mini refactor is that it means that we cannot specify a custom downsampler for timestamps in `kymo.downsampled_by()` anymore.
Technically, that makes this a breaking change, though a breakage that I don't expect would affect many people.
The alternative is adding another factory function that is …
> Make `plot_with_force` sum over entire kymo line.

- changelog.md
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_kymo.py
**Why?**
Users often want to exclude the beads from downstream analysis. Therefore it is useful if they can actually crop the kymo easily.
This API introduces Kymograph cropping.
There is also a plan for updating the Cas9 notebook with this functionality, but I will make a separate PR for that.
Note: This PR depends on https://github.com/lumicks/pylake/pull/171
> Cropping kymographs.

- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
It fixes a critical bug in Kymograph slicing that would lead to erroneous timestamp reconstruction.
**What went wrong?**
Kymographs are encoded with the so-called infowave. It's a list containing a mapping which indicates which sample to include, where the pixel ends are etc. Reconstruction is hardcoded to use a constant number of samples per pixel. There is no way to tell where a line ends in the kymograph (other than knowing the number of pixels in the kymograph metadata).
When slicing a kymograph, we need to round the slicing to the next kymograph line to make sure reconstruction does not fail.
In PR https://github.com/lumicks/pylake/pull/124 we changed the code that handles the slicing to use the same reconstruction algorithm to obtain the timestamps. Unfortunately, …
> Invalid timestamps after slicing `Kymo`

- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
Currently, in order to import kymolines from a saved .csv you first need to load a `Kymo` instance, manually construct a `CalibratedKymographChannel` from this and the channel name, and finally feed this into the import function. It would be easier to just hand the kymo and channel name directly to the import function and construct the calibrated image internally.
Note, this is an internal function for the time being as the .csv format is likely to change; however in the future when it is made public it cannot rely on the internal `CalibratedKymographChannel` class
> Import kymolines with Kymo instance

- changelog.md
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file.py
Add support for axial force detection (i.e. force detection along the Z-axis). The high-frequency data can be accessed with `f.force1z` and `f.force2z` while the downsampled low-frequency channels can be accessed with `f.downsampled_force1z` and `f.downsampled_force2z`. The calibrations can be accessed with `f.force1z.calibration` and `f.force2z.calibration`. The Z component is *not* factored in the calculation of the total force `f.force1` and `f.force2` as specifically requested by BD.
> file: add support for axial force detection

- lumicks/pylake/force_calibration/detail/driving_input.py
- lumicks/pylake/force_calibration/tests/test_driving_input.py
When doing active calibration, we have to find the input magnitude and frequency from the nanostage (or in the future trap) signal.  To obtain this we choose a small region of the Gaussian windowed frequency spectrum and find the largest peak in that region. 
After that, we regress a polynomial to an even smaller range (typically three points) of the log magnitude which provides us with the peak amplitude and frequency.
The best accuracy is obtained if the peak is actually in this region, but this relies on the search range being chosen appropriately in the first step.
This PR adds some validation on whether the peak was indeed in the search range, and whether the found magnitudes correspond to a peak rather than a dip.
If either of these conditions is not met, we throw …
> force_calibration: better validation driving input

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Using bead diameters less or equal to zero produces non-sensical calibrations (NaNs).
The field for bead diameter in Bluelake defaults to zero, so this can be confusing. With this fix it now raises an exception when zero is passed to the calibration routine.
> force_calibration: check bead diameter > 1e-6

- setup.py
Latest version of `scikit-learn` is resulting in segmentation faults on CI for `macos-latest`.
The following minimal example segfaults on CI:
```python
from sklearn.mixture import GaussianMixture
import numpy as np
model = GaussianMixture(n_components=2, init_params="kmeans", n_init=1, tol=1e-3, max_iter=100)
data = np.array([[11.20871134], [11.01644412], [11.11502055], [10.8732648]])
model.fit(data)
```
It seems to be segfaulting in `init_bounds` in [k_means_elkan.pyx](https://github.com/scikit-learn/scikit-learn/blob/1.0/sklearn/cluster/_k_means_elkan.pyx).
```python
Fatal Python error: Segmentation fault
Thread 0x000000010e82adc0 (most recent call first):
File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line …
```
> deps: pin `scikit-learn` to circumvent segfault

- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_correlated_stack.py
This PR addresses two bugs in `CorrelatedStack.export_tiff()`
- previously, attempting to export grayscale images (such as IRM) would throw an exception because the alignment matrices metadata is not there
- exporting changes the alignment matrices metadata keys from `Channel X alignment` to `Applied channel X alignment` to indicate that the data no longer corresponds to the raw data recorded in Bluelake. However, these fields were always changed regardless if the alignment was actually applied to the data or not.
In the process of fixing these, the mock test data was also updated to bring it more in line with what the real files look like.
> Fix CorrelatedStack export bugs

- lumicks/pylake/force_calibration/power_spectrum_calibration.py
Why this PR?
Currently a calibration parameter with value `None` throws a `TypeError` when a `CalibrationResults` object is printed. Now it will just be printed as a blank string
> Support `None` value parameters in calibration results repr

- changelog.md
- docs/api.rst
- docs/refs.bib
- docs/tutorial/kymo_bic_compare.png
- docs/tutorial/kymo_bind_bootstrap_2.png
- docs/tutorial/kymo_bind_dwell_1.png
- docs/tutorial/kymo_bind_dwell_2.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/binding_times.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/data/exponential_data.npz
- lumicks/pylake/kymotracker/tests/data/generate_exponential_data.py
- lumicks/pylake/kymotracker/tests/test_binding_times.py
Often it is interesting to quantify the average time a protein binds to a DNA tether, as this can gives information about the kinetics and/or thermodynamics of the system. This is accomplished by fitting a list of dwelltimes (how long a single protein stays bound to the DNA) to an exponential distribution, or weighted mixture of exponential distributions.
Docs are [here](https://lumicks-pylake.readthedocs.io/en/binding_dwell_v2/tutorial/kymotracking.html#dwelltime-analysis) and details the motivation and certain caveats that are important for properly performing analysis.
The public API is a single method `KymoLineGroup.fit_binding_times()`. This returns an immutable object containing many relevant parameters and statistics of the optimization.
**Things to note**
- all of …
> Kymotracker: bound dwelltime analysis

- changelog.md
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/detail/calibrated_images.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_calibrated_images.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/tests/test_kymo.py
Often it is more interesting to know the position of binding events in base pairs along the DNA tether rather than in microns.
**Things to note:**
- calibration is forwarded to all downstream analyses (plotting, kymotracking, MSD analysis)
- length in microns is still available (since this information is in the original h5 file and some attributes such as `pixelsize_um` are public). I think this is reasonable since you might want to know some information in um and other info in bp
- I chose to use a small dataclass to store the calibration information. This allows access to the current unit, formatted labels for plotting, and we can extend with other functionality in the future as needed without introducing tons of attributes to `Kymo`. Additionally in the future we will …
> Calibrate kymographs to base pairs

- changelog.md
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
It was noticed that for very low corner frequencies the fit would sometimes fail with a `math domain error`.
What was happening is that in the procedure used to make an initial guess of the corner frequency and diffusion constant, one term (which is monotonically related to the estimate of the corner frequency) becomes negative. Since we take the square root of this term, it fails (since it would have to be complex). 
This is sad, because most of the time, the non-linear fit would've recovered and produced a mostly reasonable estimate. Now this case is gracefully handled by setting the initial guess halfway between the lowest frequency in the power spectrum and zero.
**Notes**
Note that this PR removes the test for `bad_data`. This is because before, we were essentially …
> force_calibration: handle corner case fc < lbnd in analytic fit

- changelog.md
- docs/api.rst
- docs/tutorial/driving_input.png
- docs/tutorial/force_calibration.rst
- lumicks/pylake/__init__.py
This PR documents active calibration and makes it part of the public API.
Docs build here:
https://lumicks-pylake.readthedocs.io/en/active_calibration_docs/tutorial/force_calibration.html#active-calibration
> force_calibration: document and release active calibration

- changelog.md
- docs/refs.bib
- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/drag_models.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_axial.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Both for distances very close to the surface as well as axial force, the hydrodynamic model is less than suitable.
In these cases it is recommended to just use a simple Lorentzian, but take the distance to the nearest surface into account through the drag coefficient.
The effective drag coefficient at a particular distance from the surface is given by:
`gamma(l) = gamma_bulk * height_factor(l)`
This PR adds this option.
**More info**
When the hydrodynamic flag is set to off, but a height is specified, it will apply a correct correction on the drag force.
Note that the correction is different for axial and lateral force! For this an extra flag was added to the calibration models named `axial`.
Note that in the future, we will rely on carrying over drag coefficients from …
> Force calibration: Drag correction

- changelog.md
- docs/api.rst
- docs/refs.bib
- docs/tutorial/force_calibration.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Viscosity is a sensitive calibration parameter. Typically, users do experiments in water.
When no viscosity is specified, we will now use the viscosity of water at that particular temperature as the default.
I decided to go with the simplified model from [1]. The advantage of this model is that it covers a wider range (the Peterman model [2] mentions it should only be used >= 20 C). [3] is the reference Stijn used in his code (but not in his report, where he used [2]).
[[1] Huber, M. L., Perkins, R. A., Laesecke, A., Friend, D. G., Sengers, J. V.,Assael, M. J., & Miyagawa, K. (2009). New international formulation for the viscosity of H2O. Journal of Physical and Chemical Reference Data, 38(2), 101-125.](http://ikee.lib.auth.gr/record/218228/files/Assael3.pdf)
[[2] …
> calibration: use viscosity of water as default

- .github/workflows/pylake_test.yml
- docs/_ext/nbexport.py
- lumicks/pylake/detail/confocal.py
The version of black we use used `typed-ast`. Typed-ast currently has an open issue on 3.9.8 which is causing black to break; see here: https://github.com/python/typed_ast/issues/169
The latest version of black doesn't rely on the library with the issue anymore and just works. Note that the latest version of black made a few touchups to some docstrings. I have committed these in a separate commit as `black`.
Note that after this gets merged, you will have to update your local install of `black` to `21.10b0`.
> Update to newer version of `black`

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_correlated_stack.py
`CorrelatedStack.raw` exposes a list of internal `widefield.TiffFrame` instances. Additionally, the output is dependent on the number of frames in the stack (returns a `list` if `num_frames > 1` or a single `TiffFrame` if `num_frames == 1`). 
Likely the main use for this property is in constructing a `np.array` of the frame data, which will be implemented as a public method in an upcoming PR. Any other uses for the output of this property in the future should also be implemented as a public method/property directly on `CorrelatedStack` or (for internal use) can still be accessed by `[stack._get_frame(j) for j in range(stack.num_frames)]`.
> Deprecate `CorrelatedStack.raw`

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/test_correlated_stack.py
Sometimes you just want the pure data to work on. This adds a convenience method so that users don't have to fiddle around with the internal source data classes.
[docs are here](https://lumicks-pylake.readthedocs.io/en/wit_get_data/tutorial/correlatedstacks.html)
> Get `CorrelatedStack` data as `np.ndarray`

- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/test_correlated_stack.py
While prepping figures to add to the `CorrelatedStack` docs, I noticed a bug in which alignment was not requested (`CorrelatedStack(filename, align=False)`) yet the aligned data was still returned. This PR fixes the bug and adds a regression test
> Bugfix: WIT color-aligned data is returned but not requested

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_axial.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- Add a small private API for using drag from lateral experiment, and make sure the field name changes so it can be seen in the results.
- The name of the field where the experimental drag can be found is stored as an attribute so we don't have to hardcode the fieldname in both Pylake and Bluelake.
- Fixes a bug in `viscosity_of_water`. This function should return a 0D array for a 0D input.
> force calibration: small private API for carrying over drag coefficient

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/test_channels.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_kymo.py
- lumicks/pylake/tests/test_utilities.py
Currently, `reconstruct_image` converts `Scan` and `Kymo` `timestamps` to a floating point representation. This is undesirable. In addition, any incomplete pixel will now be dropped from reconstruction.
After the fix, `reconstruct_image` will provide as output the same type as the input.
To prevent changing two things at once, we enforce the type on image reconstruction to remain float (since certain downstream algorithms have issues with fixed precision types).
Note that I have hardened the tests for tests involving timestamps as well by providing a more realistic offset. I made these two separate commits, so I would recommend going commit by commit.
Note: Because I force pushed to the branch, I couldn't reopen the old PR :(
> Prevent conversion of timestamps to floating point during image reconstruction.

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
It's been requested to allow changing the ranges of the sliders in the kymotracker widget.
The modification in this PR allows you to override the slider ranges when opening the widget.
Docs build here: https://lumicks-pylake.readthedocs.io/en/kymo_slider_ranges/tutorial/kymotracking.html#using-the-kymotracker-widget
> kymotracker: allow changing slider ranges in the Kymotracker widget

- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Just a small dunder method because it's driving me crazy that I can't just do:
```python
"gamma_ex" in result
```
To quickly check whether it's there.
> calibration: add contains operator to `CalibrationResults`

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
**Why?**
It's nice to have a way to access all the output from the calibration procedure in one and the same data structure. Up to now, you had to keep both the `CalibrationModel` and `FitResult` around, since you needed results from both.
Note: I piggybacked a tiny fix on this for a matplotlib `DeprecationWarning` that showed up in the tests.
> calibration: store driving peak parameters

- changelog.md
- docs/tutorial/kymotracking.rst
The kymotracker tutorial previously indicated the incorrect number of samples for `sample_from_image`.
> docs: fix error in kymotracker tutorial

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Added more input validation for force calibration. We now force bead and sample density to be more than 100 kg/m^3 when specified. Temperature should stay between 5 and 90 degrees Celsius and viscosity should be bigger than 0.0003 (viscosity of water at 90 degrees Celsius).
***Why this PR?**
Reason we wish to validate some more input parameters is because certain invalid parameters produce garbage results (`viscosity = 0`, `bead_density = 0` etc). Also, by pinning them to at least ballpark values we reduce the chances of user error (for example passing Kelvins instead of Celsius, or passing viscosity or density in an incorrect unit).
> force_calibration: validate calibration params

- lumicks/pylake/detail/tests/test_widefield.py
- lumicks/pylake/detail/widefield.py
As I was working on the feature to define the location of the tether between two beads (and rotate the image such that the tether is horizontal) it became clear that it is cleaner to centralize all of the code having to do with affine transformations. In addition, when the tether feature is implemented, we can simply multiply the color correction and rotation matrices to do a single linear interpolation to get to the final data.
Note: I added a `tests` directory to the `details` module as this module is growing and we have a bunch of code in there that either isn't tested at the low level or is tested in the main tests.
> Wrap affine transformation logic in a small dataclass

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
This fixes a bug which allowed calibrations with a parameter set to zero to go through.
This fix ensures that they lead to an exception.
> force_calibration: ensure zero parameter values are rejected

- changelog.md
- docs/tutorial/images.rst
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/test_scan.py
This PR adds a function to obtain the start and stop timestamp of individual `Scan` frames. This was a user request.
Note that the name `frame_timestamp_ranges` is a bit verbose, but `timestamps` is already taken for the per pixel timestamps. `time_ranges` doesn't communicate that we are talking about `timestamps` here and `frame_timestamps` doesn't imply well enough that the returned quantity is a range. Please feel free to suggest a better name. Especially since the plan is to add an alias on `CorrelatedStack` with the same name (so that the API for getting these downsampled series is the same on both sides).
Another PR will build on top of this to provide users with a small widget to quickly correlate these. This second PR will expose the same widget as we already have …
> `Scan`: added `frame_timestamp_ranges()`

- docs/install.rst
Remove the instruction to run `python -m ipykernel install --user` from the
installation instructions, since this interferes with kernel detection in other
virtual/conda environments.
Instead, add a FAQ/troubleshooting section, explaining the situations in which
running this command may be necessary.
> docs: update installation instructions

- lumicks/pylake/channel.py
We got a support question about the returned items from this function. Now it returns a tuple of `Slice` objects for the downsampled data and a cropped version of the original LF data with the same time stamps. Previously, only the downsampled `Slice` was returned.  This change is already documented in the tutorial, but here we add a description to the API page for clarity.
https://lumicks-pylake.readthedocs.io/en/ds_like_docs/_api/lumicks.pylake.channel.Slice.html#lumicks.pylake.channel.Slice.downsampled_like
> Update API docs for `Slice.downsampled_like()`

- changelog.md
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/models.py
- lumicks/pylake/tests/test_fdfit.py
When subtracting an independent offset, this new parameter is not given a unit.
```python
dna_handles = lk.inverted_odijk("dna_handles").subtract_independent_offset() + lk.force_offset("dna_handles") 
fit = lk.FdFit(dna_handles)
fit[dna_handles].add_data("test", [1], [1])
fit
```
Old:
New:
Note: Eventually, we may want to carry over the unit handling to pint, which is why I've explicitly made these private properties for now.
> fd fitting: add units to (in)dependent variable

- changelog.md
- docs/tutorial/correlatedstack_aligned.png
- docs/tutorial/correlatedstack_cropped.png
- docs/tutorial/correlatedstack_raw.png
- docs/tutorial/correlatedstack_red.png
- docs/tutorial/correlatedstack_tether.png
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/tests/test_widefield.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/test_correlated_stack.py
This adds functionality to define the location of the tether between beads, which will be needed in order to construct WIT kymographs in the future.
Additionally, when the tether coordinates are set, the returned image data is rotated such that the tether is horizontal. Rotation is combined with the color channel alignment if applicable, such that only one linear interpolation is needed to get to the final image
> Add function to define the coordinates of the tether between beads

- lumicks/pylake/marker.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/data/mock_json.py
- lumicks/pylake/tests/test_file.py
Users need to be able to access specific metadata associated with markers.
Basically it's a `json` attached to a key named `payload` on a marker.
Private API for now since this is for a single user in particular for now.
> force_feedback: support marker metadata

- changelog.md
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/tests/test_stderr.py
Currently, Pylake evaluates the covariance matrix for the unconstrained fitting problem (not taking into account possible fixed parameters). This leads to overly pessimistic standard errors (too big).
This PR fixes that issue.
> fdfit: fix standard errors in the presence of fixed parameters

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
Previously, we were determining which line tip was clicked by converting to pixel coordinates. This connection tolerance can be surprisingly finicky in `jupyter notebook` but not `lab`. It seems that internally it renders to a higher resolution image.
This PR changes that handling to handle whether the click was close enough by considering the distance relative to the axes data limits.
> widgets: increase tolerance connect lines

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
We do not support active axial force calibration. The model is not valid here.
> force_calib: remove axial parameter active calibration

- changelog.md
- docs/tutorial/images.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/nb_widgets/correlated_plot.py
- lumicks/pylake/nb_widgets/tests/test_correlated_plot.py
- lumicks/pylake/scan.py
Allow users to also interactively explore the correlation between `Scan` objects and channel data.
**What to look out for?**
I also changed some of the default scaling behaviour. Reason being that the old behaviour opens figures too wide for realistically sized scans. Now I force the relative widths to be `1 : aspect_ratio` of the image, but I'd happily take any suggestions for better alternatives.
I considered piggybacking forwarding of `**kwargs` to this, similarly how we do it for `.plot()`, but decided against it, because I think we need to think about a better API for image adjustments than just forwarding to the very limited options on `imshow`.
Example (this was wider than the notebook):
Here are some examples of the widget in use now:
On a cropped TIFF stack (RGB) …
> scan: add `plot_correlated` for scans

- changelog.md
- docs/tutorial/nbwidgets.rst
- docs/tutorial/widget_stack_editor_1.png
- docs/tutorial/widget_stack_editor_2.png
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/nb_widgets/image_editing.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/tests/test_correlated_stack.py
Because everybody loves interactive plots!
There are currently two actions possible:
* scrolling with the mouse wheel to scroll through the image frames
* left-clicking to define the end coordinates of the tether
I've tested this in both a normal script and in jupyter notebook and lab. Docs are [here](https://lumicks-pylake.readthedocs.io/en/interactive_tether/tutorial/nbwidgets.html#image-stack-editor)
I've chosen to implement this plot by subclassing `mpl.Axes` which is a different method than we use for all of the other widgets. Personally I find this way much cleaner because all of the visualization and event handling can be abstracted/encapsulated away to the axes instance. If we like this way of doing things, I think it would be straight-forward to refactor some of …
> Interactive plot for `CorrelatedStack` tether definition

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/tests/test_correlated_stack.py
The values of `CorrelatedStack.timestamps` was inconsistent with those from `Scan.timestamps`. The frame start/stop timestamp pairs were returned for the former while individual pixel timestamps are returned for the latter.  Instead, `Scan.frame_timestamp_ranges` (added in #229) is in line with the values available for camera based images. With this change, the two APIs are now consistent
> Replace `CorrelatedStack.timestamps` with `frame_timestamp_ranges` (via deprecation)

- changelog.md
- docs/tutorial/nbwidgets.rst
- docs/tutorial/widget_stack_editor_3.png
- docs/tutorial/widget_stack_editor_4.png
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/nb_widgets/image_editing.py
- lumicks/pylake/nb_widgets/tests/conftest.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
drag to crop is nice. Docs are [here](https://lumicks-pylake.readthedocs.io/en/interactive_crop/tutorial/nbwidgets.html#image-stack-editor)
*Note*: while writing the tests for this, I noticed that our mock event for rectangle selection had the coordinates backwards; it was receiving `(y, x)` pairs instead of `(x, y)` pairs. I piggybacked the fix for this here as I needed that even for tests anyway.
> Add cropping to WIT image editor

- changelog.md
- docs/tutorial/kymo_bind_histogram_1.png
- docs/tutorial/kymo_bind_histogram_2.png
- docs/tutorial/kymo_bind_histogram_3.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
Requested convenience function from users. I split this up into an internal backend function that actually calculates the data needed to construct the histogram (for use in other places) and a public function for actually generating the plot.
The original ticket requested a histogram of only the initial binding events (the first position of each track); however it was straightforward to also include histogramming all of the positions of each track, which is also a useful metric, so I wrapped it in this PR.
Docs are [here](https://lumicks-pylake.readthedocs.io/en/hist_bind_events/tutorial/kymotracking.html#plotting-binding-histograms)
> Histogram kymotrack binding events

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/gaussian_mle.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_gaussian_mle.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
Estimating both a Gaussian and offset parameter can introduce unnecessarily high variance when the region used for fitting is narrow. An alternative is to estimate the background separately in a pre-processing step and just use that as a fixed parameter in the model.
This PR allows that option.
Note that a widget to determine the offset is planned and therefore explicitly omitted from this PR.
Docs build here: https://lumicks-pylake.readthedocs.io/en/fixed_gaussian/
> kymotracker: allow a fixed offset for the Gaussian refinement.

- docs/tutorial/kymotracking.rst
The example `kymolines[0].msd(mag_lag = 5)`, has been changed to `kymolines[0].msd(max_lag = 5)`
The docs mentioned that 'it may be tempting to use a large number of MSDs', but this should be 'a large number of lags'
> docs: small fixes to msd documentation

- .gitattributes
- docs/conf.py
- docs/fav.ico
- docs/index.rst
- docs/logo_dark.png
- docs/logo_light.png
- docs/logo_mono.png
- docs/logo_notext.png
- readme.md
Now that we have an actual logo, we should use it.
Went with the logo with text, since the one without looked quite imposing when displayed large.
Also updated the `readme.md` a bit to not distract from the actual docs like they used to. I tried to summarize the main features best I could, but comments on this are very welcome.
As an added bonus, I added a little favicon with the logo to the docs.
Docs build here: https://lumicks-pylake.readthedocs.io/en/logo_readme/
> docs: add logo to docs and readme

- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
Specifically for `Kymo` we ended up with 4 methods which require copying `self` and modifying only a few attributes resulting in duplication of the rather long `__init__()` call. This way is cleaner.
Note: inside `BaseScan.__copy__()` we call the `__init__()` method such that the cache is not propagated to the copied instances.
> Add copy method for confocal classes

- changelog.md
- docs/tutorial/fdfitting.rst
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/tests/test_fit.py
Currently, when plotting a fit made with the FdFitter, we put the data name as default label. If a user tries to override this, they get an exception (since the label is provided both by us and the `**kwargs` then.
This PR adds the option to provide a `label` argument.
> fdfit: allow using custom plot label

- changelog.md
- docs/tutorial/images.rst
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
This is a basic functionality that we've been putting off for a while, but the recent introduction of `Scan.frame_timestamp_ranges` makes it fairly simple to implement. Behavior is identical to that implemented for `CorrelatedStack`.
[Docs here](https://lumicks-pylake.readthedocs.io/en/scan_slicing/tutorial/images.html)
> Slice `Scan` objects by frame indices

- changelog.md
- docs/api.rst
- docs/tutorial/force_calibration.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
It can be convenient to just have a single function call for performing a calibration and have the backend worry about how to hook everything up in the low level API.
This allows some ease of use when writing notebooks where you generate dictionaries with calibration parameters or when you quickly want to switch between active and passive calibration and compare results.
I tried my best to order and group the parameters in a sensible way. I do enforce keyworded arguments, so that we could potentially iterate on the order of the optional ones if feedback arises.
A note on the testing. I tested that the non-default parameters came through correctly. I did not do a full spectrum simulation, because those are a bit costly to generate, and there's no added value considering …
> Convenient calibrations

- docs/conf.py
- docs/requirements.txt
Because of the size of the images on `readthedocs` version 1.5 of the python package `git-lfs` (not to be confused with actual `git-lfs`) started failing because it was pulling them as one big request. The requests exceeded some limit and returned HTTP error 413.
That package does have a newer version which introduced splitting requests (see https://github.com/liberapay/git-lfs-fetch.py/pull/7). However, this version requires auth tokens now (https://github.com/liberapay/git-lfs-fetch.py/pull/5).
This is why I propose switching to https://github.com/ssciwr/sphinx_lfs_content which maintains a simple workaround for installing `git-lfs`.
> docs: use `sphinx_lfs_content`

- changelog.md
- docs/tutorial/figures/kymographs/kymo_calibrated.png
- docs/tutorial/figures/kymographs/kymo_cropped.png
- docs/tutorial/figures/kymographs/kymo_cropped_and_sliced.png
- docs/tutorial/figures/kymographs/kymo_downsampled_position.png
- docs/tutorial/figures/kymographs/kymo_downsampled_time.png
- docs/tutorial/figures/kymographs/kymo_downsampled_time_and_position.png
- docs/tutorial/figures/kymographs/kymo_interactive.png
- docs/tutorial/figures/kymographs/kymo_interactive_result.png
- docs/tutorial/figures/kymographs/kymo_intro.png
- docs/tutorial/figures/kymographs/kymo_manual_plotting.png
- docs/tutorial/figures/kymographs/kymo_sliced.png
- docs/tutorial/kymographs.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/nb_widgets/image_editing.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
Interactive plots are nice. The interactive plot works essentially the same as the recently added one for widefield data (#236 and #239)
I also re-arranged some of the [docs](https://lumicks-pylake.readthedocs.io/en/interactive_kymo/tutorial/kymographs.html) and added images, as these docs were pretty barren before.
> Interactive cropping and calibration for kymos

- changelog.md
- docs/tutorial/figures/kymographs/kymo_correlated.png
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
This PR combines two small tickets. The first is to document `kymo.plot_with_force`. The second is to use low frequency force as a fallback when high frequency force is unavailable (this was a requested feature).
I've piggybacked forwarding custom arguments to `imshow` as well, since without this feature, most kymographs will simply be too dark.
> kymo: plot with low frequency force channels

- changelog.md
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
- lumicks/pylake/nb_widgets/detail/undostack.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_undostack.py
This was fairly highly requested functionality for the kymotracker widget.
Since the tracking steps typically take long and the actual data being stored is very very small (just some coordinates), I opted for a model where a history stack of the entire state of all the lines is stored. This keeps things implementationally quite simple.
However, since the `KymoLineGroup` is not immutable, there were two places where I was forced to make an explicit copy before changing it. I have added a comment on the lines where this happens.
We could alternatively consider going for a model where the `KymoLineGroup` is immutable. This would simplify the code on the widget side, but induce unnecessary copies elsewhere. It would also be a breaking change.
> kymowidget: add undo/redo functionality

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/image.py
- setup.py
Fixes a `DeprecationWarning` regarding `TiffFile`.
`imwrite` was introduced in 2018.11.6 (https://github.com/cgohlke/tifffile/blob/master/CHANGES.rst).
Unfortunately `TiffWriter.save` was introduced in `2020.9.30` and will require a version bump.
> ci: fix tifffile.imsave deprecation warning

- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
One of the challenges with the previous approach is that for the optimization to be successful, we need to be close to the actual optimum. The reason for this is that the log likelihood of this problem is very flat (the amplitude collapses when the frequency becomes more wrong) once you go away from the correct frequency (see figure below).
I noticed a lack of robustness when providing estimates that were even moderately far from the optimum. This means that the strategy employed previously (minimizing for each value of a range) is likely quite suboptimal, as many of these optimizations will either just fail or go to the same minimum.
I propose a small change, opting for a quick scan followed by a bounded optimization. This yields more robust results even when providing a rather rough …
> touchdown: improve robustness sine fit

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/gaussian_mle.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_gaussian_mle.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
Because we wish to correctly deal with overlapping lines in `refine_lines_gaussian()`. If two lines get close, the refinement will now do a simultaneous fit for these lines.
Notes:
Part 1 of this PR can be found in https://github.com/lumicks/pylake/pull/258
This PR also fixes a bug in `refine_lines_gaussian()` which incorrectly rounded the pixel position (`rint`) instead of flooring it. For pixels with a subpixel position larger than half the pixel, this resulted in shifting the window by one pixel in the positive direction. Typically, this would have little or no effect since the majority of the peak should still be covered.
Blue is when taking a big window and using `"ignore"` (blue) instead of `"fit_multiple"` (red)
*from Ray: I pushed 3 commits at the end to try to …
> gaussian_mle: make refine gaussian take into account multiple peaks in close proximity

- changelog.md
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Request from multiple users. Sometime you want to connect two nearby tracks that are slightly overlapped in time (by a couple frames). Previously this was impossible as we only supported connecting between the track ends. Now you can connect between any two nodes; the ends of the tracks are trimmed to these points and then concatenated
.
> Kymotracker: allow manual connection between any nodes in tracks

- .github/workflows/pylake_test.yml
- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/tests/data/mock_widefield.py
- setup.py
This PR adds Python `3.10` support to CI. It also bumps the `tabulate` dependency which prevented use of Python 3.10 (see https://github.com/lumicks/pylake/issues/266).
Since we were generating a few warnings when running the tests, I decided to delve into these a little bit and clean them up. Therefore this PR also consists of a few small fixups. I have described the reason for each minor fix in the relevant commit message.
Note that we still generate some warnings from matplotlib renaming an argument in the constructor of the `RectangleSelector`. We will fix that on the next breaking release by bumping the `mpl` dependency.
The fix in `crop_and_rotate()` hasn't actually been in a release yet, so it doesn't warrant a changelog entry. The other fixes merely affect tests.
> Spring cleaning and Python 3.10

- changelog.md
- docs/tutorial/kymotracking.rst
- readme.md
The badge in the readme should point to the workflow builds.
I piggybacked a fixup to the documentation onto this PR.
> Badge in the readme should link to workflows.

- changelog.md
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
There is a minor bug in `KymoLineGroup.fit_binding_times()` in which tracks with ambiguous dwelltimes are included in the analysis. Tracks which begin on the first frame or end on the last frame of the kymo should be excluded since, in general, we do not know the true start/stop times of the track.
Now the default behavior is to ignore these tracks, but I added a keyword argument to override the behavior. In some cases this is desirable. For example if the user incubates the tether in a channel with the protein of interest to allow binding and then moves to a different channel and starts imaging immediately, the exact start is known and defined to be the first frame.
Also added a private property to `KymoLine` to check if the ends are the first/last frame since this …
> Bugfix: ignore ambiguous dwelltimes in kymotracking binding time analysis

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
While working on analysis with kymos acquired under different pixel sizes, I noticed that sometimes the image in the kymotracker did not make any sense with the requested `axis_aspect_ratio` argument.  Finally I found that the aspect ratio was actually being calculated as `height/width` rather than `width/height`. This is fixed now, and a specific test added.
*In the following, the bug in the images aren't very apparent, but look at the printed values at the bottom of each figure*
Before:
After:
> Fix kymotracker aspect ratio bug

- contributing.md
We sometimes get questions from users how to contribute. Hopefully this will lower the bar a little bit for them to open an issue or even a PR.
I wasn't entirely sure whether this information was best suited to an readme style file, or in the documentation on readthedocs. I'm open to suggestions on that front.
I also wasn't sure what kind of detail to go in when writing the document. It may be useful for some users to include some fairly specific GH instructions like the ones here:
https://github.com/scikit-image/scikit-image/blob/main/CONTRIBUTING.rst#development-process
What do you think?
> docs: add contributing.md

- .github/workflows/pylake_test.yml
- docs/conf.py
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/requirements.txt
- docs/tutorial/force_calibration.rst
- lumicks/pylake/adjustments.py
**Why?**
We were getting build failures on RtD. See: http://github.com/readthedocs/readthedocs.org/issues/9037
That link actually mentions that we could have also solved it by pinning `jinja`. I did try this initially, but unfortunately, installing `pylake` afterwards bumps it again and makes the build fail. I figured it's a good idea to just update `sphinx` and get us up to date.
I also took the liberty of clearing out all the warnings Sphinx was producing. Reason being that  it's difficult to see real ones when they're drowned in noise.
Docs build can be found here: https://lumicks-pylake.readthedocs.io/en/update_sphinx/index.html
> docs: update sphinx

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels/test_channels.py
It's a small workflow improvement when dealing with slicing. With this improvement, properties that have a `start` and `stop` property can be used directly to slice data channels.
Before:
```python
f = lk.File("my_file.h5")
marker = f.markers["my_marker"]
f.force1x[marker.start : marker.stop]
```
After:
```python
f = lk.File("my_file.h5")
marker = f.markers["my_marker"]
f.force1x[marker]
```
Or:
```python
f = lk.File("my_file.h5")
f.force1x[f.markers["my_marker"]]
```
> channel: allow slicing by item with start and stop property

- changelog.md
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels/test_channels.py
A fairly frequent operation is to mask some `Slice` data. Currently, we always have to import `TimeSeries` manually and basically construct a new slice when we need to do this. Technically, there is no way for users to do this at the moment.
This PR introduces an extra option to the `__getitem__` dunder that allows slicing by a logical boolean numpy array.
(While working on implementing piezo tracking in Pylake, I encountered a few things that were missing from the `Slice` API. Rather than appending them on an already sizable PR, I've decided to spin them out and put them up for review separately).
Note: Currently, this doesn't accept a `List` of booleans.  We could consider extending the feature to also allow this.
> channel: mask slices

- lumicks/pylake/force_calibration/tests/conftest.py
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
This PR is intended to catch a few of the failure cases that we observe when applying the touchdown procedure.
It adds three things (images of the failure modes are shown below).
- It sets the minimum for the focal shift to `0.7` (valid focal shifts for our objectives are between `0.7` and `1.0`.
- It ensures that there is sufficient data to compute the focal shift. At least two periods of the interference pattern are required.
The reason is that despite the fit shown here looking very good, the computed focal shift is actually complete nonsense. The focal shift model is given as a background polynomial plus a sine wave contribution. When you have only a partial period of the sine wave, the polynomial simply captures all the data (resulting in a sine wave amplitude of zero and an …
> Catch some touchdown failure modes

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels/test_arithmetic.py
When adding a scalar value, subtracting a scalar value or negating a channel the force calibration is still valid and should be forwarded to the constructed `Slice`. This PR forwards the appropriate calibration items to the processed slice.
> channel: preserve calibration if valid

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/tests/test_alternate_diode_models.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
This is in preparation of the pre-characterized diodes. The plan is to measure both the diode frequency and relaxation factor for our diodes. This PR allows fixing either or both (previously one could only fix `f_diode`).
It also deduplicates some parameter descriptions by using the diode model the fixed model is derived from to obtain the parameter descriptions.
> force calibration: allowing fixing both diode frequency and relaxation factor

- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
**Why?**
It's more convenient to do this on the Pylake side than to make BL responsible for it.
As an additional benefit, this makes the downsampling more transparent to users wanting to reproduce their results.
> touchdown: make pylake responsible for downsampling

- docs/tutorial/file.rst
i noticed that the docs do not explain that channel data can be accessed as file[group name][channel name].
> docs: explain how to access channel data

- changelog.md
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
Because any modifications to `KymoLine` instances should be made via refinement methods or specifically allowed manual editing
This change is pulled out from #262, which is on hold pending validation of the algorithm
> make KymoLine immutable

- changelog.md
- lumicks/pylake/fitting/models.py
This allows the construction of models for ssDNA and dsDNA using initial guesses based on literature. These are based on the odijk and freely jointed chain implementations.
> fitting: Add ssDNA and dsDNA wrapper functions

- docs/install.rst
In a previous version of the installation instructions, we recommended windows users adding the kernel to the `kernelspec` manually, but without a specific name (which defaulted it to `python3`). This was a mistake, because it overrides the autodiscovery of the current environment's kernel that normally happens. As a result, some people are having issue with kernel discovery when installing Pylake (and likely Python in general).
Because of this, these amendments to our installation instructions.
I expanded a bit on the instructions pertaining to the `kernelspec` list (in the FAQ).
In addition, I also explicitly reference the FAQ (where these instructions can be found) because people often don't end up reading the FAQ when they run into issues after installation.
Docs …
> docs: kernelspec instructions

- changelog.md
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
We want to process the imaging metadata in a centralized place and expose only those fields that can be trusted.  This will help when we want to generate kymos from different sources for instance.
In the process of doing this I found a bug in the tiff export, which led to incorrect pixel times (so I took the liberty of fixing that up as well).
> confocal: remove direct dependence json

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
This PR adds some convenience when it comes to cropping and slicing stacks.
Notably, it allows one to directly use multidimensional indexing to select frames and crop the image. It also adds the ability to use negative indices to indicate "from end".
I also added a `.shape` property to quickly check the shape of a `CorrelatedStack`. Previously this required either collecting these pieces of information from various sources, or grabbing the entire stack's contents and calling `.shape` on it. This was very tedious and slow.
> stack: allow multidimensional indexing with `CorrelatedStack`

- changelog.md
- docs/refs.bib
- docs/tutorial/kymotracking.rst
- docs/tutorial/msdplot_100_lags.png
- docs/tutorial/msdplot_default_lags.png
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymoline.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
This PR addresses two user requests:
1. It adds an uncertainty estimate for the diffusion constant.
2. It exposes the number of lags used to estimate the diffusion constant.
Note that I added new API since the function now returns a dataclass. I've decided to do this because grouping this information together is useful and more extensible without breaking the API again.  Note that another PR for a second method is incoming. Giving it a `__float__` dunder method allows us to still use it conveniently with `numpy`, i.e.:
```python
np.array([kymoline.estimate_diffusion() for kymoline in kymolines], dtype=float)
```
> msd: add uncertainty estimate and estimation parameters to `msd` return argument

- changelog.md
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
For kymos generated from camera movies, per-pixel timestamps don't make much sense; however it would still be nice to know the start/stop timestamps for the frame integration. Additionally, a method to determine the kymo line ranges makes it simple to downsample channel data to the frequency of the lines; the functionality is similar to `Scan.frame_timestamp_ranges()`. I've kept it private for now, but it may be better as a public method.
I've implemented this as (yet another) factory because camera-based kymos will need a different implementation. Additionally, I've removed `Kymo._downsample_channel()` since that functionality is now achievable in 2 lines with this addition.
> Add `Kymo._line_timestamp_ranges()`

- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymoline.py
We should probably not use ill-posed data or API we deprecated in the tests. This cleans up two warnings that pop up during the tests.
> ci: clean up two warnings from the error log

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
This was user feedback from the training sessions. Users enter a diameter, therefore should be provided with an error message that relates to diameter for this particular criterion.
> calibration: express error in terms of diameter

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels/test_arithmetic.py
I noticed during documenting the piezo tracking functionality that currently, whenever we do arithmetic on a slice, we lose all the labels. This is not necessary. Quite a few operations (subtraction, addition, negation) will preserve the units and thereby the y label. Additionally, we can construct titles for these slices by using the existing title strings and adding the operator.
`(f.force1x - f.force2x).plot()` results in:
Before:
After:
While I'm not a huge fan of the brackets, they are needed to ensure correctness if users were to repeatedly apply operations on a slice.
> arithmetic: forward labels appropriately

- changelog.md
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/tests/test_fit.py
- lumicks/pylake/fitting/tests/test_model_composition.py
- lumicks/pylake/fitting/tests/test_pickling.py
Using `id(model)` to identify models within an `FdFit` is not a good approach, since this value is only preserved over its lifetime. One consequence of this is that `FdFit` can't be pickled (see: https://github.com/lumicks/pylake/issues/327). This PR switches to associating a uuid with a model which is then used to uniquely identify it.
> fitting: make `FdFit` 🥒-able

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/nb_widgets/image_editing.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
Creating kymos from image data opens up multiple possibilities including creating kymographs from `CorrelatedStack`s and exploring kymotracking on new types of image transformations (eg., edge detection).  Per-pixel timestamps are not supported, but the line time (frame integration time in the case of camera-based images) must be supplied. This way, these kymos can be used in most downstream analysis including kymotracking
> Create kymographs from image arrays

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
Missing channels in `scan.rgb_image` should be handled gracefully so that users still could see remaining channels.
> Handle missing channels in `scan.get_image("rgb")` gracefully

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
This PR takes all of the lists/dictionaries of values dealing with algorithm/slider parameters, ranges, descriptions, etc and centralizes everything into a small dataclass. Beyond data organization, this provides a template for future widgets that may implement other algorithms and allows for easy refactoring/de-duplication of the slider widget generation code.
The final commit makes the `algorithm_parameters` attribute private, which it likely should have been in the first place. Since we are on a breaking release, this is a good time to make the change.
This PR replaces #333 and #334.
Note: as `KymoWidgetGreedy.create_algorithm_sliders()` is now written generically we could easily move it directly into the parent class; however, we would lose the `NotImplementedError` …
> Alternative option for default Kymotracker parameters/ranges

- changelog.md
- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/force_calibration/touchdown.py
Considering that not all systems have the same acquisition rate, providing a default `sample_rate` is risky. For this reason, we refrain from providing a default now.
> Removing sample rate defaults

- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_file_download.py
- release.md
The ci tests for the download of files from Zenodo are brittle and fail when there is a timeout. This is annoying. I propose disabling these tests on ci, but adding a step to the release procedure to run them on demand.
> ci: exclude zenodo downloads from ci

- changelog.md
- docs/tutorial/images.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
We want to homogenize the API between `Scan` and `CorrelatedStack`. This PR spins out the video export and makes it work for both `CorrelatedStack` (dealing with TIFF images) and `Scan` (dealing with confocal scans). I've also taken the liberty to fix a bug in the video export and simplify the disabling of the alpha transparency.
I've manually tested it with cropping, color adjustment, tiff alignment on/off on rgb stacks, single color stacks and confocal stacks.
> correlatedstack: add video export analogous to `Scan`

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Most systems have aliasing suppression in hardware, but it is still good to have the option to take it into account in the model for alternative detection methods.
> force_calibration: add private API for taking aliasing into account

- changelog.md
- docs/tutorial/correlatedstacks.rst
- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
API uniformity basically. This way, it provides the exact same API as we have on `Scan` leading to fewer surprises for the user.
> correlated_stack: change `frame_timestamp_ranges` to method

- changelog.md
- lumicks/pylake/channel.py
Found a comment in the source code stating that `data` and `timestamps` should be lazily loaded and took this as an opportunity to implement it.
> Lazily load `TimeSeries` `data` and `timestamps`

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/tests/test_channels/test_channels.py
As a user I want to easily access the sample rate of `Continuous` and `TimeSeries` data.
`TimeSeries` data usually has a constant sample rate. The property `sample_rate` now returns the `sample_rate` if it is constant, or if not, returns `None`. If the sample rate is variable, the user needs to do something else.
Additionally, this PR fixes wrong sample rates returned for downsampled `Continuous` data (see tests).
> Same access of sample rate for `Continuous` and `TimeSeries` data

- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
We offer the functionality to crop `CorrelatedStacks`, this PR introduces the same behaviour for `Scans`.
One thing to note is that I had to overhaul the slicing by frame to achieve the correct behaviour. Reason being that the old slicing relied on always reconstructing the array. Slicing by frame resetting the crop seems unacceptable to me, as I could see that to be a regular use case (crop first, select frames later).
This comes at a penalty, namely that reconstruction takes place for the entire image array when selecting a range of frames, whereas before, if you sliced frames, you would only reconstruct what you use. In practice, I think for most use cases, the change is still warranted for two reasons:
1. I think it is rare that you know exactly which frames you want …
> Scan: support cropping.

- changelog.md
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
It homogenizes the API for tiff export between scan and confocal. It also removes some deprecated code.
I've also taken the liberty of enforcing keyword arguments for the more rarely used arguments of `export_tiff`. Reason being that they are not frequently used and have meanings which are difficult to glance from their values if used positionally. Also, more important arguments may be added in the future, and we might want to reserve earlier positions for those.
> Confocal / CorrelatedStack: make tiff export API more homogeneous

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
This PR is part of making `Scan`, `Kymo` and `CorrelatedStack` have similar properties. It's convenient to have a `shape` property.
Note that in the process of developing this feature I noticed two bugs that resulted in an error when downsampling or cropping by distance an image where some of the color channels were not defined. I fixed these and left the fixes as separate commits. If approved, I would keep those separate from the shape feature, but merge the two fixes together.
> Scan/Kymo: add shape property to `Scan` and `Kymo`.

- changelog.md
- lumicks/pylake/nb_widgets/range_selector.py
Aafke found that the range selector widget wasn't updating the plot anymore when the dataset was switched. This PR fixes that behaviour by adding a call to `draw_idle` analogously to https://github.com/lumicks/pylake/pull/337 .
> range_selector: force redraw on update

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
If the signal threshold value is set too low, the tracker will start to track noise which can results in upwards of thousands of lines. In the widget, this can appear as the widget hanging while the algorithm runs. This PR adds another label in which warnings can be displayed.
Things to note
- The cutoff value for "low threshold value" is not well known at the moment, but some tests on normal sized kymographs suggests this slowdown could appear at values corresponding to the 95th percentile of the data. However this value is likely variable based on SNR and kymo length/size. Other suggestions for cutoffs are welcome
- I used an `HTML` widget rather than the simple `Label` in order to be able to differentiate this warning label (with red font) from the existing status …
> Kymotracker: warn on low threshold value

- .github/workflows/pylake_test.py
- lumicks/pylake/nb_widgets/image_editing.py
We've been getting a warning from `mpl` for a while. Since it only involves a simple parameter rename, I figured it's fine to support both for a while. I added a comment so that we don't forget to remove it once we upgrade to `>= 3.5.0`.
I also took the liberty of adding `Werror` to our `pytest` script, so that warnings are treated as errors from now on. Hopefully this'll make us a bit more proactive about clearing these out.
> ci: clear warnings caused by `mpl` argument deprecation

- changelog.md
- lumicks/pylake/fitting/detail/model_implementation.py
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/fitting/tests/test_fd_models.py
- lumicks/pylake/fitting/tests/test_fit.py
- lumicks/pylake/fitting/tests/test_pickling.py
- lumicks/pylake/fitting/tests/test_profiles.py
When making profile likelihoods for models, the procedure could simply fail without a helpful error message.
When a model (for example the Odijk model) is profiled, its parameters are traversed up to the parameter bounds. In this case, that lower bound was zero for contour length, which is not a valid value for that model (it actually returns NaNs there).
There are multiple fixes in this:
- When NaNs are detected, the log likelihood function throws to signal to the user that this simulation cannot be trusted.
- The bounds for the models are updated to have a minimum value that is nonzero, to make sure the models don't break down.
- The profile likelihood method now deals gracefully with the cases where the model may suddenly stop simulating for some parameter values:
1. …
> fdfitting: better handling around valid model boundaries

- changelog.md
- lumicks/pylake/channel.py
- setup.py
The method `TimeSeries.from_dataset()` automatically loaded the data and timestamps from an HDF5 file upon creation of a `TimeSeries` instance. This is now avoided by creating the `TimeSeries` instance using the `h5py.Dataset.fields()` method of data and timestamps.
Just to add more information, how I realized this:
```
from lumicks import pylake as lk
filepath = "./data/Lakeview Showcase Data-20220616T152657Z-001/FD Curve_forw_DNA.h5"
file = lk.File(filepath)
a = file.h5["Distance"]["Distance 1"]["Value"]
b = file.h5["Distance"]["Distance 1"].fields("Value")
type(a), type(b)
```
The output of this is `(numpy.ndarray, h5py._hl.dataset.FieldsWrapper)`, so `a` is a numpy array directly loaded into memory, whereas `b` is a `FieldsWrapper`, enabling the lazy loading.
> channel: fixed `TimeSeries.from_dataset()` not lazy loading data

- changelog.md
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_algorithm_scaling.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Continuing with the terminology refactor. This PR tackles functions in `kymotracker.py` and some things in the widget to ensure the tests pass. There are some additional breaking changes that I've included since we're on one of those releases anyway and it cut down on some ugliness wrt argument order in the function signatures
- added defaults to the pixel threshold and track width args for `track_greedy`; this allowed for an aliasing/deprecation pathway for the former `line_width` argument
- `KymoWidget` and `KymoWidgetGreedy` now enforce keyworded arguments for everything beyond the first 2 (`kymo` and `channel`). Without this change, I would have had to put the new `track_width` parameter at the end of the constructor signature and would end up separated from the rest …
> "line" to "track" - part 2 / 3

- docs/_templates/class.rst
- docs/_templates/function.rst
- docs/api.rst
- docs/conf.py
- docs/requirements.txt
- lumicks/pylake/channel.py
There are a number of problems with how our API docs stubs are currently built. 
- Regardless of the `autodoc` settings to hide private methods, these still show up. This seems to be because we use `autosummary` to build the TOC
- The methods section for each page is just a table with the method name and first line of the docstring; the actual docstrings including parameters aren't shown anywhere. 
- Linking to specific methods of a documented class requires adding a separate entry in the TOC so that a specific stub will be built for that method (you can't link to a row in the methods table).
The only solution I could find was to write custom templates which directly use `autodoc` directives; the settings from `conf.py` then get applied correctly. I also had to switch …
> Fixup API docs

- docs/conf.py
- lumicks/pylake/adjustments.py
- lumicks/pylake/channel.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/fitting/detail/model_implementation.py
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/models.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
With the API docs becoming visible, so does a bunch of our sins against the format. I noticed that when building the docs on the napoleon branch that many of the docs were throwing warnings, so I took the liberty of fixing a lot of the small issues that were there.
Whenever relevant, I also improved small parts of docstrings to hopefully make them a bit more useful to users.
A few not so nice things to note:
- It seems that our current doc building system does not play nice when we use a deprecation notice on a function that has a list of parameters. For now, I have removed these (in two places), since people should be using the new API anyhow. I am open to suggestions on how to make it play nice however.
- Deprecation notice also don't play nice with functions that don't …
> docs: fixing docs build warnings

- .github/workflows/pylake_docs_test.yml
After the work that went into cleaning up the docs and making sure that everything works, it'd be nice to maintain them in good working order. Therefore I propose this CI test to make sure we don't end up with weird oddities on our API docs again. If it turns out to be too brittle we can remove it again, but I think we should give it a shot.
Example of what a CI run will look like if it fails (here I had deliberately broken a docstring):
Note that this PR depends on all the PRs that clear out the warnings we have now before it can be merged and turned into an active test.
> ci: test docs build

- changelog.md
- docs/tutorial/correlatedstacks.rst
- docs/tutorial/images.rst
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
It's very convenient to slice by time and timestamp, hence we want to extend this functionality to `Scan` and `Stack`.
> scans/stack: add slicing by timestamp and string

- changelog.md
- lumicks/pylake/benchmark.py
- lumicks/pylake/fitting/tests/test_fit.py
- lumicks/pylake/fitting/tests/test_profiles.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/nb_widgets/tests/test_correlated_plot.py
- lumicks/pylake/nb_widgets/tests/test_fd_selector.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/piezo_tracking/tests/test_baseline.py
- lumicks/pylake/piezo_tracking/tests/test_piezo_tracking.py
- lumicks/pylake/population/tests/test_mixture.py
- lumicks/pylake/tests/conftest.py
- lumicks/pylake/tests/test_channels/test_channels.py
- lumicks/pylake/tests/test_decorators.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_point_scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
We've been using the `cleanup` decorator from `matplotlib`, but it's [deprecated](https://github.com/matplotlib/matplotlib/pull/22697) now, so here is our own.
I also took the liberty of getting rid of a few deprecated API calls in the benchmark and adding a few `plt.close('all')` calls in a few of the tests, since auto-removal of overlapping axes is deprecated.
Longer term it might be nice to look into something such as [pytest-mpl](https://github.com/matplotlib/pytest-mpl). Maybe a fun friday afternoon project, but for now this at least gets us back up and running without using deprecated functionality.
> ci: don't use `cleanup` from the mpl testing decorators

- changelog.md
- docs/api.rst
- docs/examples/reca_fitting/reca_fitting.rst
- docs/examples/twlc_fitting/twlc_fitting.rst
- docs/tutorial/fdfitting.rst
- lumicks/pylake/benchmark.py
- lumicks/pylake/fitting/datasets.py
- lumicks/pylake/fitting/detail/model_implementation.py
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/models.py
- lumicks/pylake/fitting/parameter_trace.py
- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/fitting/tests/test_fd_models.py
- lumicks/pylake/fitting/tests/test_fit.py
- lumicks/pylake/fitting/tests/test_model_composition.py
- lumicks/pylake/fitting/tests/test_model_sim.py
- lumicks/pylake/fitting/tests/test_parameters.py
- lumicks/pylake/fitting/tests/test_pickling.py
- lumicks/pylake/fitting/tests/test_utilities.py
- lumicks/pylake/piezo_tracking/tests/conftest.py
**Why this PR**
As a user I want to have consistent naming of fitting models.
I renamed the public facing models as follows:
`inverted_marko_siggia_simplified` -> `wlc_marko_siggia_distance`
`marko_siggia_simplified` -> `wlc_marko_siggia_force`
`marko_siggia_ewlc_distance` -> `ewlc_marko_siggia_distance`
`marko_siggia_ewlc_force` -> `ewlc_marko_siggia_force`
`odijk` -> `ewlc_odijk_distance`
`inverted_odijk` -> `ewlc_odijk_force`
`freely_jointed_chain` -> `efjc_distance`
`inverted_freely_jointed_chain` -> `efjc_force`
`twistable_wlc` -> `twlc_distance`
`inverted_twistable_wlc` -> `twlc_force`
I refrained from simplifying `wlc_marko_siggia_*` to `wlc_*`, as I am unsure, if we should simplify the names already at this level and not only when we provide convenience functions to assemble a …
> Rename fdfit functions

- lumicks/pylake/fitting/fit.py
Unescaped `\` in latex markdown in some docstrings was causing warning -> error. Also took the opportunity to use the `\ln{}` latex operator instead of the `mathrm{ln}`
> Fixup unescaped backslash in docstrings

- changelog.md
- lumicks/pylake/benchmark.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/nb_widgets/image_editing.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
~As a developer I want `file` and `src` attributes of `Scan` and `CorrelatedStack` to be private, to protect them from users.
I renamed `.src` to `._src` and `._file` to `.__file`. I left the property `file` but renamed it to `_file`, as some of the code relies on the `ValueError` the property throws when there is no file stored in `.__file`.~
After reconsidering based on Joeps comment, the incentive changed:
As a developer I want `CorrelatedStack.src` to be private to protect it from the users.
I deprecated `CorrelatedStack.src`.
> Make attribute `src` private

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
Some downstream analyses on kymo tracks require information from the source `Kymo`  (`refine_tracks_centroid` and `refine_tracks_gaussian`). Until now we've assumed that all tracks have the same source instance and just used the first track in the group to get this information. Here we specifically enforce this so our assumptions are always valid.
In addition, I added properties to look up the source `Kymo` and color channel, and made some minor changes to downstream functions that ensure we're working on a `KymoTrackGroup` rather than a raw `list` or `tuple` of `KymoTrack`s
> Ensure same source data for all tracks in group

- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
While working on the PR for ensuring the same source kymo for a group, I noticed there are not tests for `_merge_tracks()` and it was not explicitly enforced that the two track instances were from the same group. Looking back, this functionality is actually tested in the widget tests, but I thought it would be good to have the smaller unit test here too.
> Add tests for `KymoTrackGroup._merge_tracks()`

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
I did this PR for a few reasons (found mostly while doing testing on the new msd methods):
- It's very convenient to be able to add `KymoTrackGroups` and to be able to add lines to one and getting a shallow copy of the group. Similarly, being able to add groups together is quite convenient when creating test data (which will come in handy when writing the theory section).
- There were some weird cornercases in `_extend`. Extending with an empty list produced an error because it doesn't have a Kymo and `_validate_single_source` fails.
- Analogously, extending with an incorrect datatype didn't manage to make it to the correct `TypeError` for the same reason.
> KymoTrackGroup: Add `+` operator

- changelog.md
- lumicks/pylake/conftest.py
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
- lumicks/pylake/tests/test_imaging_mixins.py
As a user, I want to have timestamps and metadata in TIFFs exported from Pylake (Confocal like WIT). As a developer I want to have common code in all different classes that handles exporting tiffs.
**Implementation details**
The new mixin class `TiffExport` implements the method `export_tiff()` to export tiff stacks. It uses the method `_tiff_frames()` to get frames to be written to a TIFF file. The method `_tiff_writer_kwargs()` generates the arguments used for the `TiffWriter.write()` method. The method  `_tiff_image_metadata()` generates the metadata to be written to the ImageDescription field of the exported tiff file pages and the method `_tiff_timestamp_ranges()` is used to generate a list of (start, stop) ranges, to set the (non standard) DateTime field for all …
> Unify `export_tiff` for `Scan`, `Kymo` and `CorrelatedStack` and export metadata in all cases

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
With an empty image, the threshold could be set to zero. It should at a minimum be `1`.
I noticed that the properties that depend on the `Kymo` were untested, so I added tests for these as well.
> kymotracker: ensure threshold default is never 0

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
We currently offer downsampling kymographs, but one can still compute diffusion constants from them. However, the assumptions that go into the method are then not met.
This PRs adds a  boolean property to a `Kymo` which indicates whether the Kymo is the result from downsampling. This boolean is checked before doing diffusion analysis.
*What to look out for?*
1. I chose not to disallow computing MSDs (since technically, they are just defined as they are; the assumptions come in once people start inferring things on them). I am on the fence whether we should issue a warning though.
2. I did not disallow dwelltime analyses because I think these are still valid. The downstream methods there just make use of the actually achieved minimum times, and therefore should be fine.
> diffusion: disallow estimating diffusion after downsampling

- changelog.md
- docs/refs.bib
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
This is the first part of some of the new diffusion estimation work. This implements the CVE method.
Benefits:
- Provides a really fast unbiased estimator that provides a better alternative to OLS/GLS for cases where the `SNR > 1`.
- Future extension is possible towards methods where we take into account the bias caused by substrate fluctuations (whether this is relevant for us is still T.B.D).
- Future extension to incorporating the static localization uncertainty obtained from Gaussian refinement is possible, this reduces the problem by one parameter and reduces spread of the diffusion estimates.
Below you see a figure where this method was using on a 50 point trace with 20 random points missing. The solid lines with the symbols represent the mean, while the lines …
> diffusion: implement the covariance based estimator for diffusion

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/population/dwelltime.py
`KymoTrackGroup.fit_binding_times(#)` did not filter tracks with only a single point. This leads to zero dwelltimes for those tracks and can lead to biased results since the dwell time isn't actually zero, just below the line time. Since the estimation procedure supports a minimum observation time, it is better to filter these.
I also fixed up a small docstring error in this PR.
> dwelltime: fix issue with single pixel detections

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
When using `KymoTrackGroup.estimate_diffusion()`, if any tracks are shorter than the required length (3 for `"cve"` or 5 for the others), an error would be thrown. Instead we want to gracefully handle this and discard tracks that do not meet the requirement and issue a warning to the user.
Here I add a `min_length` argument where the user can specify a length, or defaults to `None` in which the appropriate min is used based on the specified method. I also changed up the docstring to reference `KymoTrack.estimate_diffusion()` in order to properly document the updated call signature without duplicating (most of it).
Relevant docs changes are [here](https://lumicks-pylake.readthedocs.io/en/msd_checker/_api/lumicks.pylake.kymotracker.kymotrack.KymoTrackGroup.html#lumicks.pylak …
> Validate the lengths of tracks analyzed in `KymoTrackGroup.estimate_diffusion()`

- .github/CODEOWNERS
It's convenient to make sure that we always get at least one internal Pylake reviewer.
> ci: add pylake to code owners

- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
**Why**
While following and rewriting fixtures to test kymo slicing, I stumbled over a weird corner case when slicing Kymos:
**Explanation**
Slicing by providing only the start time with a value greater than the start timestamp of the very last line and less than or equal to the very last timestamp of the infowave created a dysfunctional Kymo. To fix it, the method to calculate the line timestamps in `Kymo.__getitem__()` was replaced with the method `Kymo.line_timestamp_ranges()`. Additionally, a check was introduced to ensure the stop timestamp of the kymo to have a value greater or equal to the stop timestamp of the last Kymo line, if the stop value of the slice item was greater than the start timestamp of the last Kymo line. As a bonus the old functions to calculate line and image …
> kymo: Fix erroneous slicing of kymos

- changelog.md
- lumicks/pylake/correlated_stack.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/plotting.py
- lumicks/pylake/detail/tests/test_plotting.py
- lumicks/pylake/kymo.py
- lumicks/pylake/point_scan.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_point_scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
**Why?**
As a user I want a sensible docstring for the `plot()` method of `CorrelatedStack`, `Kymo`, `Scan` and `PointScan`. Additionally, I would like to have a sensible and similar call signature for all `plot()` implementations.
This PR aligns the different plot functions and involves the following changes:
* A new module `plotting`, which provides common utility functions for plotting
* `Scan`, `Kymo` and `PointScan`: Made argument `channel` optional.
* `Scan`: Added argument `show_title`
* `Kymo`: Added arguments `image_handle` and `show_title`.
* `CorrelatedStack`: Reordered the keyword arguments and enforced all parameters after `axes` to be keyword arguments.
* The method call to `CorrelatedStack.plot()` has a decorater, which checks if the method was called with the deprecated …
> Common plot method call signature for `CorrelatedStack`, `Kymo`, `Scan` and `PointScan`

- changelog.md
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
In rare cases, it is possible that during the analytic fit, the diffusion constant returned is negative. This makes no sense as an initial guess and leads to numerical problems down the road. For this reason, an alternative method to guesstimate it is used when this occurs.
In addition, `a > 0` is not a strong enough condition for the fc estimator, because the square root operation can still produce an exception if `b < 0` while `a > 0`.
> calibration: fix analytic fit failing is `b < 0` and potentially returning `diff < 0`

- changelog.md
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
It's nice to know how long your kymograph is. This functionality was already nested inside `Kymo.plot()`, just pulled it out as a separate property. Also facilitates calculating average binding events per second after tracking: `len(tracks) / kymo.duration`
> Add `Kymo.duration` property

- docs/_static/custom.css
- docs/_static/pylake_syntax_theme.py
- docs/_templates/class.rst
- docs/_templates/function.rst
- docs/conf.py
I thought it would be nice to have a slightly customized theme that reflects the colors from the logo and fixes some other eyesores. Help a colorblind guy out and make as many suggestions as you want, important thing is we know how to do it now
[docs build](https://lumicks-pylake.readthedocs.io/en/pylake_theme/)
Some before & afters:
> Customize the docs theme with colors from Pylake logo

- .github/workflows/pylake_docs_test.yml
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- .github/workflows/pylake_test_no_notebook.yml
Adds environment variable to acknowledge that we want to use `platformdirs` to determine which paths to use. Basically they changed how the path lookup is done and added a deprecation warning to notify us about this. See https://github.com/jupyter/jupyter_core/pull/292 for more information.
> ci: use `platformdirs` for jupyter

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
On our current main, the widget renders vertically in Jupyter lab, while it should render horizontally. This makes it borderline unusable.
This PR fixes that by forcing a `show` on the plot before setting up the layout boxes.
A second thing I noticed is that our new labels are too long for the widgets. The most interesting part of the label ends up getting ellipsed out:
As a workaround, I played  bit with the styling, but the problem is that the margin between the slider and the edit part of the box is not configurable, so that leaves you with an annoyingly small slider:
Considering that we are a bit limited in how much screen space we have, I decided to shorten the label names instead.
This is what it looks like with the abridged names:
I also switched out the short form …
> nb_widgets: fix widget layout

- changelog.md
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
This functionality is provided so that we have a tried and tested method of computing a correctly weighted average diffusion.
If we don't, I fear people might just average the constants they get from `estimate_diffusion()` which can lead to suboptimal results.
To test the method, I've done some bootstrapping. Below are the results. The diffusion constant was set to a range of values (according to `(snr * noise)**2 / dt)` to simulate various levels of SNR. The noise level was kept fixed to `0.1`. I then simulate `M` "datasets" of `R` tracks. On every set of tracks I apply the methods. At the end, the ensemble method gives me an estimate and an estimate for the standard error. I aggregate these standard errors for realisations to see if there's a bias in them. I do this by …
> diffusion: add option to compute ensemble cve

- changelog.md
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/mixture.py
- lumicks/pylake/population/tests/test_dwelltimes.py
- lumicks/pylake/population/tests/test_mixture.py
We have two main functionalities currently in the `population` module: Gaussian mixture models and Dwell-time analysis. This feature allows for the results from the first to be used as input to the second. Specifically, channel data can be fit with the GMM and a labeled state-path extracted. This state-path is converted into lists of dwell-times for each state and these can then be fit with the exponential distribution.
While I was working on the tutorial update I noticed the need for this feature. So there are no docs updates here; a second PR with those changes will follow shortly
It might also be useful to have some classmethod on `DwelltimeModel` to read in state-paths directly
> Dwell-times from Gaussian Mixture Models

- changelog.md
- docs/_templates/instance.rst
- docs/api.rst
- docs/tutorial/correlatedstacks.rst
- docs/tutorial/images.rst
- docs/tutorial/kymographs.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/adjustments.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
Our current default `blue` colormap is basically unreadable (pure blue on black). Here we define `cyan`, `yellow`, and `magenta` colormaps and expose the dictionary through the `lk.colormaps` dictionary. You can use them like:
```
kymo.plot(channel="blue", cmap=lk.colormaps.cyan)
```
While a simple feature there are a couple of things I'm unsure about and would like some input:
- what do we think about the simple name `colormaps`
- ~~do we want this to be immutable? right now it's a normal `dict` so users can mess with it, but making it immutable would require something custom. Not sure if it's worth the effort~~
- forgot about `namedtuple`. overall I like this because it's immutable and personally I enjoy the dot notation better than `dict` keys. The one thing I'm not …
> Add `pylake` custom colormaps for single color images

- changelog.md
- docs/api.rst
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
The localization variance `sigma**2` is a good quantity to know as it can be used to determine the diffusive SNR (defined as `sqrt(D dt / sigma**2)`).
I noticed in writing the theory section for diffusive analysis that it was missing and I needed it.
Given that we basically do the work anyway, I figured I would add it as a public attribute of the estimate.
I decided to go with variance instead of the standard deviation since: 
a. This is what we actually calculate.
b. Estimate can go negative; and negatives should not be discarded or invalid to avoid biases when calculating population averages).
c. Variances are additive and there is less risk of user error if they get something they can safely average.
Here are some estimates for some real diffusive data (albeit a pretty …
> diffusion: expose localization variance

- lumicks/pylake/conftest.py
We're getting some deprecation warnings when importing `ipywidgets`. Considering it happens [immediately](https://github.com/lumicks/pylake/actions/runs/3649212314/jobs/6171492363#step:5:166) on `import`, I don't think it's anything specifc that we do, so for now, I've added them to our ignore list.
> ci: suppress ipywidgets deprecation warnings

- changelog.md
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
Because we're leaving some precision on the table right now when it comes to CVE-based diffusion estimates.
When calculating per track diffusion constants, the estimator variances can be quite large. In the case where all the diffusion constants are the same, we can determine an ensemble estimate which often has a higher precision simply owing to the fact that more data goes into this estimate. This comes at the cost of being able to determine individual diffusion constants for separate tracks however.
For CVE specifically, the ensemble estimate provides a good estimate of the localization variance and the variance of that estimator. We can use this estimate when computing per track diffusion estimates to reduce the number of parameters that we are forced to …
> cve: allow passing in localization variance

- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
We don't want our video export to include things from previous plots.
```python
plt.figure()
plt.plot([1, 2, 3], [1, 2, 3])
f = lk.File("C:\\Dev\\AVI rendering\\20190828-105121 Scan DNA1_CII_incubate_2min.h5")
cs = f.scans.popitem()[1]
cs.export_video("rgb", "d:\\new.gif")
```
Old behaviour:
New behaviour:
> kymo/stack: make new plot for video export

- changelog.md
- lumicks/pylake/kymo.py
It's a ~~rotate~~ translate!
Before:
After:
> kymo: fix alignment `Kymo.plot_with_position_histogram()`

- lumicks/pylake/tests/test_imaging_mixins.py
**Why?**
Numpy >= 1.24 raises a `RuntimeWarning` during casting if an floating point error occurs: 
https://github.com/numpy/numpy/releases/tag/v1.24.0
https://github.com/numpy/numpy/pull/21437
This causes `test_imaging_mixins` to fail:
The affected funtion is `TiffExport.export_tiff()`
**Solution**
Ignore the warning in the tests.
> test_imaging_mixins: ignore RuntimeWarning raised by numpy >= 1.24

- changelog.md
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
This method provides an appropriate solution for estimating a diffusion constant when we have a large number of relatively short tracks with low SNR.
Graph with the obtained standard error vs number of included points. Shown here is the standard deviation of `5000` runs of `30` tracks with `25` steps each. Dashed line indicates the recommended number of lags suggested by the OLS method.
Graph with the obtained standard error vs number of included points. Shown here is the standard deviation of `100` runs of `20` tracks with `15` steps each. Dashed line indicates the recommended number of lags suggested by the OLS method.
Very long tracks but with a very poor SNR (leading to many lags being required). Here `steps=150` and `num_tracks=20`.
What is seen in this images is …
> diffusion: Add ensemble OLS method.

- changelog.md
- docs/tutorial/population_dynamics.rst
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
Originally the issue was opened because trying to plot a bootstrap before sampling raised a cryptic exception. While figuring out how to best deal with this, I noticed some other things that could be improved
- would be better to just get rid of the `DwelltimeModel.bootstrap` attribute altogether to remove statefulness. Here I changed it to a property with a deprecation warning.
- also deprecated `DwelltimeBootstrap.plot()` and renamed to `DwelltimeBootstrap.hist()` in line with `DwelltimeModel`
- made `DwelltimeBootstrap` a frozen data class and added an `extend()` method to append new samples to the distribution. Again trying to get away from statefullness
- now trying to access `DwelltimeModel.bootstrap` before calling `DwelltimeModel.calculate_bootstrap()` raises a …
> Fix some issues with dwelltime bootstrapping

- changelog.md
- lumicks/pylake/fitting/detail/model_implementation.py
- lumicks/pylake/fitting/models.py
This PR fixes three (small) things.
1. The F-d fitter uses the docstring provided in the implementation of the F-d model as `__repr_html__`. Some of these models had no description and therefore no description was provided to the user. This is fixed now.
I considered defining the docstring in the implementation only and reading that docstring from the API side (in `models.py`) but after doing so felt that the added complexity was not really warranted to deduplicate the sections that could be deduplicated. Reason being that for the render in the Jupyter `__repr_html__`, one usually wants to use `$a$` since it renders nicely; while in the docstring for the API side, one wants :math:`a` since that formats correctly to the online documentation.
2. The criterion for the …
> fdfitter: improve docstrings for fd models

- .flake8
- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/tests/test_imaging_mixins.py
Fixed bug which occurred when exporting images to TIFF files of a numerical type with insufficient range for the data with the flag `clip=True`. Prior to this change, values exceeding the range of the numerical type were not clearly defined. After this change values below and above the supported range are clipped to the lowest or highest value of the data type respectively.
I also added some data validation to the test (reading in the TIFF file whether it is actually what we think it should be).
> export_tiff: fix bug when exporting with `clip=True`

- docs/_ext/nbexport.py
As a developer I want to include images in the notebooks that can be exported from the docs.
Additionally, I also want `notes` and `warnings` to be (properly) displayed in the exported notebooks.
* Upon writing the docs one can mark images to be attached to and embedded in the exported notebook with the option `:nbattach:`
* Notes in the notebook are now rendered with a blue box, and warnings are included and rendered with a red box
To see how the notebook looks with the modified `nbexport`, see the following Example:
```rst
.. warning::
This is alpha functionality. While usable, this has not yet been tested in a large
number of different scenarios. The API may also still be subject to change.
New NBExport funtionality
=========================
.. only:: html
:nbexport:`Download this page …
```
> docs: nbexport: Add support to embed images in markdown cells.

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
It's minor, but it's kind of annoying that when you plot with a label, you explicitly get the edge label for free.
> kymotrack: block label for edges

- changelog.md
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
While testing some other things, I noticed that only up to 2 components are shown for the histogram even if the model components > 2. Also changed so we use the estimated parameter rather than the mean of the bootstrap distribution to mark the plots
> Fixup DwelltimeBootstrap histograms

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_convenience.py
For end users, it can be beneficial to be able to just pickle things without having to think about it.
Without this change, the `CalibrationResults` structure cannot be pickled because of the locally defined lambdas for the upper bounds.
Yes, defining a function `_one` that does nothing but return `1.0` also irks me. I considered making it a static method, but it felt like polluting the class.
> calibration: allow calibration class to be pickled

- docs/conf.py
It's nice to have the links in the notebooks actually lead to the documentation online.
It took me a bit to find how to poll the URL the docs end up at. But you can find how the URL is composed from the root and `<lang>/<version>` tags [here](https://docs.readthedocs.io/en/stable/glossary.html#term-root-URL) and how to get the version from the environment variables [here](https://docs.readthedocs.io/en/stable/environment-variables.html#envvar-READTHEDOCS_VERSION). For local builds, this environment variable does not exist and we just point to `stable`.
Docs build where you can download a Jupyter notebook [here](https://lumicks-pylake.readthedocs.io/en/api_links/theory/diffusion/diffusion.html) and one with a more extreme branch name (to test name mangling by RtD) …
> docs: fix docs links from notebook

- lumicks/pylake/kymotracker/detail/msd_estimation.py
It's very minor, but in most cases where we just `.plot()` a single thing we simply forward the `**kwargs`. I found myself essentially remaking this `plot()` function because it wasn't there. Figured I'd better just do the fixup at the source.
> ensemble_msd: forward  kwargs  in `EnsembleMSD.plot()`

- changelog.md
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
While performing an analysis in preparation of the new bias corrected centroid method, I noticed that the track width rounding is inconsistent.
Track width should always be rounded upwards to an odd number of pixels (since there needs to be a defined center pixel for the centroid refinement to work). We were rounding upwards too quickly, meaning that we typically took windows that are bigger than requested. Selecting a window that's exactly 3 pixels big, would give you a window of 5. I also noticed that we were calculating these `half_kernel` sizes in multiple places, so I spun it out to a separate private function.
While doing this, I noticed that once you correct the windows it becomes apparent that you could set windows that were smaller than three pixels (for which …
> kymotracking: fix window rounding

- changelog.md
- lumicks/pylake/__about__.py
Improvements were made. Would be nice to get these to our users.
Note that the changelog links will be dead until the version is actually released. If you want to see what they link to replace `v0.13.3` with `latest`.
Preflight check:
> release: release Pylake v0.13.3

- changelog.md
- lumicks/pylake/file.py
- lumicks/pylake/note.py
- lumicks/pylake/tests/data/mock_file.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_file/test_file_items.py
Notes can be added as timeline events in Bluelake but currently, there is no easy way to load them back in `pylake`, this adds the API which is similar to the marker one.
> file: add API for note items

- changelog.md
- docs/api.rst
- docs/tutorial/imagestack.rst
- docs/tutorial/kymographs.rst
- docs/tutorial/scans.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/detail/tests/test_plotting.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/point_scan.py
- lumicks/pylake/scalebar.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_scalebar.py
This request came up multiple times during the user sessions.
I figured I'd play a bit with `AnchoredOffsetBox` on a friday afternoon, and it allowed this to be rolled into a feature relatively painlessly. Because we just use `matplotlib` API, it plays nicely with interactive widgets:
Plays nicely with movie export:
And it seems pretty easy to use. Note that adding a scale bar to `plot_correlated` is not yet supported, but it may be added in the future.
Also note that I went relatively minimal on the addition to the docs (since it's so similar to `ColorAdjustment` and the docstring for the function itself contains examples). Also note that `ImageStack` is essentially uncalibrated. I left a little `TODO` there to make sure that we update that once we add the relevant …
> plotting: allow users to add a scale bar to their plots if they want

- changelog.md
- lumicks/pylake/fitting/datasets.py
- lumicks/pylake/fitting/detail/link_functions.py
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/parameter_trace.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/fitting/tests/test_condition_handling.py
- lumicks/pylake/fitting/tests/test_fit.py
- lumicks/pylake/fitting/tests/test_model_composition.py
- lumicks/pylake/fitting/tests/test_parameter_inversion.py
- lumicks/pylake/fitting/tests/test_profiles.py
- lumicks/pylake/fitting/tests/test_stepping.py
Inspired by @alessiamarcolini comment on [this PR](https://github.com/lumicks/pylake/pull/452), I decided to remove all the `assert`-based input validation we are doing since these can easily be disabled in production and generally a well named exception is more informative. These only cover issues that were improper behaviour before, so it shouldn't affect anyone that was using the API correctly; but the changes are technically breaking, so it's a good idea to do it before `1.0`.
This is PR 1 of N with changes pertaining to this. I tried to keep the commits small to make it easier to review, but I will squash it down a bit before merging.
I did a few drive-by fixups on some docstrings as well, but that's not the main focus of this PR.
I also noticed that in some cases, we weren't testing …
> fdfitting: replace assertions with exceptions (part 1)

- changelog.md
- docs/api.rst
- docs/tutorial/fdcurves.rst
- lumicks/pylake/channel.py
- lumicks/pylake/detail/alignment.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/detail/plotting.py
- lumicks/pylake/detail/tests/test_plotting.py
- lumicks/pylake/detail/tests/test_widefield.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/fdensemble.py
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/nb_widgets/tests/test_correlated_plot.py
- lumicks/pylake/tests/test_channels/test_channels.py
- lumicks/pylake/tests/test_fdensemble.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Inspired by @alessiamarcolini comment on [this PR](https://github.com/lumicks/pylake/pull/452), I decided to remove all the `assert`-based input validation we are doing since these can easily be disabled in production and generally a well named exception is more informative. These only cover issues that were improper behaviour before, so it shouldn't affect anyone that was using the API correctly; but the changes are technically breaking, so it's a good idea to do it before `1.0`.
This is PR 2 of N with changes pertaining to this. While the first one is very specific for `FdFitting`, this one is a bit more of a hodgepodge. I tried to keep the commits small to make it easier to review, but I will squash it down a bit before merging.
I did a few drive-by fixups on some docstrings as well, …
> other: assertions to exceptions (part 2)

- changelog.md
- docs/refs.bib
- docs/tutorial/kymotracking.rst
- docs/zrefs.rst
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
Subpixel estimates can be very biased when using a simple centroid estimator when there is appreciable background. The reason is that the subpixel deviation is normalized by the total intensity over area used for the estimate. When the background is high, this results in a contraction of the subpixel correction towards the center.
**How to review this PR?**
I recommend going commit by commit. In the first few commits, I set up the algorithm in pure Python.  The beforelast commit vectorizes the algorithm. This makes it a bit trickier to read, but the performance gains are worthwhile.
**Description**
This PR is an implementation of [this ](https://opg.optica.org/oe/fulltext.cfm?uri=oe-16-18-14064&id=171315) paper. In a nutshell, the paper shows that under mild assumptions …
> kymotracking: add bias reduction step into the centroid estimator

- changelog.md
- lumicks/pylake/kymotracker/detail/trace_line_2d.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_image_sampling.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_lines_algorithm.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/kymotracker/tests/test_stitching.py
*Why this PR?*
This PR fixes a number of bugs present in `track_lines`.
Note, this PR builds on top of https://github.com/lumicks/pylake/pull/452 since it needs the bias corrected refinement.
1. `track_lines` typically returned one more track than requested.
2. `track_lines` could return non-integer time indices, which made very little sense (since they were x-coordinates along the image axis, rather than actual acquisition time points). It could also return _multiple_ points per kymograph line.
3. Because `track_lines` really looked for line structures rather than act tailored to kymographs, the endpoints were pretty arbitrary. Reason being that if a line moves downward near the end, you just get the last point on the line-like structure, even though you should get a point around the …
> track_lines: two bug fixes and an improvement

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
User feedback indicated that the line removal logic of removing a track when only a subsection of a track fell in the rectangle selector was cumbersome when lines are in close proximity. This PR changes that requirement to enforcing that the entire track needs to fall in the selector to be removed. Note that for retracking the old behaviour is maintained (intentionally).
Old behavior:
New behavior:
> tracking: only remove tracks fully in the selector

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
It adds some small convenience features.
- It allows a `KymoTrack` to be removed from the group with `.remove()`.
- It allows `KymoTrackGroup` to be indexed with a boolean array. This can be convenient when one wants to remove a whole bunch of elements at the same time.
- It removes `_concatenate_tracks`, which was unused internal api.
- Added private API for looking up a particular track in the group by it's python `id`.
Relevant section of the docs build [here](https://lumicks-pylake.readthedocs.io/en/no_track_uuids/_api/lumicks.pylake.kymotracker.kymotrack.KymoTrackGroup.html#lumicks.pylake.kymotracker.kymotrack.KymoTrackGroup)
> `KymoTrackGroup`: more options for finding and removing tracks

- docs/install.rst
Based on feedback we found that people tend to read over the reference to the FAQ at the end of the installation instructions. So now, it's presented at the top, in a little warning box up front.
We also explicitly instruct users to install a specific version of conda on windows to work around the OpenSSL issue.
Docs build here: https://lumicks-pylake.readthedocs.io/en/installation_warning/install.html#installation
> docs: refer to the faq earlier

- docs/_static/custom.css
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/mixture.py
I noticed there was an error in the `Return` section `GaussianMixtureModel.extract_dwell_times()`. I also took the opportunity to make some other general improvements to the other docstrings for the class
[Docs build here](https://lumicks-pylake.readthedocs.io/en/docstring_oops/_api/lumicks.pylake.GaussianMixtureModel.html#lumicks.pylake.GaussianMixtureModel)
> Fixup GMM documentation

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
While working on the calibration docs, I noticed the docstrings for these classes and methods were quite spartan.
I added some links to the relevant docs and examples to all of them.
Note that for the class docstring I have removed some of the documented attributes in favor of showing all parameters required for the constructor and only showing those attributes that the user might want to look at in a practical scenario (the ones that are actually computed from their inputs).
Also note that I repeat some of the exception names a few times because otherwise it didn't format correctly in the RST.
[Old](https://lumicks-pylake.readthedocs.io/en/latest/_api/lumicks.pylake.calibrate_force.html#lumicks.pylake.calibrate_force) …
> force calibration: improve docstrings

- docs/tutorial/figures/kymotracking/centroid_refinement.png
- docs/tutorial/figures/kymotracking/gaussian_refined.png
- docs/tutorial/figures/kymotracking/gaussian_refined_offset.png
- docs/tutorial/figures/kymotracking/kymo_bind_histogram_1.png
- docs/tutorial/figures/kymotracking/kymo_bind_histogram_2.png
- docs/tutorial/figures/kymotracking/kymo_bind_histogram_3.png
- docs/tutorial/figures/kymotracking/longest_track.png
- docs/tutorial/figures/kymotracking/tracking_overlay.png
- docs/tutorial/figures/kymotracking/tracking_overlay_custom_args.png
- docs/tutorial/kymotracking.rst
While testing enforced keyword arguments for kymotracking, I noticed there were some sections in the tutorial that were either broken or slightly changed results (after merging the default bias correction PR I think)
[docs build here](https://lumicks-pylake.readthedocs.io/en/kymotracking_docs_fixup/tutorial/kymotracking.html)
> Update Kymotracking tutorial

- docs/install.rst
It seems that there are issues (see this open issue https://github.com/jupyter/notebook/issues/6721) between the latest version of jupyter `notebook` and the jupyter kernel.
This causes problems with the communication between the jupyter kernel and notebook.
To reproduce this problem, simply install the latest `notebook` and `matplotlib` from `conda-forge`. Enable the interactive mode with `%matplotlib notebook` and create a few plots. Note that the problem doesn't always occur immediately, but starts to happen after some time (in my tests, 5 or 6 plots usually does it).
I suggest adding this to the installation instructions **temporarily**, which instructs users to select an older version of the `jupyter_client` (which seemed to fix the problem on `windows` at least). It …
> docs: add specific jupyter client to instructions

- changelog.md
- docs/tutorial/figures/imagestack/imagestack_adjust_absolute.png
- docs/tutorial/figures/imagestack/imagestack_adjust_percentile.png
- docs/tutorial/figures/imagestack/imagestack_correlated.png
- docs/tutorial/figures/imagestack/imagestack_cropped.png
- docs/tutorial/figures/imagestack/imagestack_kymo.png
- docs/tutorial/figures/imagestack/imagestack_red.png
- docs/tutorial/figures/imagestack/imagestack_red_cropped.png
- docs/tutorial/figures/imagestack/imagestack_tether.png
- docs/tutorial/imagestack.rst
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo_from_array.py
It's valuable for users to be able to generate `Kymos` from their camera stacks.
Turns this:
Into this:
Doing nothing more than this:
```python
stack_tether = stack.define_tether((6.94423, 4.22381), (20.47474,  4.08063))
kymograph = stack_tether.to_kymo(adjacent_lines=5)
```
This requires a re-assessment on how we treat motion blur, as camera images typically have far more motion blur, resulting in biased estimates if not correctly taken into account during specific downstream analyses (such as diffusion estimation using `cve`).
This PR introduces a new property on the `Kymo` which keeps track of this motion blur constant.
- For camera's computing the motion blur is relatively straightforward. It should simply be `(1/6) * exposure / line_time`.
- For `Kymo`'s generated …
> `ImageStack` -> `Kymo`

- changelog.md
Fixed up the release notes. Tested all the links before converting them from `latest` to `1.0.0`.
Docs build here (note that the links are dead because `v1.0.0` does not exist yet): https://lumicks-pylake.readthedocs.io/en/release_notes/changelog.html
> Release notes for Pylake v1.0.0

- docs/tutorial/figures/force_calibration/fast_sensors.png
- docs/tutorial/force_calibration.rst
This PR fixes a mislabeling in a figure title in the force calibration tutorial.
Credit goes to Michael B. for noticing this.
> docs: fix mislabeling in figure title

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/test_imaging_confocal/test_confocal.py
This PR fixes a bug that could lead to mutability of `Kymo` and `Scan` through references returned from `.get_image()` or `.timestamps`.
This bug was introduced in https://github.com/lumicks/pylake/pull/82 and released as part of `0.7.2`. Grabbing a single color image from a `Scan` or `Kymo` using `.get_image()` resulted in a reference to an internal image cache being returned.
Note: I kept the regression test separate so you can verify that it works, but I will squash it before merging.
> confocal: ensure immutability

- lumicks/pylake/detail/confocal.py
The current docstring of `ConfocalImage.fast_axis` states that `"""The axis that was scanned (x or y)"""`. It was unclear to me that this meant that the literal characters 'x' or 'y' were returned. I therefore propose to change the docstring to `"""The axis that was scanned ("X" or "Y")"""`, to indicate that the returned value is a string, and to make it explicit that the uppercase value is returned.
> docs: improve docstring for ConfocalImage.fast_axis

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/test_imaging_confocal/test_confocal.py
**Why this PR?***
This is a fixup on https://github.com/lumicks/pylake/pull/483/commits/f553a95283321d51e22080bff37bdf11d089ff1b which made sure that users could not modify the internal cache by returning a copy every time. Unfortunately, this leads to questionable performance for things such as `KymotrackGroup.plot()`. Instead, it's better to just be explicit about our intent and return it as a non-writeable array and leave it up to the user whether they want a copy that they can modify or not.
Technically, this is breaking, but considering that we never intended users to modify the internal cache, I would sooner refer to the original behaviour as a bug.
> confocal: non-writeable `.get_image()`, `.timestamps`

- changelog.md
- docs/api.rst
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/tutorial/fdcurves.rst
- docs/tutorial/kymotracking.rst
- lumicks/pylake/fdcurve.py
- lumicks/pylake/file_download.py
- lumicks/pylake/fitting/models.py
I was preparing to update the notebooks we have on Harbor to not use deprecated API. I noticed a few small errors in the deprecation warning and added some crosslinking in the kymotracking such that the notebook doesn't have to duplicate the entire algorithm description.
I also added a small commit which adds some more descriptions as to what is in an `FdCurve` as per customer request.
Docs build here: https://lumicks-pylake.readthedocs.io/en/minor_fixups/
> tutorial notebooks: minor fixes

- docs/theory/force_calibration/figures/back_focal.png
- docs/theory/force_calibration/figures/freq_dependence_near.png
- docs/theory/force_calibration/figures/freq_dependent_drag_zero.png
- docs/theory/force_calibration/force_calibration.rst
These improvements to the docs were made based on feedback.
The aim is three-fold:
1. To make the connection between te diffusion equation and the full optical trap calibration equation a little bit more clear. Before, it appeared as though the drag only appeared once we got to the trapping part (but it was always there in the diffusion equation).
2. To provide some guidance on the direction of the biases when you average too little, or use an unsuitable model.
3. To sketch the calibration setup a little bit, showing a schematic of where the force/displacement detection is taking place.
Docs build: https://lumicks-pylake.readthedocs.io/en/fixup_force_calib_docs/theory/force_calibration/force_calibration.html
> docs: improve force calibration docs

- changelog.md
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
This PR is number three in a story where we introduce more reliable uncertainty estimation.
This PR in particular provides three small improvements which we need to have things running smoothly:
- It provides the analytical gradient for the dwell time model. This improves performance when fitting dwelltime models. The performance improvement is typically a factor two or more).
- It adds a bound constraint on the estimated parameters to avoid numerical issues that occur when amplitudes or lifetimes go to zero.
- Finally, it suppresses a warning which is annoying to users and warns about something that doesn't impact the problem we are solving in a meaningful way.
One thing that might be worth noting prior to review is that I did notice all the reciprocals appearing in the …
> dwelltime: Improve numerics dwell time analysis

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_image_sampling.py
This PR fixes a bug that would round the center of the window to the incorrect pixel when using `KymoTrack.sample_from_image()`. Coming from the kymotracker, pixel coordinates are defined with their origin at the center of the pixel, whereas this function incorrectly assumed that the origin was on the left side of the pixel. The relative effect of this bug is larger for small windows.
Note that I use `int(x + 0.5)` rather than `int(round(x))` because I figured it'd make more sense to round consistent to slicing (define a pixel from `x - 0.5` up to (but not including) `x + 0.5`), whereas `round` uses banker's rounding (rounds to nearest even). In real-world situations this likely makes very little difference for us.
I realized that this bug was present while working on …
> `sample_from_image`: fix rounding issue

- changelog.md
- lumicks/pylake/tests/data/mock_widefield.py
We don't need to store the `SampleFormat` (which conveys the `datatype`) ourselves.
`tifffile` already infers this from the `numpy` `dtype` and sets this themselves in write [here](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L2726)
It used to ignore it if it was already there, but in the most recent version it produces a [warning](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L118). These warnings were visible when running the benchmark:
```
<tifffile.TiffWriter 'bench_tiff.tiff'> not writing extratag 339
<tifffile.TiffWriter 'bench_tiff.tiff'> not writing extratag 339
<tifffile.TiffWriter 'bench_tiff.tiff'> not writing extratag 339
```
> mock_confocal: don't explicitly write SampleFormat.

- changelog.md
- lumicks/pylake/kymotracker/detail/localization_models.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_loc_models.py
- lumicks/pylake/nb_widgets/detail/mouse.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/nb_widgets/tests/test_mouse.py
Nothing too exciting, but requested more than once, this PR adds a split action to the kymotracker.
Note that I piggybacked a few improvements for the localization data on this PR, which allows us to not lose the Gaussian refinement metadata if it exists.
> kymotracker: add `split` action

- lumicks/pylake/tests/data/mock_file.py
One project uses unit tests. One of the tests uses the class `MockDataFile_v2` from Pylake. To ensure the corresponding team will be aware of future changes of `MockDataFile_v2`, I added a comment to this class mentioning the external usage.
> mock_file: Add comment that `MockDataFile_v2` is an external dependency

- changelog.md
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
- lumicks/pylake/simulation/tests/test_diffusion.py
Enables global analysis across multiple kymos for various downstream analyses. The idea is that each kymo can be tracked separately and then you add all of the resulting groups together. This gives a single interface for downstream analyses regardless of single or multiple kymos tracked.
**Notes**
- Ensemble diffusion enabled for `cve` under all cases
- Ensemble diffusion for `ols` and ensemble MSD checks first if all line times and pixel sizes of the source kymos are the same; otherwise throw
- Exporting to CSV and flipping disabled for more than one source kymo
- Certain features currently raise `NotImplementedError` with this PR; will be implemented next in separate PRs
- refinement algorithms (centroid and gaussian)
- idea is to break combined group into single source …
> Enable `KymoTrackGroup` with multiple source `Kymo`s

- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
Found this plotting bug while working on the generalization of dwelltime analysis.
Not sure how this happened or why it wasn't covered, but luckily it was caught before this feature was ever released. Added a test so that this case is covered as well.
I left the test and fix as separate commits so you can verify that it does indeed hit the bug. I'll squash them down to one commit before merging.
> profile_likelihood: make sure plots work in the `n_components=1` case

- changelog.md
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
This model forms the backend for the dwell time analysis on a `KymoLineGroup`.
To enable global analysis, we need to take into account that observations coming from different kymographs may have had different support (different range of possible observation times). For example, the minimum observable dwelltime depends on the line time of a kymograph.
One thing that's unexpectedly a little tricky is how to handle plotting. When dealing with two different observation limits, it is entirely possible that one covers a bin only partially. This means that we have to take into account both the weighting inside the pdf, but also the effect discretization has on the model.
Not taking the partial bin effect into account:
Taking both into account:
If you discretize less, you can see …
> dwelltime analysis: enabling per observation pdf support limits for the `DwelltimeModel`

- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
The generalization of dwell time analysis to using multiple minimum and maximum observation times introduced in [this](https://github.com/lumicks/pylake/pull/501) PR was meant to support global analysis on `KymoTrackGroup`s containing lines originating from multiple kymographs. This PR hooks up these two.
> kymotrackgroup: multi-kymo dwell time analysis

- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
Because we want to be able to refine no matter what.
Basically I implemented a kind of recursion where if you have multiple source kymographs, you split into groups with a single source, refine, then reconstruct to the original group order.
> Refinement for multiple source kymos

- docs/requirements.txt
Was working on some docs. Noticed they weren't building on 3.11.
Bumping the `bibtex` requirement is needed to support building docs on Python 3.11. See this issue: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/284
> docs: bump bibtex requirement

- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
For now we're going to specifically disallow plotting binding profiles for `KymoTrackGroup`s that have more than one source kymo. The usefulness of such a plot is questionable and there are a ton of corner cases that could cause problems and/or could be dealt with in multiple ways (none of which are ideal). We can revisit in the future depending on user feedback
> Finalize global binding profile

- changelog.md
- lumicks/pylake/fitting/models.py
- lumicks/pylake/fitting/tests/test_fd_models.py
One of the API calls returns an incorrect model. This bug was introduced in Pylake v0.13.2 ( https://github.com/lumicks/pylake/pull/381 ).
> fitting: fix incorrect model being used for `dsdna`

- docs/whatsnew/index.rst
Currently, the what's new section is in the opposite order when compared to the changelog. This PR fixes that.
> docs: swap order for consistency with changelog

- docs/tutorial/figures/kymotracking/gau_refined_counts.png
- docs/tutorial/figures/kymotracking/gaussian_refined_counts_offset.png
- docs/tutorial/figures/kymotracking/longest_track.png
- docs/tutorial/figures/kymotracking/photon_counts_greedy.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/detail/localization_models.py
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_loc_models.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
We need an attribute that just has the photon counts when we need them (no matter how they were refined). This is especially important since in the future, we'd like to have photon counts originating from Gaussian refinement as well.
*If you squint hard enough, maybe you can see some multimer binding*
Docs build here: https://lumicks-pylake.readthedocs.io/en/count_dem_photons/tutorial/kymotracking.html
There are two open points left remaining after this PR:
1. How to best deal with the file export/import when a track has been refined via different methods. I have opened a separate ticket to figure out a way how to handle this. The CSV format is not ideal for storing metadata and ideally, we should move to something more readily extensible.
2. If we want to explore …
> kymotrack: add photon counts as an attribute

- changelog.md
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/kymotracker/detail/localization_models.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_loc_models.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/tests/test_utilities.py
It is good for users to be able to verify their localization fits, to make sure nothing went wrong. This PR adds two methods to be able to plot them quickly.
Why is it important to plot this? Well, if a user chooses a window that's too small, they might inadvertently find themselves in the situation where the baseline eats up a large chunk of the amplitude, such as here:
A similar situation would happen if you take a window that is too large, but fail to track one of the peaks inside the window.
I intend to add something to the tutorial about this feature (and how to verify that your fits are good etc), but I will keep that for the next PR since there are two PRs with changes that impact the plots in that section.
> kymotrack/kymotrackgroup: allow plotting the localization fit

- lumicks/pylake/nb_widgets/kymotracker_widgets.py
Reducing the min length parameter in the kymotracker widget does not, in fact, reduce noise but rather increase it. Fixed the extended description to state that _increasing_ the min length parameter does have a de-noising effect.
> widgets: Fix parameter description for minimum length

- changelog.md
- docs/install.rst
- lumicks/pylake/detail/tests/test_widefield.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/population/mixture.py
- setup.py
We only use `opencv` for affine transformations. Considering that several other packages provide this functionality, we can also use one of the ones we already include. I did notice that there are small differences in the affine transforms; but considering we're not doing quantitative analysis with them yet, it should be fine. I suspect that this has to do with some speed optimizations OpenCV does (I note that the API docs have a difference between `INTER_LINEAR` and `INTER_LINEAR_EXACT` whereas the latter is not available for `warp_affine`).
We could also just use raw `scipy` for this (as `scikit-image` just calls theirs), but personally, I didn't like that one as much because of the double transpose needed on the `scipy` API.
I have also reduced the scope of a few …
> deps: drop `opencv` in favor of `skimage` for affine transformations

- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/population/mixture.py
There are some dependencies we use relatively rarely. This PR makes sure we only import them as needed by importing them where they are used.
Note that I also added a changelog entry for a previous bugfix that didn't get one.
> deps: import rarely used dependencies on demand

- lumicks/pylake/channel.py
- lumicks/pylake/detail/tests/test_widefield.py
- lumicks/pylake/detail/widefield.py
This fixes a deprecation warning relating to the latest version of `numpy`. Silent conversion to a scalar from an array with dimensions is no longer permitted in the future.
> ci: fix deprecation warning in latest `numpy`

- changelog.md
- lumicks/pylake/file.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo.py
- lumicks/pylake/tests/test_scalebar.py
It's a mechanical replace. We came across this issue when looking at display units for kymotracker widget parameters, but decided to fix it across Pylake for consistency.
- "$\um$" becomes "μm" (Greek small letter mu)
- "$^2$" becomes "²" (superscript two)
> pylake: Replace $math$ unit labels with Unicode variants

- docs/tutorial/fdfitting.rst
- lumicks/pylake/force_calibration/detail/driving_input.py
This has come up in support twice now. Might as well add a sentence or two to show people how to combine different criteria when boolean array indexing the data. Also noticed some deprecated import location in `scipy` that I fixed up.
Docs build here: https://lumicks-pylake.readthedocs.io/en/add_logic_example/tutorial/fdfitting.html#adding-data-to-the-fit
> docs: add logical mask example

- docs/tutorial/figures/kymographs/kymo_wavelength_cmap.png
- docs/tutorial/kymographs.rst
- docs/whatsnew/1.2.0/1_2_0.rst
- docs/whatsnew/1.2.0/wavelength_cmaps.png
- docs/whatsnew/index.rst
- lumicks/pylake/adjustments.py
- lumicks/pylake/tests/test_image.py
The original idea came up during a feedback session with a customer who pointed out that "blue channel" data is plotted as blue (corresponding to the excitation color), however the actual emission color is green (red-shifted). Taking it a bit further, I found a paper with equations to approximate RGB values from wavelengths in the visible spectrum
*note: I started up the what's new section for 1.2.0 already here. I think it's easier to build this up as we go along rather than right before release; the intro text reads "sneak peak for 1.2.0" so we'd just need to change this to "has been released" in the final PR*
[docs build here](https://lumicks-pylake.readthedocs.io/en/wavelength_cmap/)
> Generate colormaps from wavelengths

- lumicks/pylake/piezo_tracking/tests/test_piezo_tracking.py
- lumicks/pylake/population/tests/test_dwelltimes.py
Just noticed that CI wasn't passing on another PR. `mpl` started warning us about layout changes when `tight_layout()` gets called twice (which is good). Probably better to just close the figure after we're done with it in the test, so that state doesn't propagate to the next plot in the test.
> ci: close figures before issuing another plot

- changelog.md
- lumicks/pylake/detail/h5_helper.py
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file/test_file.py
It's a tiny thing, but I noticed this while trying to export an `h5` file with a certain field removed. If you just pass a string to `omit_data`, it gets confusing since it iterates over the characters in that string. It doesn't give you a helpful error.
It should either accept a string and upconvert it to something iterable (which I did), or throw. I chose the former, because I don't see a reason to explicitly disallow the convenience option here (as most people would likely only exclude a single mask).
I also changed the doc format to the `numpydoc` format we use elsewhere.
> file: allow `str` for `omit_data` in `save_as`

- .github/workflows/pylake_test.py
- lumicks/pylake/conftest.py
- lumicks/pylake/tests/reference_data/freezing/forced_filename_1.npz
- lumicks/pylake/tests/reference_data/freezing/forced_filename_2.npz
- lumicks/pylake/tests/reference_data/freezing/freezing[1].npz
- lumicks/pylake/tests/reference_data/freezing/freezing[2].npz
- lumicks/pylake/tests/reference_data/freezing/mytest[1].npz
- lumicks/pylake/tests/reference_data/freezing/mytest[2].npz
- lumicks/pylake/tests/test_utilities.py
For another PR I have in flight, I noticed I was about to hardcode a bunch of matrices as data. Instead, it seems better to store these as a file. This PR is supposed to make this a bit more convenient. It is intended as a convenience function for small amounts of data (if we go to bigger datasets we will likely need something else in addition to this).
The function can be used by importing the fixture `reference_data` and then polling the reference data like:
```python
np.testing.assert_allclose(test_data, reference_data("test_data_name", test_data))
```
If the test data does not exist yet, the test data is generated when this function is called. If it does exist, but is different then it raises an error. You can then choose to delete the reference file (which will …
> ci: add option to freeze reference data

- changelog.md
- docs/whatsnew/1.2.0/1_2_0.rst
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_image_sampling.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/kymotracker/tests/test_stitching.py
- lumicks/pylake/kymotracker/tests/test_tracing.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/simulation/diffusion.py
Currently, we take the minimum time of the available dwell times per kymograph as the minimally observable dwelltime. For kymographs with few events, this can be off as the lowest dwell time could simply not have been observed. This leads to a potentially large bias in the estimates obtained with global analysis (if few events per kymo are available). For kymographs with many events, the bias is likely to be small.
Highly recommend going commit by commit. I left the big testing update as a separate commit to try and separate the signal from the noise a bit.
Unfortunately, the ability to perform dwell time analysis on multiple Kymo's has been released in `1.1`, meaning that it was technically possible to get into the state where you would get such biases. This means we …
> dwelltime analysis: correctly handle minimum observable time

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/image.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_image.py
- lumicks/pylake/tests/test_imaging_confocal_old/conftest.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_point_scan.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_scan.py
- lumicks/pylake/tests/test_utilities.py
Currently, we reconstruct the entire timestamp array to obtain the pixel and line time. Considering that this is something we do often, while we rarely need the full matrix of per-pixel timestamps, we may want a fast path here. Loading 30 kymographs and obtaining the line and pixel times goes from `4.1 +- 0.5` seconds to `0.5 +- 0.14` seconds on my machine.
I recommend to go commit by commit.
**Old tests**
To make sure this change doesn't fire up a bunch of the very old tests, I had to update the test data to some degree. I decided to go with minimal changes on that front, since it is not the focus of this PR. You can check out that commit and all tests should be green at that particular commit.
Note that the affected tests are all in the old test folder (and thankfully …
> confocal: faster pixel and line times.

- docs/install.rst
- setup.py
To work around a bug in `notebook` we need to pin the upper limit of `jupyter_client` and `zeromq` (see https://github.com/jupyter/notebook/issues/6748).
Until now, we've been asking users to add these extra constraints manually, but forgetting it can lead to broken interactive notebook functionality. It's unnecessary friction when it comes to installing `pylake`. Instead of adding these lines to the pip [installation instructions](https://github.com/lumicks/pylake/pull/538), it's better to just add it to the requirements for the time being.
When we release on `conda`, we should also pin the upper limit in the recipe there.
> deps: enforce upper limit `jupyter_client` and `pyzmq`

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/h5_helper.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/file.py
- lumicks/pylake/kymotracker/detail/sequence.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
This is a very minor addition. My IDE showed a warning when I was passing a `pathlib.Path` to `pylake` since the type hint was only `str`. These days, most APIs accept anything that's `PathLike` instead of strict `str`.
> Mark file APIs with `os.PathLike` type hint

- lumicks/pylake/adjustments.py
- lumicks/pylake/fitting/detail/derivative_manipulation.py
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/parameter_trace.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/force_calibration/detail/driving_input.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/data/simulate_calibration_data.py
- lumicks/pylake/force_calibration/tests/data/simulate_ideal.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/touchdown.py
- lumicks/pylake/kymotracker/detail/denoising.py
- lumicks/pylake/kymotracker/detail/gaussian_mle.py
- lumicks/pylake/kymotracker/detail/geometry_2d.py
- lumicks/pylake/kymotracker/detail/peakfinding.py
- lumicks/pylake/kymotracker/tests/test_geometry_2d.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/mixture.py
- lumicks/pylake/population/tests/test_dwelltimes.py
This follows one simple rule: At module scope, always use `import scipy`, never `imports scipy.<foo>` nor `from scipy import <foo>`.
Why: `scipy.<foo>` works anyway following `import scipy` and it will lazily import heavy submodules. Using `imports scipy.<foo>` forces the submodules to be imported eagerly.
Results: On my machine, cold import (first import following installation) goes down from 11.4 seconds to 3.9 seconds. Hot import goes down from 0.7 to 0.4 seconds.
Measuring: I followed the import time profiling method [described here](https://stackoverflow.com/a/51300944) plus a `pipenv` for reproducible cold import measurements:
```
mkdir tmp && cd tmp
pipenv --rm && pipenv shell
pip install <path/to/pylake>
python -X importtime -c "import lumicks.pylake" 2> pylake-cold.log
python -X …
```
> Speed up `import lumicks.pylake` by streamlining `scipy` imports

- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
The minimum observation time for the discrete dwell time model is the discretization timestep. Since our `DwelltimeModel`, uses a default minimum time of zero, I see a potential risk for misuse here. I think it's better to just raise if we see this being provided.
I also did a fixup on the test here, since I noticed that some of the cases didn't abide this constraint (shows how easy it is to miss it). I also noticed that I accidentally disabled the profile test earlier (so I reverted that).
> dwelltime: enforce minimum time

- lumicks/pylake/force_calibration/tests/data/simulate_calibration_data.py
- lumicks/pylake/kymotracker/tests/data/generate_gaussian_data.py
- lumicks/pylake/kymotracker/tests/test_algorithm_scaling.py
- lumicks/pylake/kymotracker/tests/test_derived_quantities/test_msd.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/kymotracker/tests/test_image_sampling.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_peakfinding.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/kymotracker/tests/test_sequence.py
- lumicks/pylake/kymotracker/tests/test_stitching.py
- lumicks/pylake/nb_widgets/tests/test_kymotracker_widget.py
- lumicks/pylake/population/tests/data/generate_trace_data.py
- lumicks/pylake/tests/data/mock_fdcurve.py
- lumicks/pylake/tests/data/mock_file.py
- lumicks/pylake/tests/data/mock_widefield.py
- pyproject.toml
If we're gonna be doing spring cleaning, might as well do all the tests now and just have `black` be active everywhere from now on. We can always selectively turn it off if we really need some bulky matrices.
I quickly went over all the changes and there was nothing particularly egregious anymore that wasn't already covered by explicitly disabling the formatter locally.
> black: enable `black` formatting for tests

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/data/simulate_calibration_data.py
- lumicks/pylake/force_calibration/tests/data/simulate_ideal.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- setup.py
We rely on some functionalities that depend on newer versions of `numpy` (`dtype` argument for hvstack) and lazy imports for `scipy`.
The lazy import ensures that this works:
```python
import scipy
scipy.optimize.curve_fit  # Prior to 1.9.0 this would fail.
```
Note that `scipy.optimize.constants` seems to have been forgotten in the initial release for lazy imports, but is added in [`1.11.1`](https://github.com/scipy/scipy/commit/855bc76864ea1e577bedb854a5d9aef97a149a86). The latter is probably still a bit too new.
The last thing is a temporary upper limit for the version of `jupyter notebook`. The reason we are introducing this is because we've been seeing issues with the `%matplotlib notebook` not working on several computers (resulting in an error that `IPython is not …
> deps: update `pylake` dependencies

- docs/tutorial/figures/force_calibration/calibration_item.png
- docs/tutorial/figures/force_calibration/calibration_item_active.png
- docs/tutorial/figures/force_calibration/identify_peaks.png
- docs/tutorial/figures/force_calibration/power_spectrum_no_noise_peak.png
- docs/tutorial/figures/force_calibration/power_spectrum_noise_peak.png
- docs/tutorial/figures/force_calibration/power_spectrum_noise_peak_robust.png
- docs/tutorial/force_calibration.rst
**Why?**
As a follow-up on #528 I have added a section on robust fitting and automated peak identification to the force calibration tutorial. See https://lumicks-pylake.readthedocs.io/en/robert-robust-fitting-example/tutorial/force_calibration.html#robust-fitting
Note that I updated the images of the force calibrations to reflect the fact that there is a new line stating the loss function in the results. I'm not sure this warrants a new image, but it's there just in case.
TO DO:
> docs: add section on robust fitting in force calibration tutorial

- changelog.md
- docs/tutorial/nbwidgets.rst
- docs/whatsnew/1.2.0/1_2_0.rst
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
Turns out that you can't resave a `csv` file when it's been opened until you call `lk.filter_tracks()` because of the `None` entries.
> kymotrackgroup: test round trip from old csv

- docs/install.rst
We pinned `conda` to an older version [earlier](https://github.com/lumicks/pylake/commit/11d383378bdbeea49c7ae61c4614668bafbc563b) to work around an OpenSSL issue. It seems that on newer `conda` versions, this issue is fixed. However, when creating a new conda environment from an older version _without_ specifying a version, it typically still installs an older version that does have the OpenSSL issue. The newer versions however, do download and extract packages in parallel which is much faster, so I would suggest keeping the explicit version in the installation instructions, but bumping it to the latest one.
> docs: update install instruction with latest conda

- lumicks/pylake/force_calibration/touchdown.py
Use non-zero initial guess for the decay parameter so it isn't exactly at the bound. `scipy=1.11.2` issues a `DivisionByZero` warning when the initial guess is exactly at the bound, but the solution is outside of the bounds.
Since in our case, it is better to provide a nonzero initial guess for the decay anyhow, this seems like the best solution.
> touchdown: use nonzero initial guess for decay

- changelog.md
- lumicks/pylake/detail/utilities.py
In [this PR](https://github.com/lumicks/pylake/pull/544), a dependency on `cachetools>=5` was inadvertently introduced.
`cachetools>=5.0.0` started passing `self` as first argument. The previous PR had been made under the assumption that this was always the case. Since we don't want to bump the reference count by including a reference to the object we're about to store the cache into, so we explicitly drop the first argument. For `cachetools<5` this then results in an error since we're assuming the `self` argument is there, while it is not.
Note that for the default key, they also cut off the first argument in the package, but we can't use the default key, since it doesn't hash in the method name to prevent clashes when we use more than one cached method in an instance.
> caching: backward compatibility for `cachetools<5`

- lumicks/pylake/conftest.py
- lumicks/pylake/tests/reference_data/freezing/non_ndarray_matrix[1].npz
- lumicks/pylake/tests/reference_data/freezing/non_ndarray_matrix[2].npz
- lumicks/pylake/tests/test_utilities.py
Non-ragged lists should just be converted to `ndarray`, since it facilitates convenient testing. If you don't do this, then you can't really use `np.testing.assert_allclose` conveniently, since you'll always explicitly have to do this step.
> ci: convert convertible list of lists to `ndarray`

- changelog.md
- lumicks/pylake/force_calibration/calibration_models.py
*Why*
During testing of robust fitting on axial force data I sometimes received a "division by zero" exception (or equivalent, can't fully remember). I traced it back to the lower bound of `f_diode`, which is zero. I think a still very reasonable lower bound is 1 Hz, one that is very unlikely to actually occur in practice but prevents 1/0.
> force calibration: new lower bound for f-diode

- changelog.md
- lumicks/pylake/adjustments.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/detail/plotting.py
- lumicks/pylake/detail/tests/test_plotting.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/kymo.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_scan.py
Enable some extra conveniences:
- alias single-channel plotting (eg, `kymo.plot("r")` instead of `kymo.plot("red")`
- enable 2-channel plotting (eg, `kymo.plot("rg")` and ignore the blue channel)
*note: I had to change the error message thrown if an invalid channel argument is supplied to `export_video`. There was no way to get around this as we hard-coded in the previous choices. However the type `ValueError` remains the same
> More options of image plotting `channel` argument

- lumicks/pylake/tests/data/mock_confocal.py
- lumicks/pylake/tests/data/test_mock_confocal.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_kymo.py
We've had a longstanding ticket to rework and reorganize the confocal imaging tests. The main point is to remove hardcoded reference values for comparisons. Preparatory work was done in #413 where you can now generate reference data when creating mock kymos and scans.
The strategy in this PR was to, one-by-one, copy relevant tests from `test_imaging_confocal_old/test_kymo.py` to the new `test_imaging_confocal/test_kymo.py` and replace all hardcoded reference values with values from the reference data objects. Fixtures also added to `conftest.py` as needed. I also ended up needing to add some extra data to the timestamps reference object for completeness. Finally, I removed all of the old tests that had been reworked (keeping that in a separate commit)
Right now, I've …
> Rework confocal tests: kymo basics

- changelog.md
- lumicks/pylake/file_download.py
The API changed the record lookup from using `record_id` to `id`
> Fix fetching files from zenodo

- docs/tutorial/figures/imagestack/imagestack_adjust_absolute.png
- docs/tutorial/figures/imagestack/imagestack_adjust_percentile.png
- docs/tutorial/figures/imagestack/imagestack_cropped.png
- docs/tutorial/figures/imagestack/imagestack_red.png
- docs/tutorial/figures/kymographs/kymo_blue.png
- docs/tutorial/figures/kymographs/kymo_intro.png
- docs/tutorial/figures/kymographs/kymo_wavelength_cmap.png
- docs/tutorial/figures/plotting_images/adjustment_options.png
- docs/tutorial/figures/plotting_images/colormaps.png
- docs/tutorial/figures/plotting_images/gamma.png
- docs/tutorial/figures/plotting_images/plot_intro.png
- docs/tutorial/figures/plotting_images/scalebar.png
- docs/tutorial/imagestack.rst
- docs/tutorial/index.rst
- docs/tutorial/kymographs.rst
- docs/tutorial/plotting_images.rst
- docs/tutorial/scans.rst
- docs/whatsnew/1.3.0/1_3_0.rst
- docs/whatsnew/1.3.0/plot_channel_options.png
- docs/whatsnew/index.rst
Now that our image plotting API is consistent across all of our image classes, it makes sense to have a single page explaining the shared plotting functionality rather than duplicating it in each tutorial.
[Build here](https://lumicks-pylake.readthedocs.io/en/all_the_plot_docs/tutorial/plotting_images.html)
> Consolidate plotting documentation

- changelog.md
- lumicks/pylake/scan.py
We currently calculate a default aspect ratio which results in square pixels. For scans acquired with non-square pixels, this results in distortion of the image
Current:
Fixed:
> Fix scan aspect ratio

- changelog.md
- lumicks/pylake/detail/image.py
- lumicks/pylake/file.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file_items.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
Prior to this change, `Kymo`s consisting of a single or partial scan line provide no `line_time_seconds` which prevents plotting and other functionality. Now they provide the line time of what is actually shown in the plot (e.g. a full line, without deadtime if the line time is smaller or equal than a single line).
The second issue is that for a few Bluelake versions, Bluelake put some kymographs that were taken with a fixed line count in the `Scan` field. The last commit contains a fallback method so that they will not be loaded as corrupted `Scan` items, but end up in the `kymos` field.
> kymo: make single line scan return a valid `line_time_seconds`

- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/test_scan.py
- lumicks/pylake/tests/test_imaging_confocal_old/test_scan.py
Continued modernisation of confocal tests, moving on to `Scan`s. With new reference data, was able to significantly reduce the length of the tests while extending to all permutations of fast/slow axes. Left as separate commits, but will squash before merging
> Migrate basic scan tests

- changelog.md
- docs/theory/diffusion/diffusion.rst
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
It makes more sense for users to filter by a specific track duration, rather than a number of points in a track.
*What to look out for*
It is important to set the minimum time appropriately. If we filter by length `min_duration`, then the first length we can actually observe is the next available duration `ceil(min_duration / line_time) * line_time`.
Below are the results of running dwell time analysis on the results from two simulated kymos (line time 0.25 and line time 0.1) with 1000 lines each.
If one computes the minimally observable duration correctly, the estimates are as expected:
_Rounded to next step (ceil)_
If not, then well, we get biased results:
_Rounded to nearest value (round)_
_Not rounded_
Note that the track durations were chosen (short compared to the …
> tracking: add `min_duration` argument to `lk.filter_tracks`

- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
I find myself frequently adding this same calculation to notebooks.
When using `window_seconds`, it is not immediately apparent how many of the raw data points actually get used and what frequency bin width that leads to. You could compute the bin width from `ps.frequency[1] - ps.frequency[0]` but that comes with the caveat that someone could have chopped parts of the spectrum out giving you an incorrect value.
We know what the native bin width will be, so let's add it as a property.
> powerspectrum: add bin width number of samples used to compute the power spectrum.

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_channels/test_channels.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Fixes some issues that came up during mutation testing.
- Removes some unnecessary code from line time reconstruction.
- Improves tests by including more specific corner cases.
- Fixes a bug in `downsampled_like` that produced an unusable `Slice`.
> Small test improvements and bugfix on `Slice`.

- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
It seems that on jupyter notebook, when you export a movie, keeping a handle to `FuncAnimation` results in `matplotlib` attempting to disconnect a callback that no longer exists when you call `plt.close()`. This change mitigates that by not storing the variable.
> export_movie: force showing the figure

- .gitattributes
- changelog.md
- docs/tutorial/imagestack.rst
- docs/tutorial/scans.rst
- docs/whatsnew/1.3.0/1_3_0.rst
- docs/whatsnew/1.3.0/export_correlated.gif
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/nb_widgets/correlated_plot.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_plotting.py
Highly requested feature. This feature allows you to export channel data alongside a movie. Users want these kind of movies in talks and whatnot.
I've manually tested all permutations I could think of (cropping by time, pixels, including color adjustments for both scans and image stacks). I tested on jupyter notebook (with `notebook` backend), jupyter lab (with `widget` backend) and on the non-interactive backend.
Docs [here](https://lumicks-pylake.readthedocs.io/en/correlated_movie/whatsnew/1.3.0/1_3_0.html), [here](https://lumicks-pylake.readthedocs.io/en/correlated_movie/tutorial/imagestack.html#stack-plotting) and [here](https://lumicks-pylake.readthedocs.io/en/correlated_movie/tutorial/scans.html#confocal-plotting). API docs …
> export_movie: add the option to correlate a channel slice when exporting to a movie

- changelog.md
- lumicks/pylake/nb_widgets/correlated_plot.py
It fixes a bug that leads to an off-by-one error in the correlated plot.
- We downsample over the frame.
- The downsampled time axis uses the minimum timestamp of each frame as its timestamp.
- We subtract the first downsampled timestamp such that the origin starts at zero.
- We want to hold this first sample over the entire frame, as it corresponds to that frame. In other words, up to the next frame/time point. Therefore we should be using "post", not "pre" when setting up the step plot.
- To make sure we get an additional stick for the last frame, we must also hold the last value for the frame time.
Note:
I will defer the regression test (for now) as I plan to add an additional test that will cover this once we correctly handle the exposure time for `ImageStack`. …
> plot_correlated: fix off by one error

- docs/_ext/nbexport.py
- docs/requirements.txt
Our docs stopped building.
One is an import issue (they removed an import from `nbexport` [here](https://github.com/jupyter/nbconvert/commit/a7df9afbf165e397c31d6b79c66cff8288e4a42e)). Second was just a warning (but one that will become an error in the future) which is that an `id` field is missing from our exported notebooks.
> docs: fix import issue and add `id` field to notebook export

- docs/api.rst
- docs/conf.py
- docs/refs.bib
- docs/requirements.txt
- docs/tutorial/figures/population_dynamics/hmm_hist.png
- docs/tutorial/figures/population_dynamics/hmm_labeled_trace.png
- docs/tutorial/population_dynamics.rst
- lumicks/pylake/population/__init__.py
- lumicks/pylake/population/detail/fit_info.py
- lumicks/pylake/population/detail/hmm.py
- lumicks/pylake/population/detail/validators.py
- lumicks/pylake/population/hmm.py
- lumicks/pylake/population/tests/test_hmm.py
- lumicks/pylake/population/tests/test_hmm_algos.py
- lumicks/pylake/population/tests/test_mixture.py
- lumicks/pylake/population/tests/test_validators.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Adds models for analyzing time series data exhibiting transitions between discrete states. This is useful for constant-extension experiments or photon count time traces (especially FRET)
This PR lays down all of the internal algorithms for model training and state labeling. A second PR will focus on building up the rest of the public API with convenience functions for plots, histograms, etc...
Notes:
- Similar to `lk.GaussianMixtureModel` that wraps `sklearn`'s GMM, I defined an internal model class to just handle the parameters and initialization/update; we can then expose what we want from the model through the public API that wraps this
- There is a lot of internal code that uses notation seemingly from nowhere, however it is pretty standard in the HMM field and …
> Hidden Markov models

- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/power_models.py
- lumicks/pylake/force_calibration/tests/data/simulate_ideal.py
- lumicks/pylake/force_calibration/tests/test_camera_calibration.py
- lumicks/pylake/force_calibration/tests/test_simulations.py
This model can be used for camera-based calibrations with longer exposure times. Public API is pending.
See [Wong, W. P., & Halvorsen, K. (2006). The effect of integration time on fluctuation measurements: calibrating an optical trap in the presence of motion blur. Optics express, 14(25), 12517-12531](https://opg.optica.org/oe/fulltext.cfm?uri=oe-14-25-12517) for more information.
> calibration: add private api for motion blur model

- changelog.md
- lumicks/pylake/file.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
This allows reconstruction of images from systems where the photon detector channels are not named with the standard "Red, "Green", and "Blue" names.
For example, this image is reconstructed from a file where the photon count channels are named `Detector 1`, `Detector 2`, `Detector 3` and `Detector 4`. 
Draft because needs additional tests.
> Add custom mapping of photon counter channels to RGB colors

- .gitattributes
- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/kymo.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_imaging_camera/data/tiff_from_scan_v1_3_1.tiff
- lumicks/pylake/tests/test_imaging_camera/reference_data/legacy_exposure_handling/dead_time[False].npz
- lumicks/pylake/tests/test_imaging_camera/reference_data/legacy_exposure_handling/dead_time[True].npz
- lumicks/pylake/tests/test_imaging_camera/test_image_reconstruction.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
- lumicks/pylake/tests/test_imaging_confocal/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_imagestack.py
- lumicks/pylake/tests/test_imaging_mixins.py
- lumicks/pylake/tests/test_scalebar.py
- setup.manifest
Currently, `frame_timestamp_ranges` does not return the correct values for `include_dead_time=False` for `ImageStack` objects loaded from camera images. The reason for this was an invalid assumption on the data inside the `DateTime` tag.
Instead of `start of frame N:end of the exposure of frame N`, this metadata contains `start of frame N:start of frame N+1`. The actual exposure is stored in a field called `Exposure time (ms)` in the json field.
TIFF files written with Pylake from confocal `Scan` and `Kymo` objects were storing `start of frame N:end of the exposure of frame N` and no exposure field in the metadata. This PR also changes that to make it consistent with Bluelake files.
To recap, we have the following metadata:
1. The per-frame DateTime tag, where we have …
> `ImageStack`: Make `include_dead_time=False` actually exclude the dead time.

- lumicks/pylake/population/detail/hmm.py
- lumicks/pylake/population/detail/mixin.py
- lumicks/pylake/population/hmm.py
- lumicks/pylake/population/mixture.py
- lumicks/pylake/population/tests/test_hmm_algos.py
After adding HMMs and re-aligning the GMM API, I realized that we could de-duplicate a bit more code using the mixin if we implement a simple data structure for the GMM rather than just storing the `sklearn` model. This has the added benefit in that we can get rid of the `as_sorted` decorator and the private `_map` property.
All changes are to private API
Two tiny extras that I had to do, but I think it's worth it:
- store the `lower_bound` as a private attribute, but this can be removed when we remove `exit_flag`
- change the implementation of the deprecated `label()` method, but I realized we can do it even easier with other stuff we already had
> Move duplicated GMM/HMM properties to mixin

- changelog.md
- lumicks/pylake/force_calibration/tests/test_touchdown.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
Pytest changed its warning/exception order starting from `8.0.0` (see https://github.com/pytest-dev/pytest/issues/9036).
This updates our tests to pass under the new and old version of `pytest`.
- For kymographs, this meant explicitly passing a motion blur parameter such that we don't issue that error instead of what we are looking for.
- For the dwelltime analysis, we have to make sure we don't get any of the deprecation warnings so that we can see the warning we are testing for.
- For touchdown, we have to explicitly silence the covariance matrix is undefined error (which actually already tells us that the problem will be non-identifiable i.e. too little data, which is exactly what the test tests for).
After this gets merged, I will merge `1.3` back into `main`.
> ci: fix tests for `pytest>=8.0.0`

- changelog.md
- docs/api.rst
- lumicks/pylake/__init__.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/detail/salty_water.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
Sometimes one may use a high sodium buffer. In that case, you need a different viscosity and density.
The first two commits introduce the functionality. The last commit I would say is optional, but I feel it's an improvement. It basically merges the functionality of `viscosity_of_salty_water` into `viscosity_of_water` by just giving it an extra argument. I feel this is better for discoverability of the API. Plan would be to just squash it before merge.
Paper here: https://srd.nist.gov/JPCRD/jpcrd176.pdf
Docs build here: https://lumicks-pylake.readthedocs.io/en/salty_branch/_api/lumicks.pylake.viscosity_of_water.html
> calibration: add model for salt water

- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
It would be nice to have `ImageStack` close the file handle when it is garbage collected. People have run into not being able to delete files on windows because the handle was still open.
In addition, a `.close()` is added for cases where it should be closed immediately.
I considered two alternatives before going for the wrapper class:
- Using `weakref.finalizer`, but this cannot pass the instance it is closing as argument (and is therefore not a solution for this).
- Adding the handling on `TiffStack`, but this is unfortunately also not an option, since the handle is actually associated with the `TiffFile` and `TiffStack` can return new `TiffStack` instances that reference the same (list of) `TiffFile`s.
> ImageStack: allow closing `ImageStack` file handles

- changelog.md
- lumicks/pylake/detail/confocal.py
- setup.py
`tifffile` deprecated the way we pass the resolution unit a while ago. This PR gets rid of the old way of passing it.
I did have to bump the dependency to where the parameter was first introduced.
> tiff: don't rely on deprecated API for resolution unit

- changelog.md
- lumicks/pylake/group.py
- lumicks/pylake/tests/test_file/test_file.py
Noticed this while working on a small data analysis script. Sometimes, it can be quite useful to grab by full paths, but once you start relying on that, you start noticing that some things are inconsistent with `h5py`.
This makes our API consistent with `h5py`.
Before:
```python
file = lk.File("test.h5")
"Force HF/Force 1x" in file  # => False
"Force HF/Force 1x" in file.h5  # => True
```
After:
```python
file = lk.File("test.h5")
"Force HF/Force 1x" in file  # => True
"Force HF/Force 1x" in file.h5  # => True
```
> group: forward `__contains__` dunder to `h5py`

- changelog.md
- lumicks/pylake/adjustments.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/group.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
- setup.py
Tests are failing on `main` because of one of the missing `tifffile` deprecation fix.
If we're gonna be merging some things back, might as well merge back all the bug fixes as there are no conflicts.
> Merge bug fixes from `1.3` back into `main`

- changelog.md
- lumicks/pylake/detail/bead_cropping.py
- lumicks/pylake/detail/tests/data/kymo_sum0.npz
- lumicks/pylake/detail/tests/data/kymo_sum1.npz
- lumicks/pylake/detail/tests/data/kymo_sum2.npz
- lumicks/pylake/detail/tests/data/kymo_sum3.npz
- lumicks/pylake/detail/tests/data/kymo_sum4.npz
- lumicks/pylake/detail/tests/data/kymo_sum5.npz
- lumicks/pylake/detail/tests/data/kymo_sum6.npz
- lumicks/pylake/detail/tests/data/kymo_sum7.npz
- lumicks/pylake/detail/tests/test_bead_crop.py
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
- lumicks/pylake/tests/test_imaging_confocal/data/bead_kymo.npz
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_slice_crop.py
Selecting ROIs by hand can be cumbersome. This function provides approximate bead edges that can be used for setting the kymotracking ROI (or directly crop the kymograph).
Might be a good initial approach until we find something better. Marked as beta because while tested on a fair number of kymographs, we might still find a better algorithm in the future.
API docs [here](https://lumicks-pylake.readthedocs.io/en/find_beads/_api/lumicks.pylake.kymo.Kymo.html#lumicks.pylake.kymo.Kymo.bead_roi) and [here](https://lumicks-pylake.readthedocs.io/en/find_beads/_api/lumicks.pylake.kymo.Kymo.html#lumicks.pylake.kymo.Kymo.crop_beads)
> kymo: crop beads out of kymograph

- lumicks/pylake/detail/bead_cropping.py
- lumicks/pylake/detail/tests/test_bead_crop.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_slice_crop.py
The algorithm added in https://github.com/lumicks/pylake/pull/623 works fairly robustly, but can fail occasionally for narrow beads. The algorithm in this PR is a bit more general and can be used as fallback.
It makes use of cross correlation to determine features that recur in each frame. Basically, for each window, it attempts to use a series of all possible templates of a given size, which it then cross correlates with the next frame (taking the maximum found cross correlation). This is repeated for each frame. After this, we take the average along the positional axis which gives you a score for how "templatey" that bit is. 
There is a parameter (which is not explicitly documented in the function on kymo), which relaxes the requirement of the template to stay in the …
> kymo: finding bead edges part 2

- docs/examples/cas9_kymotracking/binding_vs_force.png
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cas9_kymotracking/kymo_position_over_time.png
- docs/examples/cas9_kymotracking/kymowidget.png
- docs/examples/cas9_kymotracking/line_duration_vs_force.png
- docs/examples/cas9_kymotracking/photon_counts_longest.png
- docs/examples/reca_fitting/reca_fitting.rst
- docs/tutorial/figures/kymographs/kymo_cropped_bead_edges.png
- docs/tutorial/kymographs.rst
- docs/tutorial/plotting_images.rst
- docs/tutorial/scans.rst
- docs/whatsnew/1.4.0/1_4_0.rst
- docs/whatsnew/1.4.0/bead_edges.png
- docs/whatsnew/1.4.0/tracking_comparison.png
- docs/whatsnew/1.4.0/tracking_comparison_threshold.png
- lumicks/pylake/kymo.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/simulation/diffusion.py
- lumicks/pylake/tests/test_file_download.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_slice_crop.py
Running through all our notebooks, I noticed that there were a few rough edges that needed fixing before release.
In addition, this PR aims to fix a few last remaining issues and incorporates a `slack` variable into the bead edge detector based on review comments.
Unfortunately, it seems that for the widget to be able to use the new functionality at all, we do need to add them to the list of parameters. Initially I thought of adding them to the widget as direct parameters, but this would require ughly additional workarounds to make it work properly. For now I have added them non-UI visible because I feel the guidance on how to best choose it is still being discussed. Right now the default is set to the legacy value, but we could easily change that in the future if we want …
> some final tasks before release

- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Garbage collection isn't run after each test / parametrization, which means that in some cases, handles can still be open which `pytest` raises an exception for. Best to just force close the TIFFs.
Normally, I would have preferred to use a context manager, but I feel providing this API on `ImageStack` would give the wrong impression of what happens in the following case:
```python
with lk.ImageStack("tiff.tiff") as im:
im2 = im[50:100, 50:100]
```
If we were to close `im` here, `im2` would be invalidated. This could be avoided by opening the file only on demand and closing it immediately or copying. For now I would propose just fixing the tests.
> tests: force close tiff files

- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/kymotracker/kymotrack.py
- We have systems out in the field with `100` kHz sampling rate. We should ideally not hardcode the `78125` Hz in our docs examples, because people may end up copying these and getting invalid results.
- We forgot to provide the public function `time_idx` with a docstring which makes it not show up as an API endpoint in the documentation.
> docs: fix some small oversights in the documentation

- changelog.md
- lumicks/pylake/detail/widefield.py
- lumicks/pylake/tests/data/mock_widefield.py
- lumicks/pylake/tests/test_imaging_camera/conftest.py
- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
Some systems in the field have the ability to export two-color tiff stacks. Would be good to add support for them.
*Note*
I have made the judgment call to map the export function to a three color tiff stack with the correct mapping, since it makes it more convenient to load into other software. Not many software packages support two color tiffs out of the box, besides, if people want the original two-color tiff, they have it already.
> imagestack: support two-color tiff stacks

- changelog.md
- docs/theory/force_calibration/fitting.rst
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
The statistical backing calculation that we compute during force calibration is incorrect. It seems the argument order in the lower incomplete gamma function got swapped. I checked back in history and this has always been the case, all the way back to the implementation we had in LDAT. I suspect this confusion arose when someone was looking at MATLAB code (since the argument order is reversed there w.r.t. scipy's `gammainc`).
To avoid the same problem in the future, I also suggest just going straight to evaluating it from a chi squared survival function `(1-cdf)` to make it more immediately apparent what we are calculating here.
I also [added a little text in the docs](https://lumicks-pylake.readthedocs.io/en/fix_gamma/theory/force_calibration/fitting.html#goodness-of-fit) …
> calibration: fix incorrect statistical backing calculation

- changelog.md
- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_diode_models.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
It's a small thing, but it can be tedious to simulate a power spectrum from a fit result (since the number of fitted parameters can vary). This PR makes that a bit more user friendly.
> calibration: make it easier to simulate model

- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/image_stack.py
- lumicks/pylake/nb_widgets/correlated_plot.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_plotting.py
Sometimes, you want to see things that happen within a frame. Currently, we downsample to the frame time. This PR makes this downsampling optional. This means you can just provide a slice that is downsampled the way you want it, and it'll just work.
This is especially important for `Scan` items, because they have long frame times.
This PR proposes adding a new argument for this. Which means you'd call `plot_correlated` or `export_video` with `downsample_channel=False` to get the behaviour where it doesn't downsample extra. The default is `True` for backwards compatibility; but if the old behavior is so bad that one might consider it faulty, we could consider making the default `False`.
> plot_correlated: add option to not downsample the channel data

- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/convenience.py
- lumicks/pylake/force_calibration/detail/hydrodynamics.py
- lumicks/pylake/force_calibration/tests/conftest.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
It may be confusing that we calculate back our drag coefficient to bulk. The reason we do this is so that experiments can be compared and drag coefficients can be carried over from one calibration axis to the other.
However, it may not always be immediately clear how to calculate this value back to the surface-relevant value.
Since one may require the local drag coefficient for other analyses, it is a good idea to also expose a local drag coefficient.
When not using hydro, the drag coefficient we calculate _is_ the local drag.
When hydro _is_ active, then the drag coefficient we obtain with the model is the drag we would have obtained in bulk (all the height dependence is in the model). That means that we have to explicitly convert that drag coefficient to a "local" drag. …
> calibration: expose an estimate of the local drag

- changelog.md
- docs/tutorial/figures/kymographs/kymo_plot_with_channels.png
- docs/tutorial/figures/kymographs/kymo_plot_with_channels_customized.png
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_plotting.py
It would be nice to just plot any channel data alongside kymos and to have control over how these get downsampled.
With this new call (`kymo.plot_with_channels()`), you can make plots like the following with a single call:
and
Note that since not all our channels have y-label metadata (most do not), the y-labels are customizable (by passing a list of labels).
Docs [here](https://lumicks-pylake.readthedocs.io/en/plot_with_channel/tutorial/kymographs.html#correlating-with-channel-data) and [here](https://lumicks-pylake.readthedocs.io/en/plot_with_channel/_api/lumicks.pylake.kymo.Kymo.html#lumicks.pylake.kymo.Kymo.plot_with_channels).
I figured that since we are generalizing this behavior and making it more composable, users may also want to be able to plot more than one …
> kymo: add `plot_with_channels`

- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/examples/cst/kinesin_closed_loop.rst
- docs/examples/cst/kinesin_open_loop.rst
- docs/theory/force_calibration/force_calibration.rst
- docs/tutorial/fdcurves.rst
- docs/tutorial/fdfitting.rst
- docs/tutorial/file.rst
- docs/tutorial/force_calibration.rst
- docs/tutorial/kymotracking.rst
- docs/tutorial/nbwidgets.rst
- docs/tutorial/piezotracking.rst
- lumicks/pylake/file.py
- lumicks/pylake/population/dwelltime.py
Our example/tutorial notebooks were producing some warnings because of characters not being escaped, and we had some other small formatting issues. This PR fixes those. Some of these were found with [blackdoc](https://github.com/keewis/blackdoc).
> docs: small style fixes

- changelog.md
- docs/api.rst
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/parameter_trace.py
- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/fitting/tests/test_fd_models.py
- lumicks/pylake/fitting/tests/test_parameter_inversion.py
A few tiny fixes to reduce API friction based on a use case where we do not fit a model first.
`parameter_trace()` can be used to fit a single parameter on a per datapoint basis while keeping all others fixed. Typically, one would fit a model to _different_ data, and then use that model to compute such a parameter trace. However, there are use cases for when one just wants to do it with a set of parameters obtained earlier (or via other means).
Currently, users might attempt to pass a regular dictionary with values to `parameter_trace()` analogously to what we allow for `model.__call__()`. The error you get when you do that is not helpful, nor does the docstring indicate any way to do this.
One thing I doubted about is whether we should just fall back to the default …
> fdfit: better error handling `parameter_trace()` 

- changelog.md
- lumicks/pylake/detail/imaging_mixins.py
- lumicks/pylake/nb_widgets/correlated_plot.py
- lumicks/pylake/tests/test_imaging_camera/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_export.py
- lumicks/pylake/tests/test_imaging_confocal/test_plotting.py
Working on the what's new section, I noticed two bugs in the video export functionality.
The first is that the final time step when not downsampling is too big (it takes the frame time step rather than the channel time step we should actually be using when not downsampling to frames).
Without it, you get this:
This feature was never released (therefore I did not include a changelog entry).
The second bug is that the `start_frame` argument is ignored. This bug was introduced in Pylake 1.3.0 in this [PR](https://github.com/lumicks/pylake/pull/600).
Note that I am targeting `main`, since we want to release `1.5.0` soon and have no plans for `1.4.1`, but we could easily backport the `start_frame` fix if there is a need.
In both cases, I've hardened the tests to cover these …
> video export: fix two bugs in video export

- .github/workflows/pylake_docs_test.yml
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- .github/workflows/pylake_test_no_notebook.yml
- .readthedocs.yaml
- changelog.md
- docs/examples/cas9_kymotracking/cas9_kymotracking.rst
- docs/install.rst
- docs/tutorial/imagestack.rst
- docs/tutorial/nbwidgets.rst
- docs/tutorial/scans.rst
- lumicks/pylake/conftest.py
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
- lumicks/pylake/nb_widgets/range_selector.py
- pyproject.toml
- setup.py
It's good to stay relatively up to date with Python versions. This PR drops support for Python `3.9` and adds support for `3.12`.
We could consider keeping `3.9` for one more release and immediately drop it on the next (to ease any transition issues) or just rip the band-aid off now. I have a mild preference for the latter, since `3.9` is old, and all the dependency changes we _are_ already doing for `jupyter notebook` might require a new environment for some anyway.
*Jupyter*
With `3.12` comes a necessary change, which is the switch to jupyter `notebook>=7`. Reason being that `notebook<7` pins us to `pyzmq<25`. For a while, they [added](https://github.com/jupyter/notebook/pull/6749) this pin officially, but they have since dropped …
> Support python 3.12 / notebook>=7 and drop support for python 3.9.

- changelog.md
- lumicks/pylake/__about__.py
Release 1.5.0!
Builds here: [changelog](https://lumicks-pylake.readthedocs.io/en/release_v1_5_0/changelog.html) and [what's new](https://lumicks-pylake.readthedocs.io/en/release_v1_5_0/whatsnew/1.5.0/1_5_0.html).
> Release pylake v1.5.0

- lumicks/pylake/tests/test_imaging_camera/test_image_stack.py
*Why this PR?*
Unfortunately, one of our tests is broken.
The test in question tests whether a `Kymo` coming from an `ImageStack` can be tracked successfully.
`track_greedy` raises when the threshold is equal or smaller than the minimum pixel value.
The minimum pixel value of the `Kymo` exported from the `ImageStack` here is `3`. That means this test can randomly fail during tracking, depending on whether the floating point pixel value (after filtering) is slightly above or below this critical value.
It seems that numerically, we typically ended up with `2.9999999999999996` for the minimum pixel value. Meaning the threshold would be above.
> tests: fix test for tracking `ImageStack`-based `Kymo`

- changelog.md
- lumicks/pylake/__about__.py
We currently have a bug on the latest release that prevents people from opening files with a subset of photon channels.
Would be nice to quickly release a hotfix for this.
> release: release Pylake v1.5.1

- changelog.md
- lumicks/pylake/file_download.py
- lumicks/pylake/tests/test_file_download.py
Currently, when there is a hash mismatch between the file on Zenodo and the one on disk, your only recourse is to either use `force_download=True` which re-downloads all the files or delete the file manually (which can be tricky) and then rerun the function. This one adds an argument `allow_overwrite` to allow overwriting those files where there is a hash mismatch only.
> zenodo: add `allow_overwrite` as parameter

- changelog.md
- lumicks/pylake/calibration.py
- lumicks/pylake/group.py
- lumicks/pylake/tests/test_file/test_file_items.py
It's a small thing, but it is often awkward to explain the difference between
`f.force1x`, `f.downsampled_force1x` and `f["Force HF"]["Force 1x"]` and `f["Force LF"]["Force 1x"]`. The former nets you metadata, while the latter does not, even though most other channel access happens with square brackets.
This PR adds that the force metadata is available when accessing with square brackets as well.
> file: populate calibration field when accessing force via square brackets

- changelog.md
- docs/tutorial/figures/kymographs/kymo_plot_with_channels_customized.png
- docs/tutorial/kymographs.rst
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_plotting.py
People want to be able to set custom titles in `plot_with_channels`. I went with the parameter name `titles` since it seemed logical.
Example usage:
```python
kymo.plot_with_channels(
[
file.force1x.downsampled_by(100),
file["Photon count"]["Green"].downsampled_over(kymo.line_timestamp_ranges(), reduce=np.sum),
],
"rgb",
adjustment=lk.ColorAdjustment(5, 98, "percentile"),
aspect_ratio=0.2,
title_vertical=False,
titles=["First", "Second", "Third"],
)
```
> kymo: allow custom titles in `plot_with_channels`

- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
In an effort to make Pylake calibration results more similar to Bluelake calibration results, this adds both fit range and exclusion ranges to the `CalibrationResults`.
Note that it is private in this PR, because the next PR will add a layer on top that unifies the properties for both classes (`CalibrationResults` and `ForceCalibrationItem`).
> calibration: private api for exclusion/fit ranges

- changelog.md
- docs/api.rst
- lumicks/pylake/calibration.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_axial.py
- lumicks/pylake/force_calibration/tests/test_diode_models.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/tests/test_file/test_calibration_item.py
It's about time we defined a unified calibration API that exposes (but also documents) all the relevant properties.
This PR adds almost all of the plumbing.
Previously, we always exposed the raw dictionary data for calibration items. This has lead to subtle differences between calibration items coming from Bluelake and ones performed by Pylake. In addition, many of the names of these dictionaries can be sort of cryptic if you are not intimately familiar with force calibration.
This commit adds an actual calibration API with properties that have human readable names for all the important parameters and results. In addition to that, there are extensive doc-strings now that describe what each parameter means. To make sure the items do not go out of sync again (and keep …
> calibration: expose all relevant calibration parameters as properties

- changelog.md
- lumicks/pylake/nb_widgets/kymotracker_widgets.py
The widget won't open on versions of `matplotlib` later than 3.9, since the magic `%matplotlib widget` now returns the widget name `widget` rather than `ipympl`. In addition, it seems that 3.9 [lowercases](https://github.com/matplotlib/matplotlib/pull/27948) all the backend names, but older ones didn't, so I decided to do that defensively in our check too.
I've added a second option for a magic, since in this case, if we had had this in the error message, the user would have likely found `%matplotlib ipympl` to be functional (it does work already in 3.9.0).
> tracker: allow widget backend

- changelog.md
- lumicks/pylake/calibration.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_active_calibration.py
- lumicks/pylake/force_calibration/tests/test_hydro.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/tests/data/mock_file.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_calibration_item.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_file/test_file_items.py
Given that we now have actual properties defining the physical properties of each force calibration result, it's time to actually present these to the user.
In the updated API, the html and string representation of a calibration item give you a short summary of what's in there. Note the last column, which indicates whether the `Slice` you got this calibration item from actually contains the data you would need to recalibrate. I hope this will make it more clear when a sufficient amount of data was exported.
Access to the items is still by indexing them. And this now lists a table of properties.
**What to look out for?**
Technically, this PR is breaking, because we used to return a raw `list` of force calirations from `.calibration`. A regular list has some more operations …
> calibration: force calibration API pretty printing

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_io.py
This makes sure the `photon_counts` field is populated when loading a file and issues a warning if something unexpected happens.
Edit: Doh! When merging the last bugfix, I made changes back in time in the changelog. I just fixed that in this PR.
> kymotrack: load photon counts from file

- .gitignore
- docs/run_notebooks.py
- release.md
This is a little Friday afternoon project. It's happened more than once that notebooks we ship broke or used deprecated API. Considering how our collection of notebooks is growing (and expected to grow further), I think we need some sort of semi-automated solution to catch these problems. I did have a quick look at [galata](https://github.com/jupyterlab/jupyterlab/tree/main/galata), but I feel that for what we are doing here it is overkill for now.
Running this little script before release should prevent that.
Basically, you just run it from the command line _after_ building the docs:
`python docs/run_notebooks.py --reset`
It caches which notebooks already passed, so rerunning it without `reset` only reruns the needed ones.
`python docs/run_notebooks.py`
Finally, if you …
> testing: add small script to test notebooks we ship

- lumicks/pylake/detail/tests/test_value.py
- lumicks/pylake/detail/value.py
We have some parameter classes (`CalibrationParameter` and Fd-fitting `Parameter`) which hold metadata about the parameter (description, unit, etc...) along with a value. Currently, to use these types in any sort of arithmetic you have to specifically request the `value` attribute
```
result = array * parameter.value
```
Using this mixin allows for a simpler syntax while maintaining the useful metadata
```
result = array * parameter
```
This PR focuses on implementing the necessary dunder methods as described in [Emulating Numeric Types](https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types) and tests (there are a lot of possibilities here, so suggestions on extra tests or things I've missed are very welcome). Following PRs will apply this mixin to …
> Emulate numeric types for parameter classes

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
It seems that in some rare conditions, we see some truncated confocal kymos. While we should solve this upstream, the fact that these were generated means that we should likely provide a fallback option for opening them.
> scan: allow loading truncated scans

- docs/run_notebooks.py
I didn't realize this, but we use the same filenames quite frequently. This silently makes the checker skip these files. This commit fixes that by encoding the relevant part of the path in the name used in both the report and the target filename in case of a `--copy`.
I also added two quality of life features.
- If you run this script with `-n specific_notebook.ipynb`, it force runs it (despite it having passed before).
- It now checks a hash whether a notebook changed, and if it did, it will rerun it even if the last run was a success (this should have probably been the behavior initially).
> tools: small fix to `run_notebooks`

- changelog.md
- lumicks/pylake/fitting/detail/derivative_manipulation.py
- lumicks/pylake/fitting/model.py
- lumicks/pylake/fitting/tests/test_model_sim.py
Noticed something odd in external code using the call operator on an inverted model (wrapping the independent variable in a list only to immediately extract it again after the call).
Turns out, calling the model with a scalar returns an error instead of working properly. Not ideal, so let's fix it.
> fdfitter: fix inversion for the scalar case

- lumicks/pylake/fitting/parameters.py
Without these docstrings, the properties simply don't show up in the docs.
> fdfit: add docstring to `Parameter`

- changelog.md
- lumicks/pylake/detail/mixin.py
- lumicks/pylake/tests/test_file/conftest.py
- lumicks/pylake/tests/test_file/test_file.py
- lumicks/pylake/tests/test_file/test_file_items.py
If the confocal diagnostics channel has no points before the item, these properties raise, while they should just return either an empty slice (if there is really no data) or a slice with the data that is still present.
> confocal: fix bug with empty power channels

- changelog.md
- docs/tutorial/figures/file/downsampling.png
- docs/tutorial/figures/file/first_plot.png
- docs/tutorial/figures/file/full_range.png
- docs/tutorial/figures/file/highlight_points.png
- docs/tutorial/figures/file/highlight_region.png
- docs/tutorial/figures/file/manual_seconds.png
- docs/tutorial/figures/file/marker_range.png
- docs/tutorial/figures/file/slice.png
- docs/tutorial/figures/file/slice_ts.png
- docs/tutorial/figures/file/start_time.png
- docs/tutorial/figures/file/timestamp_axis.png
- docs/tutorial/file.rst
- lumicks/pylake/channel.py
- lumicks/pylake/detail/plotting.py
- lumicks/pylake/detail/timeindex.py
- lumicks/pylake/tests/test_channels/test_channels.py
- lumicks/pylake/tests/test_timeindex.py
While working on the force calibration docs (not done yet), I found myself wanting to annotate some regions on a channel plot.
Instead of repeating the code in multiple notebooks / tutorials, I figured it might be a nice feature to just have in Pylake.
Docs build here: https://lumicks-pylake.readthedocs.io/en/highlight/tutorial/file.html#highlighting
```python
force.highlight_time_range(("50s", "85s"), annotation="region 2")
```
```python
force.highlight_time_range("50s", annotation="start 1", color="C0")
force.highlight_time_range("90s", annotation="start 2", color="C1")
```
```python
file.force1x.highlight_time_range(file.markers["Tether: 11"], annotation="marker")
```
> slice: add option to highlight time region

- docs/examples/droplet_fusion/droplet_fusion.rst
- docs/examples/droplet_fusion/droplet_size_pixels.png
- docs/examples/droplet_fusion/fit.png
- docs/examples/droplet_fusion/force_signal.png
- docs/examples/droplet_fusion/frame2.png
- docs/examples/droplet_fusion/frame6.png
- docs/examples/droplet_fusion/image_segmentation.png
- docs/examples/droplet_fusion/selected_data.png
- docs/examples/index.rst
An example of how to analyze a droplet fusion event
Build can be found here: https://lumicks-pylake.readthedocs.io/en/examples_droplet_fusion/examples/droplet_fusion/droplet_fusion.html
> Examples droplet fusion

- changelog.md
- docs/tutorial/figures/kymotracking/sample_from_channel.png
- docs/tutorial/kymotracking.rst
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/tests/test_image_sampling.py
It can be pretty error prone for users to do this themselves. To do this properly, they have to index `line_timestamp_ranges()` themselves and have to make sure the kymograph they apply that on is the one they have tracks of (and that it is cropped in the same way).
Docs build [here](https://lumicks-pylake.readthedocs.io/en/downsampled_over_track/tutorial/kymotracking.html#averaging-channel-data-over-tracks) and [here](https://lumicks-pylake.readthedocs.io/en/downsampled_over_track/_api/lumicks.pylake.kymotracker.kymotrack.KymoTrack.html#lumicks.pylake.kymotracker.kymotrack.KymoTrack.sample_from_channel).
> kymotrack: add `sample_from_channel`

- changelog.md
- lumicks/pylake/file_download.py
- lumicks/pylake/tests/test_file_download.py
We should not restrict what file names can be used in zenodo links as it will prohibit people from using this in their own notebooks.
The surface calibration data contains filenames with spaces which made me realize that we don't support non-url characters in file names.
> download: allow non-url characters in filenames

- .gitignore
- lumicks/pylake/kymotracker/tests/conftest.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
- lumicks/pylake/kymotracker/tests/test_refinement.py
- lumicks/pylake/tests/test_imaging_confocal/conftest.py
I notice some of our tests fail in some rare cases. I verified that these were false positives and they were related to the rng involved in making the fixture. This PR makes sure that all the fixtures are using a fixed seed.
Note that in the first commit I added a folder to the gitignore list, this is since on `main` we ignore a big `nb_test` folder that is used for semi-automatically testing notebooks that I would not like to have to stash or drop when rebasing every time. I intend to squash this to one commit.
> ci: make sure we used fixed seed in fixtures

- changelog.md
- docs/api.rst
- lumicks/pylake/force_calibration/calibration_item.py
- lumicks/pylake/force_calibration/calibration_models.py
- lumicks/pylake/force_calibration/tests/test_calibration_item.py
- This gives users an option to interrogate the parameter values and results of the diode calibration.
- After discussing this with hrishi, I have decided to return a small dataclass rather than expose direct access to the free function to ensure that we can change this model in the future if need be.
Docs build here: https://lumicks-pylake.readthedocs.io/en/expose_diode_model/_api/lumicks.pylake.calibration.ForceCalibrationItem.html#lumicks.pylake.calibration.ForceCalibrationItem.diode_calibration
> calibration: expose diode calibration

- .github/workflows/pylake_test.yml
- changelog.md
- docs/install.rst
- docs/tutorial/force_calibration.rst
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/kymotracker/kymotrack.py
- setup.py
We need to remove the `numpy` upper bound. When people install via pip, they will get `python` `3.13`. `numpy` is not going to release wheels for `1.24.x`for `3.13` and up. This means that people who made an environment with `python` `3.13` will end up in the situation where installing numpy will result in an attempt to compile it on their system (which often fails on windows).
I had a quick look and it seems that the only change that impacted us was the removal of `np.NaN` and the fact that `np.all([None, 5])` returns `None` for `numpy<2` and `False` for `numpy>=2`.
I piggybacked two tiny fixes to the documentation on this PR.
1. `Rf` is not present in items where the calibration was reset to unity, hence we want to use `Response (pN/V)` instead so people don't run into …
> deps: allow `numpy>=2`, add `python==3.13` to ci

- changelog.md
- lumicks/pylake/__about__.py
The main reason is to unpin `numpy` as it causes issues when installing with python `3.13`. That said, it is nice to release the bug fixes we have accrued on the release branch.
> release: release pylake `v1.5.3`

- lumicks/pylake/kymo.py
It's very minor, but it isn't always clear to users how the `kymo_args` argument is intended to be used. This hopefully helps with that.
> kymo: improve `plot_with_channels` docstring

- changelog.md
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/tests/test_fit.py
I got confused by the error message for a moment while setting up a multi-model fit.
If I get confused, it's likely to be even worse for an end user, hence a better error message seems in order.
> fdfit: add error message when model not found

- docs/examples/binding_lifetime/binding_lifetime.rst
- docs/examples/binding_lifetime/bootstrap1.png
- docs/examples/binding_lifetime/bootstrap2.png
- docs/examples/binding_lifetime/double_exponential_fit.png
- docs/examples/binding_lifetime/exponential_fit.png
- docs/examples/binding_lifetime/kymo1.png
- docs/examples/binding_lifetime/kymo2.png
- docs/examples/binding_lifetime/kymotracker.png
- docs/examples/binding_lifetime/profile1.png
- docs/examples/binding_lifetime/profile2.png
- docs/examples/index.rst
- docs/tutorial/kymotracking.rst
- docs/tutorial/population_dynamics.rst
Typical DPI workflow: how to fit one or multiple exponentials to a distribution of binding lifetimes and check which model is optimal.
Docs can be found here: https://lumicks-pylake.readthedocs.io/en/binding-lifetime-example/examples/binding_lifetime/binding_lifetime.html
> examples: add binding lifetime analysis

- changelog.md
- lumicks/pylake/channel.py
- lumicks/pylake/detail/utilities.py
- lumicks/pylake/tests/test_channels/test_arithmetic.py
- lumicks/pylake/tests/test_utilities.py
Dividing a slice by a scalar doesn't work properly for numpy arrays and other convertible types.
The bug basically boils down to the assumption that `np.isscalar(x)` would return `False` for `np.array(1)`, which it doesn't.
Considering that we want to start using a value class for several things, I think the safest approach would be to check whether what we have is convertible to a scalar explicitly, rather than direct type checking. This way we also preserve the type of the source data, and the behavior doesn't break if more scalar-like datatypes become available.
Please think of any cases I might have missed in the tests.
> slice: ensure operators work with all scalars

- changelog.md
- lumicks/pylake/force_calibration/calibration_results.py
- lumicks/pylake/force_calibration/detail/driving_input.py
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/power_spectrum_calibration.py
- lumicks/pylake/force_calibration/tests/test_power_model.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- A simpler constructor will allow easier construction of a `PowerSpectrum`. The benefits of this may not be evident in this PR, but a followup one will have pathological spectra constructed directly rather than ifft'ing the spectrum only to immediately fft it again.
- Keeping track of the uncut data will allow us to plot what we excluded.
- Keeping track of the high frequency data and performing the downsampling and exclusion/fit ranges lazily will allow us to do multiple analyses without the requirement to always recompute the expensive part (the FFT) or keep two separate power spectra around. It also means that we will be getting the full spectrum in the calibration routine, which will allow us to apply some improvements going forward.
- Plotting the driving peak for an active …
> PowerSpectrum: improve diagnostic value power spectrum api

- changelog.md
- lumicks/pylake/fitting/fit.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/fitting/tests/test_profiles.py
- lumicks/pylake/fitting/tests/test_stepping.py
- lumicks/pylake/population/dwelltime.py
Parameter profiles are computed by changing one parameter and re-optimizing all the others. This procedure is then repeated until we either hit a point where the fit gets significantly worse or we hit our parameter bounds.
When doing this, it is important to choose a step size of the step to make. Since the optimization part is the most expensive part, we do this adaptively _before_ optimizing. Basically we want the step to end up in some range of chi squared increase. 
We don't want it to be too large (since we don't want to end up in a different minimum). And we don't want it to be too small, because then we would take forever.
In some cases, during fd fitting, the chi squared increased so fast however that this adaptive system breaks down and we end up with step sizes …
> dwelltime: silence unnecessary warnings profiles

- lumicks/pylake/fitting/parameters.py
- lumicks/pylake/fitting/profile_likelihood.py
- lumicks/pylake/kymotracker/tests/test_kymotrack.py
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
For some purposes, we need a quantity that calculates an approximate standard error rapidly.
Asymptotics are useful especially when the problem is well constrained (lots of data and a well-suited model).
_2-component fit based on 100 dwells. Profile likelihood compared to asymptotic intervals. Confidence intervals would be given by the locations where the curves meet the threshold (dashed horizontal line)._
_2-component fit based on 1000 dwells. Profile likelihood compared to asymptotic intervals. Confidence intervals would be given by the locations where the curves meet the threshold (dashed horizontal line). Note how for lots of data, these two approaches produce almost identical results._
I have added the ability to plot them alongside the profiles, as it can be …
> dwelltime: add standard errors based on hessian approximation

- changelog.md
- docs/examples/bead_coupling/coupling.rst
- docs/examples/bead_coupling/single_result.png
- docs/examples/binding_lifetime/binding_lifetime.rst
- docs/examples/binding_lifetime/bootstrap1.png
- docs/examples/binding_lifetime/bootstrap2.png
- docs/examples/binding_lifetime/double_exponential_fit.png
- docs/examples/binding_lifetime/exponential_fit.png
- docs/run_notebooks.py
- docs/theory/force_calibration/active.rst
- docs/theory/force_calibration/figures/diffusion_spectra.png
- docs/theory/force_calibration/figures/hydro_fast.png
- docs/theory/force_calibration/figures/lorentzians.png
- docs/theory/force_calibration/passive.rst
- docs/tutorial/figures/population_dynamics/discrete_pop.png
- docs/tutorial/force_calibration/active_calibration.rst
- docs/tutorial/force_calibration/force_calibration.rst
- docs/tutorial/population_dynamics.rst
- docs/whatsnew/1.6.0/1_6_0.rst
- docs/whatsnew/1.6.0/new_examples.png
- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
I had hoped this would be the release PR already, but it turns out we need a few more small fixes before we can release.
1. It seems we haven't run the notebooks in a while, and some of the figures/numbers went out of date. The figures in the theory section were updated since they didn't take into account this [PR](https://github.com/lumicks/pylake/pull/613/files) yet. Some power spectral plots were updated, since they didn't take into account that we explicitly show the cuts now. Finally, [when it was first introduced](https://github.com/lumicks/pylake/pull/541/files#diff-2c94bbb8cdc4e7320db76b6434fff877418be37b52edc9c9b14a09fd86d7c5e7), the discrete dwell time plot did not enforce specifying a minimum observation time. Now it does, (as it should) by default, but the …
> release procedure fixes

- changelog.md
- lumicks/pylake/force_calibration/detail/calibration_properties.py
- lumicks/pylake/force_calibration/tests/test_calibration_item.py
The force sensitivity should correspond to `Rf` rather than the full response and should omit the sign. The reason for this is that we typically recalibrate using a ratio of sensitivities. We can do this since Bluelake is already always using the correct sign for the force data.
This helps keep things simple for users as the alternative would require users to either manually change the sign at the end, or the sign information would have to be propagated through the calibration models when recalibrating (which leads to an extra class parameter when initializing those).
Since some calibration items do not provide a value for `Rf`, I deferred to using the `Response (pN/V)` instead as it is always available. Unfortunately, I overlooked that the response can be negative and a …
> calibration: ensure `force_sensitivity` omits sign

- .readthedocs.yaml
readthedocs now [requires an explicit sphinx configuration](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/)
> docs: add explicit sphinx configuration

- changelog.md
- lumicks/pylake/force_calibration/power_spectrum.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum.py
These are two small improvements to `PowerSpectrum` that would make it a lot more convenient for me to use.
- `.compress()` is needed as in simulation studies, the spectra can become prohibitively memory consuming.
- The integer cast is simply convenience. I did consider explicitly adding `int | float` as an allowed parameter, but I felt that would signal the wrong intent. Also, raising for a `float` that is losslessly convertible to an `int` would be irritating as one frequently unpacks dictionaries coming from a bluelake dictionary (which are floats).
> power_spectrum: two tiny improvements

- changelog.md
- lumicks/pylake/kymotracker/kymotrack.py
Noticed this while working on #726, `load_tracks` uses `pixelsize_um` always when loading tracks from a CSV if photon counts are present.  If there are no photon counts, it works fine. 
A better solution to this and more robust test is included in #726 but it's good to have this in the next patch release
> Bugfix: `load_tracks` doesn't handle basepairs well

- .github/actions/check-python-packaging/action.yml
- .github/workflows/pylake_release.yml
- .github/workflows/pylake_test.yml
- pyproject.toml
**Why this PR**
- The strict `twine` check verifies the build before it goes out. Previously, I missed that the `README.md` wouldn't be picked up on a case-sensitive OS such as the one we use to deploy.
- We should also unpin `setuptools` to not stick with the deprecated source distribution name (`lumicks.pylake` -> `lumicks_pylake`).
> ci: verify before uploading, unpin setuptools

- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/kymotrack.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/kymotracker/tests/test_io.py
- lumicks/pylake/kymotracker/tests/test_kymotrackgroup_sources.py
- lumicks/pylake/nb_widgets/tests/test_image_editing.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_plotting.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_transforms.py
Often it's desirable to calibrate a kymo to basepairs without cropping out the beads. This is especially useful because tracking can be performed on the kymo straight from the `.h5` and exported; when re-loading the CSV you don't have to do any preprocessing for the kymo (besides calibrating to bp)
I also took this opportunity to consolidate the various calibration units into an `Enum` that also holds the "pretty" label that can be used for plotting. We've run into issues with this before with inconsistent formatting or unit names (here and in other projects) and hopefully this will help to avoid those issues.
> Calibrate kymo to basepairs without cropping

- changelog.md
- docs/tutorial/force_calibration/calibration_items.rst
- lumicks/pylake/calibration.py
- lumicks/pylake/channel.py
- lumicks/pylake/conftest.py
- lumicks/pylake/force_calibration/calibration_item.py
- lumicks/pylake/force_calibration/calibration_results.py
- lumicks/pylake/force_calibration/detail/calibration_properties.py
- lumicks/pylake/force_calibration/tests/test_calibration_item.py
- lumicks/pylake/force_calibration/tests/test_power_spectrum_calibration.py
- lumicks/pylake/piezo_tracking/piezo_tracking.py
- lumicks/pylake/piezo_tracking/tests/conftest.py
- lumicks/pylake/tests/test_channels/test_arithmetic.py
- lumicks/pylake/tests/test_channels/test_channels.py
- lumicks/pylake/tests/test_file/test_file.py
It is good to be able to recalibrate your force data.
By providing an API to do this, you basically end up with a force slice that can be treated as any other force slice (with a calibration item attached that conforms to a common API).
For instance, a recalibrated force slice can now directly be fed to the piezo tracking API (which reads from the calibration item).
Prior to implementing the new functionality, I removed some old cruftiness from the API that didn't really gel well with the new API. I left this as a separate commit.
Usage example:
```python
import lumicks.pylake as lk
f = lk.File("passive_calibration.h5")
calibration = f.force1x.calibration[1]  # Grab a calibration item for force 1x
calib_slice = f.force1x[calibration]
previous_calibration = …
```
> channel: support recalibrating force data

- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/tests/test_greedy_algorithm.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_transforms.py
Sometimes you want to calibrate your tether with a known orientation but without flipping the kymo. Followup to #726
> calibrate tether upside down

- docs/tutorial/figures/kymographs/background.png
- docs/tutorial/figures/kymographs/kymograph_selection.png
- docs/tutorial/figures/kymographs/photon_counts.png
- docs/tutorial/kymographs.rst
I frequently get questions about this workflow, so I added an example.
I decided to add the example in the 'Tutorial', but it would also fit under 'Examples'
On the one hand, there is no new syntax introduced, which makes it fit under 'Examples'.
On the other hand, the example is just very short and does not represent a full workflow, which makes it fit in the 'Tutorial'. Let me know what you think.
> kymograph tutorial: add section on photon counts

- docs/examples/binding_lifetime/binding_lifetime.rst
- docs/examples/index.rst
- docs/examples/kon/bootstrap.png
- docs/examples/kon/hist_fit.png
- docs/examples/kon/kon.png
- docs/examples/kon/kon.rst
- docs/examples/kon/kymo1.png
- docs/examples/kon/track_selection1.png
- docs/examples/kon/track_selection1_plot.png
- docs/examples/kon/track_selection2.png
- docs/examples/kon/tracks1.png
I added an example for a frequently requested workflow: kon.
Docs can be found here: https://lumicks-pylake.readthedocs.io/en/example_kon/examples/kon/kon.html
> examples: determine effective kon

- lumicks/pylake/population/dwelltime.py
- lumicks/pylake/population/tests/test_dwelltimes.py
Bootstrapping can become prohibitively expensive for large number of samples. This adds a small API which can be used to speed things up. Considering we may want >= 2 components in models we end up ranking this is low hanging fruit for speeding things up.
> dwelltime: allow parallel bootstraps

- docs/examples/kon/kon.rst
I updated a bug, Kd was wrongly referred to as Koff.
And I improved clarity by changing ‘binding time’ to ’time between binding events'
> example kon: fix bug and improve clarity

- changelog.md
- lumicks/pylake/kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_plotting.py
It seems that we did not consider the start time of the `kymo` versus the `timestamp` of the first data point when implementing `Kymo.plot_with_channels()`.
Considering that `line_timestamp_ranges()` typically does a lot more than we need (we only need the very first timestamp), I also added a small method to shortcut this calculation. The difference in performance is about 9x for a typical kymograph.
```python
f = lk.File("kymo.h5")
kymo = f.kymos["test_kymo"]
kymo.plot_with_channels(
[f["Photon count"]["Red"].downsampled_by(100),
f["Photon count"]["Red"].downsampled_over(kymo.line_timestamp_ranges())],
adjustment=lk.ColorAdjustment([0, 0, 0], [95, 100, 100], "percentile"),
titles=("Kymograph", "Downsampled 100", "Downsampled kymo")
) …
```
> kymo: fix bug in `Kymo.plot_with_channels()`

- changelog.md
- lumicks/pylake/detail/confocal.py
- lumicks/pylake/detail/pixel_calibration.py
- lumicks/pylake/kymo.py
- lumicks/pylake/kymotracker/detail/msd_estimation.py
- lumicks/pylake/kymotracker/kymotracker.py
- lumicks/pylake/scan.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
- lumicks/pylake/tests/test_imaging_confocal/test_kymo_transforms.py
Provides a public endpoint as requested in https://github.com/lumicks/pylake/issues/751.
Also looked into making the spatial calibration code a bit more homogeneous between `Scan` and `Kymo` and moved the calibration into its own file which helps keep the `Kymo` file manageable in size.
> confocal: add api for getting axis info
